package com.ripplehire.candidate.entities;

// Generated Oct 13, 2015 3:38:00 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActionReason generated by hbm2java
 */
@Entity
@Table(name = "action_reason")
public class ActionReason implements java.io.Serializable {

	private Integer actionReasonSeq;
	private Integer companyMstrSeq;
	private String rejectReason;
	private String type;
    private Integer priority;
	private Character status;
	private Integer createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public ActionReason() {
	}

	public ActionReason(Integer companyMstrSeq, String rejectReason,
                        Character status, Integer createdBy, Date createDttm,
                        Integer updatedBy, Date updateDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.rejectReason = rejectReason;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ACTION_REASON_SEQ", unique = true, nullable = false)
	public Integer getActionReasonSeq() {
		return this.actionReasonSeq;
	}

	public void setActionReasonSeq(Integer actionReasonSeq) {
		this.actionReasonSeq = actionReasonSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ")
	public Integer getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(Integer companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "REJECT_REASON", length = 100)
	public String getRejectReason() {
		return this.rejectReason;
	}

	public void setRejectReason(String rejectReason) {
		this.rejectReason = rejectReason;
	}

	@Column(name = "TYPE", length = 100)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

    @Column(name = "PRIORITY")
    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    @Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
