package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivitystageReward generated by hbm2java
 */
@Entity
@Table(name = "activitystage_reward")
public class ActivitystageReward implements java.io.Serializable {

	private Integer activitystageRewardSeq;
	private Reward reward;
	private ActivityMstr activityMstr;
	private int companyMstrSeq;
	private int stageNumber;
	private int activitystageCnt;
	private String activitystageDesc;
	private Integer activitystagePriority;
	private String restrictRewardCd;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public ActivitystageReward() {
	}

	public ActivitystageReward(Reward reward, ActivityMstr activityMstr,
			int companyMstrSeq, int stageNumber, int activitystageCnt,
			String activitystageDesc, char status, int createdBy,
			Date createDttm) {
		this.reward = reward;
		this.activityMstr = activityMstr;
		this.companyMstrSeq = companyMstrSeq;
		this.stageNumber = stageNumber;
		this.activitystageCnt = activitystageCnt;
		this.activitystageDesc = activitystageDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public ActivitystageReward(Reward reward, ActivityMstr activityMstr,
			int companyMstrSeq, int stageNumber, int activitystageCnt,
			String activitystageDesc, Integer activitystagePriority,
			String restrictRewardCd, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm) {
		this.reward = reward;
		this.activityMstr = activityMstr;
		this.companyMstrSeq = companyMstrSeq;
		this.stageNumber = stageNumber;
		this.activitystageCnt = activitystageCnt;
		this.activitystageDesc = activitystageDesc;
		this.activitystagePriority = activitystagePriority;
		this.restrictRewardCd = restrictRewardCd;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ACTIVITYSTAGE_REWARD_SEQ", unique = true, nullable = false)
	public Integer getActivitystageRewardSeq() {
		return this.activitystageRewardSeq;
	}

	public void setActivitystageRewardSeq(Integer activitystageRewardSeq) {
		this.activitystageRewardSeq = activitystageRewardSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REWARD_SEQ", nullable = false)
	public Reward getReward() {
		return this.reward;
	}

	public void setReward(Reward reward) {
		this.reward = reward;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTIVITY_MSTR_SEQ", nullable = false)
	public ActivityMstr getActivityMstr() {
		return this.activityMstr;
	}

	public void setActivityMstr(ActivityMstr activityMstr) {
		this.activityMstr = activityMstr;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "STAGE_NUMBER", nullable = false)
	public int getStageNumber() {
		return this.stageNumber;
	}

	public void setStageNumber(int stageNumber) {
		this.stageNumber = stageNumber;
	}

	@Column(name = "ACTIVITYSTAGE_CNT", nullable = false)
	public int getActivitystageCnt() {
		return this.activitystageCnt;
	}

	public void setActivitystageCnt(int activitystageCnt) {
		this.activitystageCnt = activitystageCnt;
	}

	@Column(name = "ACTIVITYSTAGE_DESC", nullable = false)
	public String getActivitystageDesc() {
		return this.activitystageDesc;
	}

	public void setActivitystageDesc(String activitystageDesc) {
		this.activitystageDesc = activitystageDesc;
	}

	@Column(name = "ACTIVITYSTAGE_PRIORITY")
	public Integer getActivitystagePriority() {
		return this.activitystagePriority;
	}

	public void setActivitystagePriority(Integer activitystagePriority) {
		this.activitystagePriority = activitystagePriority;
	}

	@Column(name = "RESTRICT_REWARD_CD", length = 20)
	public String getRestrictRewardCd() {
		return this.restrictRewardCd;
	}

	public void setRestrictRewardCd(String restrictRewardCd) {
		this.restrictRewardCd = restrictRewardCd;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
