package com.ripplehire.candidate.entities;

// Generated May 19, 2014 3:21:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivityMstr generated by hbm2java
 */
@Entity
@Table(name = "activity_mstr")
public class ActivityMstr implements java.io.Serializable {

	private Integer activityMstrSeq;
	private UserRole userRole;
	private int companyMstrSeq;
	private String activityCd;
	private String activityType;
	private String activityDesc;
	private int activityPriority;
	private Integer activityLimit;
	private String limitCriteria;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<GoalActivity> goalActivities = new HashSet<GoalActivity>(0);
	private Set<EmplActivity> emplActivities = new HashSet<EmplActivity>(0);
	private Set<ActivitystageReward> activitystageRewards = new HashSet<ActivitystageReward>(
			0);
	private Set<Reward> rewards = new HashSet<Reward>(0);

	public ActivityMstr() {
	}

	public ActivityMstr(UserRole userRole, int companyMstrSeq,
			String activityCd, String activityType, int activityPriority,
			char status, int createdBy, Date createDttm) {
		this.userRole = userRole;
		this.companyMstrSeq = companyMstrSeq;
		this.activityCd = activityCd;
		this.activityType = activityType;
		this.activityPriority = activityPriority;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public ActivityMstr(UserRole userRole, int companyMstrSeq,
			String activityCd, String activityType, String activityDesc,
			int activityPriority, Integer activityLimit, String limitCriteria,
			char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm, Set<GoalActivity> goalActivities,
			Set<EmplActivity> emplActivities,
			Set<ActivitystageReward> activitystageRewards, Set<Reward> rewards) {
		this.userRole = userRole;
		this.companyMstrSeq = companyMstrSeq;
		this.activityCd = activityCd;
		this.activityType = activityType;
		this.activityDesc = activityDesc;
		this.activityPriority = activityPriority;
		this.activityLimit = activityLimit;
		this.limitCriteria = limitCriteria;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.goalActivities = goalActivities;
		this.emplActivities = emplActivities;
		this.activitystageRewards = activitystageRewards;
		this.rewards = rewards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ACTIVITY_MSTR_SEQ", unique = true, nullable = false)
	public Integer getActivityMstrSeq() {
		return this.activityMstrSeq;
	}

	public void setActivityMstrSeq(Integer activityMstrSeq) {
		this.activityMstrSeq = activityMstrSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ROLE_SEQ", nullable = false)
	public UserRole getUserRole() {
		return this.userRole;
	}

	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "ACTIVITY_CD", nullable = false, length = 20)
	public String getActivityCd() {
		return this.activityCd;
	}

	public void setActivityCd(String activityCd) {
		this.activityCd = activityCd;
	}

	@Column(name = "ACTIVITY_TYPE", nullable = false, length = 20)
	public String getActivityType() {
		return this.activityType;
	}

	public void setActivityType(String activityType) {
		this.activityType = activityType;
	}

	@Column(name = "ACTIVITY_DESC")
	public String getActivityDesc() {
		return this.activityDesc;
	}

	public void setActivityDesc(String activityDesc) {
		this.activityDesc = activityDesc;
	}

	@Column(name = "ACTIVITY_PRIORITY", nullable = false)
	public int getActivityPriority() {
		return this.activityPriority;
	}

	public void setActivityPriority(int activityPriority) {
		this.activityPriority = activityPriority;
	}

	@Column(name = "ACTIVITY_LIMIT")
	public Integer getActivityLimit() {
		return this.activityLimit;
	}

	public void setActivityLimit(Integer activityLimit) {
		this.activityLimit = activityLimit;
	}

	@Column(name = "LIMIT_CRITERIA", length = 20)
	public String getLimitCriteria() {
		return this.limitCriteria;
	}

	public void setLimitCriteria(String limitCriteria) {
		this.limitCriteria = limitCriteria;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activityMstr")
	public Set<GoalActivity> getGoalActivities() {
		return this.goalActivities;
	}

	public void setGoalActivities(Set<GoalActivity> goalActivities) {
		this.goalActivities = goalActivities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activityMstr")
	public Set<EmplActivity> getEmplActivities() {
		return this.emplActivities;
	}

	public void setEmplActivities(Set<EmplActivity> emplActivities) {
		this.emplActivities = emplActivities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activityMstr")
	public Set<ActivitystageReward> getActivitystageRewards() {
		return this.activitystageRewards;
	}

	public void setActivitystageRewards(
			Set<ActivitystageReward> activitystageRewards) {
		this.activitystageRewards = activitystageRewards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activityMstr")
	public Set<Reward> getRewards() {
		return this.rewards;
	}

	public void setRewards(Set<Reward> rewards) {
		this.rewards = rewards;
	}

}
