package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CampaignJob generated by hbm2java
 */
@Entity
@Table(name = "campaign_job")
public class CampaignJob implements java.io.Serializable {

	private Integer campaignJobSeq;
	private Job job;
	private Campaign campaign;
	private int companyMstrSeq;
	private String jobType;
	private int jobPositions;
	private int jobPositionsClosed;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public CampaignJob() {
	}

	public CampaignJob(Job job, Campaign campaign, int companyMstrSeq,
			String jobType, int jobPositions, int jobPositionsClosed,
			char status, int createdBy, Date createDttm) {
		this.job = job;
		this.campaign = campaign;
		this.companyMstrSeq = companyMstrSeq;
		this.jobType = jobType;
		this.jobPositions = jobPositions;
		this.jobPositionsClosed = jobPositionsClosed;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CampaignJob(Job job, Campaign campaign, int companyMstrSeq,
			String jobType, int jobPositions, int jobPositionsClosed,
			char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm) {
		this.job = job;
		this.campaign = campaign;
		this.companyMstrSeq = companyMstrSeq;
		this.jobType = jobType;
		this.jobPositions = jobPositions;
		this.jobPositionsClosed = jobPositionsClosed;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CAMPAIGN_JOB_SEQ", unique = true, nullable = false)
	public Integer getCampaignJobSeq() {
		return this.campaignJobSeq;
	}

	public void setCampaignJobSeq(Integer campaignJobSeq) {
		this.campaignJobSeq = campaignJobSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_SEQ", nullable = false)
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAMPAIGN_SEQ", nullable = false)
	public Campaign getCampaign() {
		return this.campaign;
	}

	public void setCampaign(Campaign campaign) {
		this.campaign = campaign;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "JOB_TYPE", nullable = false, length = 10)
	public String getJobType() {
		return this.jobType;
	}

	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	@Column(name = "JOB_POSITIONS", nullable = false)
	public int getJobPositions() {
		return this.jobPositions;
	}

	public void setJobPositions(int jobPositions) {
		this.jobPositions = jobPositions;
	}

	@Column(name = "JOB_POSITIONS_CLOSED", nullable = false)
	public int getJobPositionsClosed() {
		return this.jobPositionsClosed;
	}

	public void setJobPositionsClosed(int jobPositionsClosed) {
		this.jobPositionsClosed = jobPositionsClosed;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
