package com.ripplehire.candidate.entities;
// Generated 31 Aug, 2016 1:04:36 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name = "candidate")
public class Candidate implements java.io.Serializable {

	private Integer candidateSeq;
	private UserProfile userProfile;
	private int companyMstrSeq;
	private String fbUrl;
	private String liUrl;
	private String firstName;
	private String middleName;
	private String lastName;
	private String fullName;
	private String salutation;
	private String skypeid;
	private String phoneNoExt;
	private String phoneNo;
	private String alternatePhoneNo;
	private String landlineNoExt;
	private String landlineNo;
	private String emailAddr;
	private String alternateEmailAddr;
	private String highestEducation;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String pinCode;
	private String country;
	private String permanantCountry;
	private String permanantAddressLine1;
	private String permanantState;
	private String permanantPincode;
	private String maritalStatus;
	private String infoByEmp;
	private String customSelect1;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<EmplRefrl> emplRefrls = new HashSet<EmplRefrl>(0);
	private Set<DuplicateCandidateLog> duplicateCandidateLogs = new HashSet<DuplicateCandidateLog>(0);
	private Set<CandidateResumedetails> candidateResumedetailses = new HashSet<CandidateResumedetails>(0);

	public Candidate() {
	}

	public Candidate(int companyMstrSeq, char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public Candidate(UserProfile userProfile, int companyMstrSeq, String fbUrl, String liUrl, String firstName,
					 String middleName, String lastName, String fullName, String salutation, String skypeid, String phoneNoExt,
					 String phoneNo, String alternatePhoneNo, String landlineNoExt, String landlineNo, String emailAddr,
					 String alternateEmailAddr, String highestEducation, String addressLine1, String addressLine2, String city,
					 String state, String pinCode, String country, String permanantCountry, String permanantAddressLine1,
					 String permanantState, String permanantPincode, String maritalStatus, String infoByEmp,
					 char status, int createdBy, Date createDttm, Integer updatedBy, Date updateDttm, Set<EmplRefrl> emplRefrls,
					 Set<DuplicateCandidateLog> duplicateCandidateLogs, Set<CandidateResumedetails> candidateResumedetailses) {
		this.userProfile = userProfile;
		this.companyMstrSeq = companyMstrSeq;
		this.fbUrl = fbUrl;
		this.liUrl = liUrl;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.fullName = fullName;
		this.salutation = salutation;
		this.skypeid = skypeid;
		this.phoneNoExt = phoneNoExt;
		this.phoneNo = phoneNo;
		this.alternatePhoneNo = alternatePhoneNo;
		this.landlineNoExt = landlineNoExt;
		this.landlineNo = landlineNo;
		this.emailAddr = emailAddr;
		this.alternateEmailAddr = alternateEmailAddr;
		this.highestEducation = highestEducation;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.pinCode = pinCode;
		this.country = country;
		this.permanantCountry = permanantCountry;
		this.permanantAddressLine1 = permanantAddressLine1;
		this.permanantState = permanantState;
		this.permanantPincode = permanantPincode;
		this.maritalStatus = maritalStatus;
		this.infoByEmp = infoByEmp;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.emplRefrls = emplRefrls;
		this.duplicateCandidateLogs = duplicateCandidateLogs;
		this.candidateResumedetailses = candidateResumedetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CANDIDATE_SEQ", unique = true, nullable = false)
	public Integer getCandidateSeq() {
		return this.candidateSeq;
	}

	public void setCandidateSeq(Integer candidateSeq) {
		this.candidateSeq = candidateSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PROFILE_SEQ")
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "FB_URL", length = 300)
	public String getFbUrl() {
		return this.fbUrl;
	}

	public void setFbUrl(String fbUrl) {
		this.fbUrl = fbUrl;
	}

	@Column(name = "LI_URL", length = 300)
	public String getLiUrl() {
		return this.liUrl;
	}

	public void setLiUrl(String liUrl) {
		this.liUrl = liUrl;
	}

	@Column(name = "FIRST_NAME", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "MIDDLE_NAME", length = 50)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "LAST_NAME", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "FULL_NAME", length = 260)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "SALUTATION", length = 60)
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	@Column(name = "SKYPE_ID", length = 100)
	public String getSkypeid() {
		return this.skypeid;
	}

	public void setSkypeid(String skypeid) {
		this.skypeid = skypeid;
	}

	@Column(name = "PHONE_NO_EXT", length = 10)
	public String getPhoneNoExt() {
		return this.phoneNoExt;
	}

	public void setPhoneNoExt(String phoneNoExt) {
		this.phoneNoExt = phoneNoExt;
	}

	@Column(name = "PHONE_NO", length = 15)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "ALTERNATE_PHONE_NO", length = 100)
	public String getAlternatePhoneNo() {
		return this.alternatePhoneNo;
	}

	public void setAlternatePhoneNo(String alternatePhoneNo) {
		this.alternatePhoneNo = alternatePhoneNo;
	}

	@Column(name = "LANDLINE_NO_EXT", length = 10)
	public String getLandlineNoExt() {
		return this.landlineNoExt;
	}

	public void setLandlineNoExt(String landlineNoExt) {
		this.landlineNoExt = landlineNoExt;
	}

	@Column(name = "LANDLINE_NO", length = 15)
	public String getLandlineNo() {
		return this.landlineNo;
	}

	public void setLandlineNo(String landlineNo) {
		this.landlineNo = landlineNo;
	}

	@Column(name = "EMAIL_ADDR", length = 50)
	public String getEmailAddr() {
		return this.emailAddr;
	}

	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	@Column(name = "ALTERNATE_EMAIL_ADDR", length = 50)
	public String getAlternateEmailAddr() {
		return this.alternateEmailAddr;
	}

	public void setAlternateEmailAddr(String alternateEmailAddr) {
		this.alternateEmailAddr = alternateEmailAddr;
	}

	@Column(name = "HIGHEST_EDUCATION", length = 100)
	public String getHighestEducation() {
		return this.highestEducation;
	}

	public void setHighestEducation(String highestEducation) {
		this.highestEducation = highestEducation;
	}

	@Column(name = "ADDRESS_LINE_1", length = 200)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE_2", length = 200)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "CITY", length = 60)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 60)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "PIN_CODE", length = 10)
	public String getPinCode() {
		return this.pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	@Column(name = "COUNTRY", length = 60)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "PERMANANT_COUNTRY", length = 100)
	public String getPermanantCountry() {
		return this.permanantCountry;
	}

	public void setPermanantCountry(String permanantCountry) {
		this.permanantCountry = permanantCountry;
	}

	@Column(name = "PERMANANT_ADDRESS_LINE_1", length = 100)
	public String getPermanantAddressLine1() {
		return this.permanantAddressLine1;
	}

	public void setPermanantAddressLine1(String permanantAddressLine1) {
		this.permanantAddressLine1 = permanantAddressLine1;
	}

	@Column(name = "PERMANANT_STATE", length = 100)
	public String getPermanantState() {
		return this.permanantState;
	}

	public void setPermanantState(String permanantState) {
		this.permanantState = permanantState;
	}

	@Column(name = "PERMANANT_PINCODE", length = 100)
	public String getPermanantPincode() {
		return this.permanantPincode;
	}

	public void setPermanantPincode(String permanantPincode) {
		this.permanantPincode = permanantPincode;
	}

	@Column(name = "MARITAL_STATUS", length = 100)
	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "INFO_BY_EMP", length = 1000)
	public String getInfoByEmp() {
		return this.infoByEmp;
	}

	public void setInfoByEmp(String infoByEmp) {
		this.infoByEmp = infoByEmp;
	}

	@Column(name = "CUSTOM_SELECT_1", length = 200)
	public String getCustomSelect1() {
		return customSelect1;
	}

	public void setCustomSelect1(String customSelect1) {
		this.customSelect1 = customSelect1;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<EmplRefrl> getEmplRefrls() {
		return this.emplRefrls;
	}

	public void setEmplRefrls(Set<EmplRefrl> emplRefrls) {
		this.emplRefrls = emplRefrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<DuplicateCandidateLog> getDuplicateCandidateLogs() {
		return this.duplicateCandidateLogs;
	}

	public void setDuplicateCandidateLogs(Set<DuplicateCandidateLog> duplicateCandidateLogs) {
		this.duplicateCandidateLogs = duplicateCandidateLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidate")
	public Set<CandidateResumedetails> getCandidateResumedetailses() {
		return this.candidateResumedetailses;
	}

	public void setCandidateResumedetailses(Set<CandidateResumedetails> candidateResumedetailses) {
		this.candidateResumedetailses = candidateResumedetailses;
	}

}
