package com.ripplehire.candidate.entities;

// Generated Jun 11, 2015 7:19:30 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CandidateUploadResumeDetails generated by hbm2java
 */
@Entity
@Table(name = "candidate_upload_resume_details")
public class CandidateUploadResumeDetails implements java.io.Serializable {

	private Integer candidateUploadResumeDetails;
	private RefrlChannelMstr refrlChannelMstr;
	private EmplRefrl emplRefrl;
	private Integer companyMstrSeq;
	private Integer userProfileSeq;
	private Integer jobSeq;
	private String empEmail;
	private String vendorId;
	private String candidateResumeFileName;
	private String candidateResumeActualFileName;
	private String uploadBatchId;
	private String uploadStatus;
	private CandidateUploadParsedData candidateUploadParsedData;
    private String displayTitle;
	private char status;
	private int createdBy;
	private Date createdDttm;
	private Integer updatedBy;
	private Date updatedDttm;

	public CandidateUploadResumeDetails() {
	}

	public CandidateUploadResumeDetails(char status, int createdBy,
			Date createdDttm) {
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public CandidateUploadResumeDetails(RefrlChannelMstr refrlChannelMstr,
			EmplRefrl emplRefrl, Integer companyMstrSeq,
			Integer userProfileSeq, Integer jobSeq, String vendorId,
			String candidateResumeFileName,
			String candidateResumeActualFileName, String uploadBatchId,
			String uploadStatus, CandidateUploadParsedData candidateUploadParsedData, char status,
			int createdBy, Date createdDttm, Integer updatedBy, Date updatedDttm) {
		this.refrlChannelMstr = refrlChannelMstr;
		this.emplRefrl = emplRefrl;
		this.companyMstrSeq = companyMstrSeq;
		this.userProfileSeq = userProfileSeq;
		this.jobSeq = jobSeq;
		this.vendorId = vendorId;
		this.candidateResumeFileName = candidateResumeFileName;
		this.candidateResumeActualFileName = candidateResumeActualFileName;
		this.uploadBatchId = uploadBatchId;
		this.uploadStatus = uploadStatus;
		this.candidateUploadParsedData = candidateUploadParsedData;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CANDIDATE_UPLOAD_RESUME_DETAILS", unique = true, nullable = false)
	public Integer getCandidateUploadResumeDetails() {
		return this.candidateUploadResumeDetails;
	}

	public void setCandidateUploadResumeDetails(
			Integer candidateUploadResumeDetails) {
		this.candidateUploadResumeDetails = candidateUploadResumeDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOURCE_CHANNEL")
	public RefrlChannelMstr getRefrlChannelMstr() {
		return this.refrlChannelMstr;
	}

	public void setRefrlChannelMstr(RefrlChannelMstr refrlChannelMstr) {
		this.refrlChannelMstr = refrlChannelMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_REFRL_SEQ")
	public EmplRefrl getEmplRefrl() {
		return this.emplRefrl;
	}

	public void setEmplRefrl(EmplRefrl emplRefrl) {
		this.emplRefrl = emplRefrl;
	}

	@Column(name = "COMPANY_MSTR_SEQ")
	public Integer getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(Integer companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "USER_PROFILE_SEQ")
	public Integer getUserProfileSeq() {
		return this.userProfileSeq;
	}

	public void setUserProfileSeq(Integer userProfileSeq) {
		this.userProfileSeq = userProfileSeq;
	}

	@Column(name = "JOB_SEQ")
	public Integer getJobSeq() {
		return this.jobSeq;
	}

	public void setJobSeq(Integer jobSeq) {
		this.jobSeq = jobSeq;
	}

	@Column(name = "EMP_EMAIL", length = 100)
	public String getEmpEmail() {
		return this.empEmail;
	}

	public void setEmpEmail(String empEmail) {
		this.empEmail = empEmail;
	}

	@Column(name = "VENDOR_ID", length=100)
	public String getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(String vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "CANDIDATE_RESUME_FILE_NAME", length = 100)
	public String getCandidateResumeFileName() {
		return this.candidateResumeFileName;
	}

	public void setCandidateResumeFileName(String candidateResumeFileName) {
		this.candidateResumeFileName = candidateResumeFileName;
	}

	@Column(name = "CANDIDATE_RESUME_ACTUAL_FILE_NAME", length = 100)
	public String getCandidateResumeActualFileName() {
		return this.candidateResumeActualFileName;
	}

	public void setCandidateResumeActualFileName(
			String candidateResumeActualFileName) {
		this.candidateResumeActualFileName = candidateResumeActualFileName;
	}

	@Column(name = "UPLOAD_BATCH_ID", length = 50)
	public String getUploadBatchId() {
		return this.uploadBatchId;
	}

	public void setUploadBatchId(String uploadBatchId) {
		this.uploadBatchId = uploadBatchId;
	}

    @Column(name = "DISPLAY_TITLE", length = 100)
    public String getDisplayTitle() {
        return displayTitle;
    }

    public void setDisplayTitle(String displayTitle) {
        this.displayTitle = displayTitle;
    }

    @Column(name = "UPLOAD_STATUS", length = 50)
	public String getUploadStatus() {
		return this.uploadStatus;
	}

	public void setUploadStatus(String uploadStatus) {
		this.uploadStatus = uploadStatus;
	}

    @ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CANDIDATE_UPLOAD_PARSED_DATA_SEQ")
	public CandidateUploadParsedData getCandidateUploadParsedData() {
		return this.candidateUploadParsedData;
	}

	public void setCandidateUploadParsedData(CandidateUploadParsedData candidateUploadParsedData) {
		this.candidateUploadParsedData = candidateUploadParsedData;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

}
