package com.ripplehire.candidate.entities;

// Generated Aug 3, 2015 1:39:41 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CandidateResumeData generated by hbm2java
 */
@Entity
@Table(name = "candidate_resume_data")
public class CandidateResumeData implements java.io.Serializable {

	private Integer candidateResumeDataSeq;
	private CandidateResumedetails candidateResumedetails;
	private int companyMstrSeq;
	private String resumeData;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public CandidateResumeData() {
	}

	public CandidateResumeData(CandidateResumedetails candidateResumedetails,
							   int companyMstrSeq, char status, int createdBy, Date createDttm) {
		this.candidateResumedetails = candidateResumedetails;
		this.companyMstrSeq = companyMstrSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CandidateResumeData(CandidateResumedetails candidateResumedetails,
							   int companyMstrSeq, String resumeData, char status, int createdBy,
							   Date createDttm, Integer updatedBy, Date updateDttm) {
		this.candidateResumedetails = candidateResumedetails;
		this.companyMstrSeq = companyMstrSeq;
		this.resumeData = resumeData;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CANDIDATE_RESUME_DATA_SEQ", unique = true, nullable = false)
	public Integer getCandidateResumeDataSeq() {
		return this.candidateResumeDataSeq;
	}

	public void setCandidateResumeDataSeq(Integer candidateResumeDataSeq) {
		this.candidateResumeDataSeq = candidateResumeDataSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CANDIDATE_RESUMEDETAILS_SEQ", nullable = false)
	public CandidateResumedetails getCandidateResumedetails() {
		return this.candidateResumedetails;
	}

	public void setCandidateResumedetails(
			CandidateResumedetails candidateResumedetails) {
		this.candidateResumedetails = candidateResumedetails;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Lob
	@Column(name = "RESUME_DATA", nullable = false, length = 2147483647)
	public String getResumeData() {
		return this.resumeData;
	}

	public void setResumeData(String resumeData) {
		this.resumeData = resumeData;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
