package com.ripplehire.candidate.entities;

// Generated Dec 11, 2014 5:19:15 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CandidateResumedetails generated by hbm2java
 */
@Entity
@Table(name = "candidate_resumedetails")
public class CandidateResumedetails implements java.io.Serializable {

	private Integer candidateResumedetailsSeq;
	private GenderMstr genderMstr;
	private CurrentLocationMstr currentLocationMstr;
	private Candidate candidate;
	private QualificationMstr qualificationMstr;
	private CountryMstr countryMstr;
	private CurrentEmployerMstr currentEmployerMstr;
	private RelationshipMstr relationshipMstr;
	private CurrencyMstr currencyMstr;
    private VendorProfile vendorProfile;
	private int companyMstrSeq;
	private Integer day;
	private Integer month;
	private Integer year;
	private String skills;
	private String otherEmployer;
	private String otherQualification;
	private Integer yearsExp;
	private Integer relevantExp;
	private Double currentCtc;
	private Double expectedCtc;
	private Float billRate;
	private Integer billRateCurrency;
	private String billRateBasis;
	private Integer noticePeriod;
	private String resumeSynopsis;
	private String resumeSubDirectory;
	private String resumeFileRefNm;
	private String resumeFileRefActualNm;
	private String candidateImageSubDirectory;
	private String candidateImage;
	private String candidateImageActualNm;
	private Integer resumeFileSize;
	private String notetoRecruter;
	private String industry;
	private String subIndustry;
	private String passportNo;
	private String pancardNo;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private String highestDeg;
	private String highestDegStream;
	private Integer highestDegYear;
	private Integer highestDegPerc;
	private Integer highestDegBacklogs;
	private String certifications;
	private Float hscAggPerc;
	private Integer sscAggPerc;
	private String parsedResume;
	private String isFakeEmployer;
	private String isFakeQualification;
    private String fakeInfo;
	private String ethnicity;
	private String vendorEmail;
    private String vendorPhoneNoExt;
    private String vendorPhoneNo;
    private String militaryServices;
	private Character jobApplyTerms;

	private String relocate;
	private String citizenship;
	private String university;
	private String twitterHandle;
	private String portfolio;
	private String startDate;
	private String disability;

	private char agencyTerms;
	private String candidatePassion;
	private String custom1;
	private String custom2;
	private String custom3;
	private String custom4;
	private String custom5;
	private String custom6;
	private String custom7;
	private String custom8;
	private String custom9;
	private String custom10;
	private String custom11;
	private String custom12;

    private Set<CandidateLog> candidateLogs = new HashSet<CandidateLog>(0);
	private Set<EmplRefrl> emplRefrls = new HashSet<EmplRefrl>(0);
	private Set<CandidateSkills> candidateSkillses = new HashSet<CandidateSkills>(0);
	private Set<CandidateResumeData> candidateResumeDatas = new HashSet<CandidateResumeData>(0);

	public CandidateResumedetails() {
	}

	public CandidateResumedetails(Candidate candidate, int companyMstrSeq,
			char status, int createdBy, Date createDttm) {
		this.candidate = candidate;
		this.companyMstrSeq = companyMstrSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CandidateResumedetails(GenderMstr genderMstr,
			CurrentLocationMstr currentLocationMstr, Candidate candidate,
			QualificationMstr qualificationMstr, CountryMstr countryMstr,
			CurrentEmployerMstr currentEmployerMstr,
			RelationshipMstr relationshipMstr, CurrencyMstr currencyMstr,
            VendorProfile vendorProfile,
			int companyMstrSeq, Integer day, Integer month, Integer year,
			String skills, String otherEmployer, String otherQualification,
			Integer yearsExp, Integer relevantExp, Double currentCtc,
            Double expectedCtc, Integer noticePeriod, String resumeSynopsis, String resumeSubDirectory,
			String resumeFileRefNm, String resumeFileRefActualNm, String candidateImage, String candidateImageActualNm,
			Integer resumeFileSize, String notetoRecruter, String industry, String subIndustry,
			String passportNo, String pancardNo, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm,
			String highestDeg, String highestDegStream, Integer highestDegYear,
			Integer highestDegPerc, Integer highestDegBacklogs,
			String certifications, Float hscAggPerc, Integer sscAggPerc,String parsedResume, String isFakeEmployer, String isFakeQualification,
			Set<CandidateLog> candidateLogs, Set<EmplRefrl> emplRefrls,
			Set<CandidateSkills> candidateSkillses, Set<CandidateResumeData> candidateResumeDatas) {
		this.genderMstr = genderMstr;
		this.currentLocationMstr = currentLocationMstr;
		this.candidate = candidate;
		this.qualificationMstr = qualificationMstr;
		this.countryMstr = countryMstr;
		this.currentEmployerMstr = currentEmployerMstr;
		this.relationshipMstr = relationshipMstr;
		this.currencyMstr = currencyMstr;
        this.vendorProfile = vendorProfile;
		this.companyMstrSeq = companyMstrSeq;
		this.day = day;
		this.month = month;
		this.year = year;
		this.skills = skills;
		this.otherEmployer = otherEmployer;
		this.otherQualification = otherQualification;
		this.yearsExp = yearsExp;
		this.relevantExp = relevantExp;
		this.currentCtc = currentCtc;
		this.expectedCtc = expectedCtc;
		this.noticePeriod = noticePeriod;
		this.resumeSynopsis = resumeSynopsis;
		this.resumeSubDirectory = resumeSubDirectory;
		this.resumeFileRefNm = resumeFileRefNm;
		this.resumeFileRefActualNm = resumeFileRefActualNm;
		this.resumeFileSize = resumeFileSize;
		this.notetoRecruter = notetoRecruter;
		this.industry = industry;
		this.subIndustry = subIndustry;
		this.passportNo = passportNo;
		this.pancardNo = pancardNo;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.highestDeg = highestDeg;
		this.highestDegStream = highestDegStream;
		this.highestDegYear = highestDegYear;
		this.highestDegPerc = highestDegPerc;
		this.highestDegBacklogs = highestDegBacklogs;
		this.certifications = certifications;
		this.hscAggPerc = hscAggPerc;
		this.sscAggPerc = sscAggPerc;
		this.parsedResume = parsedResume;
		this.isFakeEmployer = isFakeEmployer;
		this.isFakeQualification = isFakeQualification;
		this.candidateLogs = candidateLogs;
		this.emplRefrls = emplRefrls;
		this.candidateSkillses = candidateSkillses;
		this.candidateResumeDatas = candidateResumeDatas;
		this.candidateImage = candidateImage;
		this.candidateImageActualNm = candidateImageActualNm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CANDIDATE_RESUMEDETAILS_SEQ", unique = true, nullable = false)
	public Integer getCandidateResumedetailsSeq() {
		return this.candidateResumedetailsSeq;
	}

	public void setCandidateResumedetailsSeq(Integer candidateResumedetailsSeq) {
		this.candidateResumedetailsSeq = candidateResumedetailsSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GENDER_MSTR_SEQ")
	public GenderMstr getGenderMstr() {
		return this.genderMstr;
	}

	public void setGenderMstr(GenderMstr genderMstr) {
		this.genderMstr = genderMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENT_LOCATION_MSTR_SEQ")
	public CurrentLocationMstr getCurrentLocationMstr() {
		return this.currentLocationMstr;
	}

	public void setCurrentLocationMstr(CurrentLocationMstr currentLocationMstr) {
		this.currentLocationMstr = currentLocationMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CANDIDATE_SEQ", nullable = false)
	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUALIFICATION_MSTR_SEQ")
	public QualificationMstr getQualificationMstr() {
		return this.qualificationMstr;
	}

	public void setQualificationMstr(QualificationMstr qualificationMstr) {
		this.qualificationMstr = qualificationMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_MSTR_SEQ")
	public CountryMstr getCountryMstr() {
		return this.countryMstr;
	}

	public void setCountryMstr(CountryMstr countryMstr) {
		this.countryMstr = countryMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENT_EMPLOYER_MSTR_SEQ")
	public CurrentEmployerMstr getCurrentEmployerMstr() {
		return this.currentEmployerMstr;
	}

	public void setCurrentEmployerMstr(CurrentEmployerMstr currentEmployerMstr) {
		this.currentEmployerMstr = currentEmployerMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RELATIONSHIP_MSTR_SEQ")
	public RelationshipMstr getRelationshipMstr() {
		return this.relationshipMstr;
	}

	public void setRelationshipMstr(RelationshipMstr relationshipMstr) {
		this.relationshipMstr = relationshipMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENCY_MSTR_SEQ")
	public CurrencyMstr getCurrencyMstr() {
		return this.currencyMstr;
	}

	public void setCurrencyMstr(CurrencyMstr currencyMstr) {
		this.currencyMstr = currencyMstr;
	}

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "VENDOR_PROFILE_SEQ")
    public VendorProfile getVendorProfile() {
        return this.vendorProfile;
    }

    public void setVendorProfile(VendorProfile vendorProfile) {
        this.vendorProfile = vendorProfile;
    }

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "DAY")
	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	@Column(name = "MONTH")
	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	@Column(name = "YEAR")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "SKILLS", length = 3000)
	public String getSkills() {
		return this.skills;
	}

	public void setSkills(String skills) {
		this.skills = skills;
	}

	@Column(name = "OTHER_EMPLOYER", length = 100)
	public String getOtherEmployer() {
		return this.otherEmployer;
	}

	public void setOtherEmployer(String otherEmployer) {
		this.otherEmployer = otherEmployer;
	}

	@Column(name = "OTHER_QUALIFICATION", length = 100)
	public String getOtherQualification() {
		return this.otherQualification;
	}

	public void setOtherQualification(String otherQualification) {
		this.otherQualification = otherQualification;
	}

	@Column(name = "YEARS_EXP")
	public Integer getYearsExp() {
		return this.yearsExp;
	}

	public void setYearsExp(Integer yearsExp) {
		this.yearsExp = yearsExp;
	}

	@Column(name = "RELEVANT_EXP")
	public Integer getRelevantExp() {
		return this.relevantExp;
	}

	public void setRelevantExp(Integer relevantExp) {
		this.relevantExp = relevantExp;
	}

	@Column(name = "CURRENT_CTC", precision = 20, scale = 5)
	public Double getCurrentCtc() {
		return this.currentCtc;
	}

	public void setCurrentCtc(Double currentCtc) {
		this.currentCtc = currentCtc;
	}

	@Column(name = "EXPECTED_CTC", precision = 20, scale = 5)
	public Double getExpectedCtc() {
		return this.expectedCtc;
	}

	public void setExpectedCtc(Double expectedCtc) {
		this.expectedCtc = expectedCtc;
	}

	public void setBillRate(Float billRate) {
		this.billRate = billRate;
	}

	@Column(name = "BILL_RATE", precision = 20, scale = 10)
	public Float getBillRate() {
		return this.billRate;
	}

	@Column(name = "BILL_RATE_CURRENCY")
	public Integer getBillRateCurrency() {
		return this.billRateCurrency;
	}

	public void setBillRateCurrency(Integer billRateCurrency) {
		this.billRateCurrency = billRateCurrency;
	}

	@Column(name = "BILL_RATE_BASIS")
	public String getBillRateBasis() {
		return this.billRateBasis;
	}

	public void setBillRateBasis(String billRateBasis) {
		this.billRateBasis = billRateBasis;
	}


	@Column(name = "NOTICE_PERIOD")
	public Integer getNoticePeriod() {
		return this.noticePeriod;
	}

	public void setNoticePeriod(Integer noticePeriod) {
		this.noticePeriod = noticePeriod;
	}

	@Column(name = "RESUME_SYNOPSIS", length = 400)
	public String getResumeSynopsis() {
		return this.resumeSynopsis;
	}

	public void setResumeSynopsis(String resumeSynopsis) {
		this.resumeSynopsis = resumeSynopsis;
	}

	@Column(name = "RESUME_SUB_DIRECTORY", length = 400)
	public String getResumeSubDirectory() {
		return resumeSubDirectory;
	}

	public void setResumeSubDirectory(String resumeSubDirectory) {
		this.resumeSubDirectory = resumeSubDirectory;
	}

	@Column(name = "RESUME_FILE_REF_NM", length = 150)
	public String getResumeFileRefNm() {
		return this.resumeFileRefNm;
	}

	public void setResumeFileRefNm(String resumeFileRefNm) {
		this.resumeFileRefNm = resumeFileRefNm;
	}

	@Column(name = "RESUME_FILE_REF_ACTUAL_NM", length = 100)
	public String getResumeFileRefActualNm() {
		return this.resumeFileRefActualNm;
	}

	public void setResumeFileRefActualNm(String resumeFileRefActualNm) {
		this.resumeFileRefActualNm = resumeFileRefActualNm;
	}

	@Column(name = "CANDIDATE_IMAGE_SUB_DIRECTORY", length = 400)
	public String getCandidateImageSubDirectory() {
		return candidateImageSubDirectory;
	}

	public void setCandidateImageSubDirectory(String candidateImageSubDirectory) {
		this.candidateImageSubDirectory = candidateImageSubDirectory;
	}

	@Column(name = "CANDIDATE_IMAGE", length = 200)
	public String getCandidateImage() {
		return this.candidateImage;
	}

	public void setCandidateImage(String candidateImage) {
		this.candidateImage = candidateImage;
	}

	@Column(name = "CANDIDATE_IMAGE_ACTUAL_NM", length = 200)
	public String getCandidateImageActualNm() {
		return this.candidateImageActualNm;
	}

	public void setCandidateImageActualNm(String candidateImageActualNm) {
		this.candidateImageActualNm = candidateImageActualNm;
	}

	@Column(name = "RESUME_FILE_SIZE")
	public Integer getResumeFileSize() {
		return this.resumeFileSize;
	}

	public void setResumeFileSize(Integer resumeFileSize) {
		this.resumeFileSize = resumeFileSize;
	}

	@Column(name = "NOTETO_RECRUTER", length = 3000)
	public String getNotetoRecruter() {
		return this.notetoRecruter;
	}

	public void setNotetoRecruter(String notetoRecruter) {
		this.notetoRecruter = notetoRecruter;
	}

	@Column(name = "INDUSTRY", length = 100)
	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	@Column(name = "SUB_INDUSTRY", length = 100)
	public String getSubIndustry() {
		return this.subIndustry;
	}

	public void setSubIndustry(String subIndustry) {
		this.subIndustry = subIndustry;
	}

	@Column(name = "PASSPORT_NO", length = 100)
	public String getPassportNo() {
		return this.passportNo;
	}

	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}

	@Column(name = "PANCARD_NO", length = 100)
	public String getPancardNo() {
		return this.pancardNo;
	}

	public void setPancardNo(String pancardNo) {
		this.pancardNo = pancardNo;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@Column(name = "HIGHEST_DEG", length = 100)
	public String getHighestDeg() {
		return this.highestDeg;
	}

	public void setHighestDeg(String highestDeg) {
		this.highestDeg = highestDeg;
	}

	@Column(name = "HIGHEST_DEG_STREAM", length = 100)
	public String getHighestDegStream() {
		return this.highestDegStream;
	}

	public void setHighestDegStream(String highestDegStream) {
		this.highestDegStream = highestDegStream;
	}

	@Column(name = "HIGHEST_DEG_YEAR")
	public Integer getHighestDegYear() {
		return this.highestDegYear;
	}

	public void setHighestDegYear(Integer highestDegYear) {
		this.highestDegYear = highestDegYear;
	}

	@Column(name = "HIGHEST_DEG_PERC")
	public Integer getHighestDegPerc() {
		return this.highestDegPerc;
	}

	public void setHighestDegPerc(Integer highestDegPerc) {
		this.highestDegPerc = highestDegPerc;
	}

	@Column(name = "HIGHEST_DEG_BACKLOGS")
	public Integer getHighestDegBacklogs() {
		return this.highestDegBacklogs;
	}

	public void setHighestDegBacklogs(Integer highestDegBacklogs) {
		this.highestDegBacklogs = highestDegBacklogs;
	}

	@Column(name = "CERTIFICATIONS", length = 200)
	public String getCertifications() {
		return this.certifications;
	}

	public void setCertifications(String certifications) {
		this.certifications = certifications;
	}

	@Column(name = "HSC_AGG_PERC")
	public Float getHscAggPerc() {
		return this.hscAggPerc;
	}

	public void setHscAggPerc(Float hscAggPerc) {
		this.hscAggPerc = hscAggPerc;
	}

	@Column(name = "SSC_AGG_PERC")
	public Integer getSscAggPerc() {
		return this.sscAggPerc;
	}

	public void setSscAggPerc(Integer sscAggPerc) {
		this.sscAggPerc = sscAggPerc;
	}

	@Lob
	@Column(name = "RESUME_DATA", nullable = false, length = 2147483647)
	public String getParsedResume() {
		return this.parsedResume;
	}

	public void setParsedResume(String parsedResume) {
		this.parsedResume = parsedResume;
	}

	@Column(name = "IS_FAKE_EMPLOYER", length = 2)
	public String getIsFakeEmployer() {
		return this.isFakeEmployer;
	}

	public void setIsFakeEmployer(String isFakeEmployer) {
		this.isFakeEmployer = isFakeEmployer;
	}

	@Column(name = "IS_FAKE_QUALIFICATION", length = 2)
	public String getIsFakeQualification() {
		return this.isFakeQualification;
	}

	public void setIsFakeQualification(String isFakeQualification) {
		this.isFakeQualification = isFakeQualification;
	}

    @Column(name = "FAKE_INFO", length = 200)
    public String getFakeInfo() {        return fakeInfo;    }

    public void setFakeInfo(String fakeInfo) {        this.fakeInfo = fakeInfo;    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "candidateResumedetails")
	public Set<CandidateLog> getCandidateLogs() {
		return this.candidateLogs;
	}

	public void setCandidateLogs(Set<CandidateLog> candidateLogs) {
		this.candidateLogs = candidateLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidateResumedetails")
	public Set<EmplRefrl> getEmplRefrls() {
		return this.emplRefrls;
	}

	public void setEmplRefrls(Set<EmplRefrl> emplRefrls) {
		this.emplRefrls = emplRefrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidateResumedetails")
	public Set<CandidateSkills> getCandidateSkillses() {
		return this.candidateSkillses;
	}

	public void setCandidateSkillses(Set<CandidateSkills> candidateSkillses) {
		this.candidateSkillses = candidateSkillses;
	}

    @Column(name = "ETHNICITY", length = 100)
    public String getEthnicity() {
        return ethnicity;
    }

    public void setEthnicity(String ethnicity) {
        this.ethnicity = ethnicity;
    }

	@Column(name = "VENDOR_EMAIL", length = 100)
	public String getVendorEmail() {
		return vendorEmail;
	}

	public void setVendorEmail(String vendorEmail) {
		this.vendorEmail = vendorEmail;
	}

	@Column(name = "VENDOR_PHONE_NO_EXT", length = 10)
    public String getVendorPhoneNoExt() {
        return vendorPhoneNoExt;
    }

    public void setVendorPhoneNoExt(String vendorPhoneNoExt) {
        this.vendorPhoneNoExt = vendorPhoneNoExt;
    }

    @Column(name = "VENDOR_PHONE_NO", length = 10)
    public String getVendorPhoneNo() {
        return vendorPhoneNo;
    }

    public void setVendorPhoneNo(String vendorPhoneNo) {
        this.vendorPhoneNo = vendorPhoneNo;
    }

    @Column(name = "MILITARY_SERVICES", length = 150)
    public String getMilitaryServices() {
        return militaryServices;
    }

    public void setMilitaryServices(String militaryServices) {
        this.militaryServices = militaryServices;
    }


	@Column(name = "JOB_APPLY_TERMS", length = 1)
	public Character getJobApplyTerms() {
		return jobApplyTerms;
	}

	public void setJobApplyTerms(Character jobApplyTerms) {
		this.jobApplyTerms = jobApplyTerms;
	}

	@Column(name = "RELOCATE", length = 10)
	public String getRelocate() {
		return relocate;
	}

	public void setRelocate(String relocate) {
		this.relocate = relocate;
	}

	@Column(name = "CITIZENSHIP", length = 50)
	public String getCitizenship() {
		return citizenship;
	}

	public void setCitizenship(String citizenship) {
		this.citizenship = citizenship;
	}

	@Column(name = "UNIVERSITY", length = 50)
	public String getUniversity() {
		return university;
	}

	public void setUniversity(String university) {
		this.university = university;
	}

	@Column(name = "TWITTER_HANDLE", length = 50)
	public String getTwitterHandle() {
		return twitterHandle;
	}

	public void setTwitterHandle(String twitterHandle) {
		this.twitterHandle = twitterHandle;
	}

	@Column(name = "PORTFOLIO", length = 50)
	public String getPortfolio() {
		return portfolio;
	}

	public void setPortfolio(String portfolio) {
		this.portfolio = portfolio;
	}

	@Column(name = "START_DATE", length = 20)
	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "DISABILITY", length = 150)
	public String getDisability() {
		return disability;
	}

	public void setDisability(String disability) {
		this.disability = disability;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidateResumedetails")
	public Set<CandidateResumeData> getCandidateResumeDatas() {
		return this.candidateResumeDatas;
	}

	public void setCandidateResumeDatas(
			Set<CandidateResumeData> candidateResumeDatas) {
		this.candidateResumeDatas = candidateResumeDatas;
	}

	@Column(name = "VENDOR_TERMS", length = 1)
	public char getAgencyTerms() {
		return agencyTerms;
	}

	public void setAgencyTerms(char agencyTerms) {
		this.agencyTerms = agencyTerms;
	}

	@Column(name = "PASSION", length = 100)
	public String getCandidatePassion() {
		return candidatePassion;
	}

	public void setCandidatePassion(String candidatePassion) {
		this.candidatePassion = candidatePassion;
	}

	@Column(name = "CUSTOM1", length = 500)
	public String getCustom1() {
		return custom1;
	}

	public void setCustom1(String custom1) {
		this.custom1 = custom1;
	}

	@Column(name = "CUSTOM2", length = 500)
	public String getCustom2() {
		return custom2;
	}

	public void setCustom2(String custom2) {
		this.custom2 = custom2;
	}

	@Column(name = "CUSTOM3", length = 500)
	public String getCustom3() {
		return custom3;
	}

	public void setCustom3(String custom3) {
		this.custom3 = custom3;
	}

	@Column(name = "CUSTOM4", length = 500)
	public String getCustom4() {
		return custom4;
	}

	public void setCustom4(String custom4) {
		this.custom4 = custom4;
	}

	@Column(name = "CUSTOM5", length = 500)
	public String getCustom5() {
		return custom5;
	}

	public void setCustom5(String custom5) {
		this.custom5 = custom5;
	}

	@Column(name = "CUSTOM6", length = 500)
	public String getCustom6() {
		return custom6;
	}

	public void setCustom6(String custom6) {
		this.custom6 = custom6;
	}

	@Column(name = "CUSTOM7", length = 500)
	public String getCustom7() {
		return custom7;
	}

	public void setCustom7(String custom7) {
		this.custom7 = custom7;
	}

	@Column(name = "CUSTOM8", length = 500)
	public String getCustom8() {
		return custom8;
	}

	public void setCustom8(String custom8) {
		this.custom8 = custom8;
	}

	@Column(name = "CUSTOM9", length = 500)
	public String getCustom9() {
		return custom9;
	}

	public void setCustom9(String custom9) {
		this.custom9 = custom9;
	}

	@Column(name = "CUSTOM10", length = 500)
	public String getCustom10() {
		return custom10;
	}

	public void setCustom10(String custom10) {
		this.custom10 = custom10;
	}

	@Column(name = "CUSTOM11", length = 500)
	public String getCustom11() {
		return custom11;
	}

	public void setCustom11(String custom11) {
		this.custom11 = custom11;
	}

	@Column(name = "CUSTOM12", length = 500)
	public String getCustom12() {
		return custom12;
	}

	public void setCustom12(String custom12) {
		this.custom12 = custom12;
	}
}
