package com.ripplehire.candidate.entities;

// Generated Jun 11, 2015 7:19:30 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CandidateUploadResumeDetails generated by hbm2java
 */
@Entity
@Table(name = "candidate_upload_parsed_data")
public class CandidateUploadParsedData implements java.io.Serializable {

	private Integer candidateUploadParsedDataSeq;
    private Set<CandidateUploadResumeDetails> candidateUploadResumeDetailses = new HashSet<CandidateUploadResumeDetails>(
            0);
	private String parsedResume;
	private char status;
	private int createdBy;
	private Date createdDttm;
	private Integer updatedBy;
	private Date updatedDttm;

	public CandidateUploadParsedData() {
	}

    public CandidateUploadParsedData(String parsedResume) {
        this.parsedResume = parsedResume;
        this.createdDttm = new Date();
        this.createdBy= 1;
    }

    public CandidateUploadParsedData(Integer candidateUploadParsedDataSeq, Set<CandidateUploadResumeDetails> candidateUploadResumeDetailses, String parsedResume, char status, int createdBy, Date createdDttm, Integer updatedBy, Date updatedDttm) {
        this.candidateUploadParsedDataSeq = candidateUploadParsedDataSeq;
        this.candidateUploadResumeDetailses = candidateUploadResumeDetailses;
        this.parsedResume = parsedResume;
        this.status = status;
        this.createdBy = createdBy;
        this.createdDttm = createdDttm;
        this.updatedBy = updatedBy;
        this.updatedDttm = updatedDttm;
    }


    @Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CANDIDATE_UPLOAD_PARSED_DATA_SEQ", unique = true, nullable = false)
	public Integer getCandidateUploadParsedDataSeq() {
        return candidateUploadParsedDataSeq;
    }

    public void setCandidateUploadParsedDataSeq(Integer candidateUploadParsedDataSeq) {
        this.candidateUploadParsedDataSeq = candidateUploadParsedDataSeq;
    }


    @Column(name = "PARSED_RESUME")
	public String getParsedResume() {
		return this.parsedResume;
	}

	public void setParsedResume(String parsedResume) {
		this.parsedResume = parsedResume;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "candidateUploadParsedData")
    public Set<CandidateUploadResumeDetails> getCandidateUploadResumeDetailses() {
        return this.candidateUploadResumeDetailses;
    }

    public void setCandidateUploadResumeDetailses(
            Set<CandidateUploadResumeDetails> candidateUploadResumeDetailses) {
        this.candidateUploadResumeDetailses = candidateUploadResumeDetailses;
    }

}
