package com.ripplehire.candidate.entities;
// Generated 10 Oct, 2017 4:32:21 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CandidatePageLayout generated by hbm2java
 */
@Entity
@Table(name = "candidate_page_layout")
public class CandidatePageLayout implements java.io.Serializable {

	private Integer candidatePageLayoutSeq;
	private int companyMstrSeq;
	private String pageCd;
	private String pageDesc;
	private String layoutType;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public CandidatePageLayout() {
	}

	public CandidatePageLayout(int companyMstrSeq, String pageCd, String pageDesc, String layoutType, char status,
			int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.pageCd = pageCd;
		this.pageDesc = pageDesc;
		this.layoutType = layoutType;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CandidatePageLayout(int companyMstrSeq, String pageCd, String pageDesc, String layoutType, char status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.pageCd = pageCd;
		this.pageDesc = pageDesc;
		this.layoutType = layoutType;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CANDIDATE_PAGE_LAYOUT_SEQ", unique = true, nullable = false)
	public Integer getCandidatePageLayoutSeq() {
		return this.candidatePageLayoutSeq;
	}

	public void setCandidatePageLayoutSeq(Integer candidatePageLayoutSeq) {
		this.candidatePageLayoutSeq = candidatePageLayoutSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "PAGE_CD", nullable = false, length = 50)
	public String getPageCd() {
		return this.pageCd;
	}

	public void setPageCd(String pageCd) {
		this.pageCd = pageCd;
	}

	@Column(name = "PAGE_DESC", nullable = false, length = 100)
	public String getPageDesc() {
		return this.pageDesc;
	}

	public void setPageDesc(String pageDesc) {
		this.pageDesc = pageDesc;
	}

	@Column(name = "LAYOUT_TYPE", nullable = false, length = 100)
	public String getLayoutType() {
		return this.layoutType;
	}

	public void setLayoutType(String layoutType) {
		this.layoutType = layoutType;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
