package com.ripplehire.candidate.entities;
// Generated 11 Oct, 2017 4:57:39 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CandidatePageRegions generated by hbm2java
 */
@Entity
@Table(name = "candidate_page_regions")
public class CandidatePageRegions implements java.io.Serializable {

	private Integer candidatePageRegionSeq;
	private CandidatePageLayout candidatePageLayout;
	private int companyMstrSeq;
	private String regionCd;
	private String regionDesc;
	private String regionType;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public CandidatePageRegions() {
	}

	public CandidatePageRegions(CandidatePageLayout candidatePageLayout, int companyMstrSeq, String regionCd,
			String regionDesc, String regionType, char status, int createdBy, Date createDttm) {
		this.candidatePageLayout = candidatePageLayout;
		this.companyMstrSeq = companyMstrSeq;
		this.regionCd = regionCd;
		this.regionDesc = regionDesc;
		this.regionType = regionType;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CandidatePageRegions(CandidatePageLayout candidatePageLayout, int companyMstrSeq, String regionCd,
			String regionDesc, String regionType, char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm) {
		this.candidatePageLayout = candidatePageLayout;
		this.companyMstrSeq = companyMstrSeq;
		this.regionCd = regionCd;
		this.regionDesc = regionDesc;
		this.regionType = regionType;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CANDIDATE_PAGE_REGION_SEQ", unique = true, nullable = false)
	public Integer getCandidatePageRegionSeq() {
		return this.candidatePageRegionSeq;
	}

	public void setCandidatePageRegionSeq(Integer candidatePageRegionSeq) {
		this.candidatePageRegionSeq = candidatePageRegionSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CANDIDATE_PAGE_LAYOUT_SEQ", nullable = false)
	public CandidatePageLayout getCandidatePageLayout() {
		return this.candidatePageLayout;
	}

	public void setCandidatePageLayout(CandidatePageLayout candidatePageLayout) {
		this.candidatePageLayout = candidatePageLayout;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "REGION_CD", nullable = false, length = 50)
	public String getRegionCd() {
		return this.regionCd;
	}

	public void setRegionCd(String regionCd) {
		this.regionCd = regionCd;
	}

	@Column(name = "REGION_DESC", nullable = false, length = 100)
	public String getRegionDesc() {
		return this.regionDesc;
	}

	public void setRegionDesc(String regionDesc) {
		this.regionDesc = regionDesc;
	}

	@Column(name = "REGION_TYPE", nullable = false, length = 100)
	public String getRegionType() {
		return this.regionType;
	}

	public void setRegionType(String regionType) {
		this.regionType = regionType;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
