package com.ripplehire.candidate.entities;
// Generated Feb 10, 2016 4:38:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CandidateCustomData generated by hbm2java
 */
@Entity
@Table(name = "candidate_custom_data")
public class CandidateCustomData implements java.io.Serializable {

	private Integer candidateCustomDataSeq;
	private String customtext1;
	private String customtext2;
	private String customtext3;
	private String customtext4;
	private String customtext5;
	private String customtext6;
	private String customtext7;
	private String customtext8;
	private String customtext9;
	private String customtext10;
	private String customtext11;
	private String customtext12;
	private String customtext13;
	private String customtext14;
	private String customtext15;
	private String customtext16;
	private String customtext17;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public CandidateCustomData() {
	}

	public CandidateCustomData(char status, int createdBy, Date createDttm) {
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CandidateCustomData(String customtext1, String customtext2, String customtext3, String customtext4,
			String customtext5, String customtext6, String customtext7, String customtext8, String customtext9,
			String customtext10, String customtext11, String customtext12, String customtext13, String customtext14,
			String customtext15, String customtext16, String customtext17, char status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm) {
		this.customtext1 = customtext1;
		this.customtext2 = customtext2;
		this.customtext3 = customtext3;
		this.customtext4 = customtext4;
		this.customtext5 = customtext5;
		this.customtext6 = customtext6;
		this.customtext7 = customtext7;
		this.customtext8 = customtext8;
		this.customtext9 = customtext9;
		this.customtext10 = customtext10;
		this.customtext11 = customtext11;
		this.customtext12 = customtext12;
		this.customtext13 = customtext13;
		this.customtext14 = customtext14;
		this.customtext15 = customtext15;
		this.customtext16 = customtext16;
		this.customtext17 = customtext17;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CANDIDATE_CUSTOM_DATA_SEQ", unique = true, nullable = false)
	public Integer getCandidateCustomDataSeq() {
		return this.candidateCustomDataSeq;
	}

	public void setCandidateCustomDataSeq(Integer candidateCustomDataSeq) {
		this.candidateCustomDataSeq = candidateCustomDataSeq;
	}

	@Column(name = "CUSTOMTEXT_1", length = 100)
	public String getCustomtext1() {
		return this.customtext1;
	}

	public void setCustomtext1(String customtext1) {
		this.customtext1 = customtext1;
	}

	@Column(name = "CUSTOMTEXT_2", length = 100)
	public String getCustomtext2() {
		return this.customtext2;
	}

	public void setCustomtext2(String customtext2) {
		this.customtext2 = customtext2;
	}

	@Column(name = "CUSTOMTEXT_3", length = 100)
	public String getCustomtext3() {
		return this.customtext3;
	}

	public void setCustomtext3(String customtext3) {
		this.customtext3 = customtext3;
	}

	@Column(name = "CUSTOMTEXT_4", length = 100)
	public String getCustomtext4() {
		return this.customtext4;
	}

	public void setCustomtext4(String customtext4) {
		this.customtext4 = customtext4;
	}

	@Column(name = "CUSTOMTEXT_5", length = 100)
	public String getCustomtext5() {
		return this.customtext5;
	}

	public void setCustomtext5(String customtext5) {
		this.customtext5 = customtext5;
	}

	@Column(name = "CUSTOMTEXT_6", length = 100)
	public String getCustomtext6() {
		return this.customtext6;
	}

	public void setCustomtext6(String customtext6) {
		this.customtext6 = customtext6;
	}

	@Column(name = "CUSTOMTEXT_7", length = 100)
	public String getCustomtext7() {
		return this.customtext7;
	}

	public void setCustomtext7(String customtext7) {
		this.customtext7 = customtext7;
	}

	@Column(name = "CUSTOMTEXT_8", length = 100)
	public String getCustomtext8() {
		return this.customtext8;
	}

	public void setCustomtext8(String customtext8) {
		this.customtext8 = customtext8;
	}

	@Column(name = "CUSTOMTEXT_9", length = 100)
	public String getCustomtext9() {
		return this.customtext9;
	}

	public void setCustomtext9(String customtext9) {
		this.customtext9 = customtext9;
	}

	@Column(name = "CUSTOMTEXT_10", length = 100)
	public String getCustomtext10() {
		return this.customtext10;
	}

	public void setCustomtext10(String customtext10) {
		this.customtext10 = customtext10;
	}

	@Column(name = "CUSTOMTEXT_11", length = 100)
	public String getCustomtext11() {
		return this.customtext11;
	}

	public void setCustomtext11(String customtext11) {
		this.customtext11 = customtext11;
	}

	@Column(name = "CUSTOMTEXT_12", length = 100)
	public String getCustomtext12() {
		return this.customtext12;
	}

	public void setCustomtext12(String customtext12) {
		this.customtext12 = customtext12;
	}

	@Column(name = "CUSTOMTEXT_13", length = 100)
	public String getCustomtext13() {
		return this.customtext13;
	}

	public void setCustomtext13(String customtext13) {
		this.customtext13 = customtext13;
	}

	@Column(name = "CUSTOMTEXT_14", length = 100)
	public String getCustomtext14() {
		return this.customtext14;
	}

	public void setCustomtext14(String customtext14) {
		this.customtext14 = customtext14;
	}

	@Column(name = "CUSTOMTEXT_15", length = 100)
	public String getCustomtext15() {
		return this.customtext15;
	}

	public void setCustomtext15(String customtext15) {
		this.customtext15 = customtext15;
	}

	@Column(name = "CUSTOMTEXT_16", length = 100)
	public String getCustomtext16() {
		return this.customtext16;
	}

	public void setCustomtext16(String customtext16) {
		this.customtext16 = customtext16;
	}

	@Column(name = "CUSTOMTEXT_17", length = 100)
	public String getCustomtext17() {
		return this.customtext17;
	}

	public void setCustomtext17(String customtext17) {
		this.customtext17 = customtext17;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
