package com.ripplehire.candidate.entities;

// Generated Aug 13, 2014 1:39:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CandidateLog generated by hbm2java
 */
@Entity
@Table(name = "candidate_log")
public class CandidateLog implements java.io.Serializable {

	private Integer candidateLogSeq;
	private EmplRefrl emplRefrl;
	private CandidateResumedetails candidateResumedetails;
	private Integer companyMstrSeq;
	private String responseOne;
	private String responseTwo;
	private String comments;
	private String firstName;
	private String lastName;
	private String phoneNo;
	private String landlineNo;
	private Integer day;
	private Integer month;
	private Integer year;
	private String emailAddr;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public CandidateLog() {
	}

	public CandidateLog(char status, int createdBy, Date createDttm) {
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CandidateLog(EmplRefrl emplRefrl,
			CandidateResumedetails candidateResumedetails,
			Integer companyMstrSeq, String responseOne, String responseTwo,
			String comments, String firstName, String lastName, String phoneNo,
			String landlineNo, Integer day, Integer month, Integer year,
			String emailAddr, char status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm) {
		this.emplRefrl = emplRefrl;
		this.candidateResumedetails = candidateResumedetails;
		this.companyMstrSeq = companyMstrSeq;
		this.responseOne = responseOne;
		this.responseTwo = responseTwo;
		this.comments = comments;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNo = phoneNo;
		this.landlineNo = landlineNo;
		this.day = day;
		this.month = month;
		this.year = year;
		this.emailAddr = emailAddr;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CANDIDATE_LOG_SEQ", unique = true, nullable = false)
	public Integer getCandidateLogSeq() {
		return this.candidateLogSeq;
	}

	public void setCandidateLogSeq(Integer candidateLogSeq) {
		this.candidateLogSeq = candidateLogSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_REFRL_SEQ")
	public EmplRefrl getEmplRefrl() {
		return this.emplRefrl;
	}

	public void setEmplRefrl(EmplRefrl emplRefrl) {
		this.emplRefrl = emplRefrl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CANDIDATE_RESUMEDETAILS_SEQ")
	public CandidateResumedetails getCandidateResumedetails() {
		return this.candidateResumedetails;
	}

	public void setCandidateResumedetails(
			CandidateResumedetails candidateResumedetails) {
		this.candidateResumedetails = candidateResumedetails;
	}

	@Column(name = "COMPANY_MSTR_SEQ")
	public Integer getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(Integer companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "RESPONSE_ONE", length = 200)
	public String getResponseOne() {
		return this.responseOne;
	}

	public void setResponseOne(String responseOne) {
		this.responseOne = responseOne;
	}

	@Column(name = "RESPONSE_TWO", length = 200)
	public String getResponseTwo() {
		return this.responseTwo;
	}

	public void setResponseTwo(String responseTwo) {
		this.responseTwo = responseTwo;
	}

	@Column(name = "COMMENTS", length = 300)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "FIRST_NAME", length = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 30)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "PHONE_NO", length = 15)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "LANDLINE_NO", length = 15)
	public String getLandlineNo() {
		return this.landlineNo;
	}

	public void setLandlineNo(String landlineNo) {
		this.landlineNo = landlineNo;
	}

	@Column(name = "DAY")
	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	@Column(name = "MONTH")
	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	@Column(name = "YEAR")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "EMAIL_ADDR", length = 50)
	public String getEmailAddr() {
		return this.emailAddr;
	}

	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
