package com.ripplehire.candidate.entities;

// Generated Jun 18, 2015 4:43:37 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CandidateEthnicity generated by hbm2java
 */
@Entity
@Table(name = "candidate_ethnicity")
public class CandidateEthnicity implements java.io.Serializable {

	private Integer candidateEthnicitySeq;
	private Integer companyMstrSeq;
	private String ethnicityDesc;
	private char status;
	private char createdBy;
	private Date createDttm;
	private Character updatedBy;
	private Date updateDttm;

	public CandidateEthnicity() {
	}

	public CandidateEthnicity(char status, char createdBy, Date createDttm) {
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CandidateEthnicity(Integer companyMstrSeq, String ethnicityDesc,
			char status, char createdBy, Date createDttm, Character updatedBy,
			Date updateDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.ethnicityDesc = ethnicityDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CANDIDATE_ETHNICITY_SEQ", unique = true, nullable = false)
	public Integer getCandidateEthnicitySeq() {
		return this.candidateEthnicitySeq;
	}

	public void setCandidateEthnicitySeq(Integer candidateEthnicitySeq) {
		this.candidateEthnicitySeq = candidateEthnicitySeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ")
	public Integer getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(Integer companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "ETHNICITY_DESC", length = 100)
	public String getEthnicityDesc() {
		return this.ethnicityDesc;
	}

	public void setEthnicityDesc(String ethnicityDesc) {
		this.ethnicityDesc = ethnicityDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 1)
	public char getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(char createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY", length = 1)
	public Character getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Character updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
