package com.ripplehire.candidate.entities;

// Generated Aug 12, 2014 2:57:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CandidateSkills generated by hbm2java
 */
@Entity
@Table(name = "candidate_skills")
public class CandidateSkills implements java.io.Serializable {

	private Integer candidateSkillsSeq;
	private CandidateResumedetails candidateResumedetails;
	private SkillsMstr skillsMstr;
	private int companyMstrSeq;
	private String skillType;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public CandidateSkills() {
	}

	public CandidateSkills(CandidateResumedetails candidateResumedetails,
			SkillsMstr skillsMstr, int companyMstrSeq, char status, int createdBy, Date createDttm) {
		this.candidateResumedetails = candidateResumedetails;
		this.skillsMstr = skillsMstr;
		this.companyMstrSeq = companyMstrSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CandidateSkills(CandidateResumedetails candidateResumedetails,
			SkillsMstr skillsMstr, int companyMstrSeq, String skillType, char status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm) {
		this.candidateResumedetails = candidateResumedetails;
		this.skillsMstr = skillsMstr;
		this.companyMstrSeq = companyMstrSeq;
		this.skillType = skillType;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CANDIDATE_SKILLS_SEQ", unique = true, nullable = false)
	public Integer getCandidateSkillsSeq() {
		return this.candidateSkillsSeq;
	}

	public void setCandidateSkillsSeq(Integer candidateSkillsSeq) {
		this.candidateSkillsSeq = candidateSkillsSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CANDIDATE_RESUMEDETAILS_SEQ", nullable = false)
	public CandidateResumedetails getCandidateResumedetails() {
		return this.candidateResumedetails;
	}

	public void setCandidateResumedetails(
			CandidateResumedetails candidateResumedetails) {
		this.candidateResumedetails = candidateResumedetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SKILLS_MSTR_SEQ", nullable = false)
	public SkillsMstr getSkillsMstr() {
		return this.skillsMstr;
	}

	public void setSkillsMstr(SkillsMstr skillsMstr) {
		this.skillsMstr = skillsMstr;
	}
	
	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}
	
	@Column(name = "SKILL_TYPE", length = 1)
	public String getSkillType() {
		return this.skillType;
	}

	public void setSkillType(String skillType) {
		this.skillType = skillType;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
