package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city")
public class City implements java.io.Serializable {

	private Integer citySeq;
	private State state;
	private Country country;
	private String cityName;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Set<CityLang> cityLangs = new HashSet<CityLang>(0);

	public City() {
	}

	public City(State state, Country country, String cityName, char status,
			int createdBy, Date createDttm) {
		this.state = state;
		this.country = country;
		this.cityName = cityName;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public City(State state, Country country, String cityName, char status,
			int createdBy, Date createDttm, Set<CityLang> cityLangs) {
		this.state = state;
		this.country = country;
		this.cityName = cityName;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.cityLangs = cityLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CITY_SEQ", unique = true, nullable = false)
	public Integer getCitySeq() {
		return this.citySeq;
	}

	public void setCitySeq(Integer citySeq) {
		this.citySeq = citySeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_SEQ", nullable = false)
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_SEQ", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "CITY_NAME", nullable = false, length = 50)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<CityLang> getCityLangs() {
		return this.cityLangs;
	}

	public void setCityLangs(Set<CityLang> cityLangs) {
		this.cityLangs = cityLangs;
	}

}
