package com.ripplehire.candidate.entities;

// Generated Jan 29, 2015 7:15:52 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientCustomItemMstr generated by hbm2java
 */
@Entity
@Table(name = "client_custom_item_mstr")
public class ClientCustomItemMstr implements java.io.Serializable {

	private Integer clientCustomItemMstrSeq;
	private int companyMstrSeq;
	private String customItemClientId;
	private String customItemDesc;
	private String customItemType;
    private String displayPage;
    private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public ClientCustomItemMstr() {
	}

	public ClientCustomItemMstr(int companyMstrSeq, String customItemClientId,
			String customItemType, char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.customItemClientId = customItemClientId;
		this.customItemType = customItemType;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public ClientCustomItemMstr(int companyMstrSeq, String customItemClientId,
			String customItemDesc, String customItemType, char status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.customItemClientId = customItemClientId;
		this.customItemDesc = customItemDesc;
		this.customItemType = customItemType;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CLIENT_CUSTOM_ITEM_MSTR_SEQ", unique = true, nullable = false)
	public Integer getClientCustomItemMstrSeq() {
		return this.clientCustomItemMstrSeq;
	}

	public void setClientCustomItemMstrSeq(Integer clientCustomItemMstrSeq) {
		this.clientCustomItemMstrSeq = clientCustomItemMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "CUSTOM_ITEM_CLIENT_ID", nullable = false, length = 100)
	public String getCustomItemClientId() {
		return this.customItemClientId;
	}

	public void setCustomItemClientId(String customItemClientId) {
		this.customItemClientId = customItemClientId;
	}

	@Column(name = "CUSTOM_ITEM_DESC", length = 100)
	public String getCustomItemDesc() {
		return this.customItemDesc;
	}

	public void setCustomItemDesc(String customItemDesc) {
		this.customItemDesc = customItemDesc;
	}

	@Column(name = "CUSTOM_ITEM_TYPE", nullable = false, length = 50)
	public String getCustomItemType() {
		return this.customItemType;
	}

	public void setCustomItemType(String customItemType) {
		this.customItemType = customItemType;
	}

    @Column(name = "DISPLAY_PAGE", length = 50)
    public String getDisplayPage() {        return displayPage;    }

    public void setDisplayPage(String displayPage) {        this.displayPage = displayPage;    }

    @Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
