package com.ripplehire.candidate.entities;

// Generated Feb 6, 2015 4:18:05 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ClientCustomMapping generated by hbm2java
 */
@Entity
@Table(name = "client_custom_mapping", uniqueConstraints = @UniqueConstraint(columnNames = {
        "COMPANY_MSTR_SEQ", "EXTERNAL_KEY" }))
public class ClientCustomMapping implements java.io.Serializable {

    private Integer clientCustomMappingSeq;
    private int companyMstrSeq;
    private String internalKey;
    private Integer internalSubStatusSeq;
    private String externalKey;
    private String type;
    private char status;
    private int createdBy;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;

    public ClientCustomMapping() {
    }

    public ClientCustomMapping(int companyMstrSeq, String internalKey,
                               String externalKey, char status, int createdBy, Date createDttm) {
        this.companyMstrSeq = companyMstrSeq;
        this.internalKey = internalKey;
        this.externalKey = externalKey;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
    }

    public ClientCustomMapping(int companyMstrSeq, String internalKey,
                               String externalKey, char status, int createdBy, Date createDttm,
                               Integer updatedBy, Date updateDttm) {
        this.companyMstrSeq = companyMstrSeq;
        this.internalKey = internalKey;
        this.externalKey = externalKey;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "CLIENT_CUSTOM_MAPPING_SEQ", unique = true, nullable = false)
    public Integer getClientCustomMappingSeq() {
        return this.clientCustomMappingSeq;
    }

    public void setClientCustomMappingSeq(Integer clientCustomMappingSeq) {
        this.clientCustomMappingSeq = clientCustomMappingSeq;
    }

    @Column(name = "COMPANY_MSTR_SEQ", nullable = false)
    public int getCompanyMstrSeq() {
        return this.companyMstrSeq;
    }

    public void setCompanyMstrSeq(int companyMstrSeq) {
        this.companyMstrSeq = companyMstrSeq;
    }

    @Column(name = "INTERNAL_KEY", nullable = false, length = 50)
    public String getInternalKey() {
        return this.internalKey;
    }

    public void setInternalKey(String internalKey) {
        this.internalKey = internalKey;
    }

    @Column(name = "INTERNAL_SUB_STATUS_SEQ", nullable = true)
    public Integer getInternalSubStatusSeq() {
        return internalSubStatusSeq;
    }

    public void setInternalSubStatusSeq(Integer internalSubStatusSeq) {
        this.internalSubStatusSeq = internalSubStatusSeq;
    }

    @Column(name = "EXTERNAL_KEY", nullable = false, length = 50)
    public String getExternalKey() {
        return this.externalKey;
    }

    public void setExternalKey(String externalKey) {
        this.externalKey = externalKey;
    }

    @Column(name = "TYPE", nullable = false, length = 50)
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DTTM", nullable = false, length = 19)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DTTM", length = 19)
    public Date getUpdateDttm() {
        return this.updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }

}