package com.ripplehire.candidate.entities;

// Generated Jul 11, 2014 7:18:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientInterviewStatus generated by hbm2java
 */
@Entity
@Table(name = "client_service_request_log")
public class ClientServiceRequestLog implements java.io.Serializable {
    private Integer clientServiceRequestLogSeq;
    private String requestMsg;
    private String requestStatus;
    private String requestType;
    private char status;
    private int createdBy;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;

    public ClientServiceRequestLog(){}

    public ClientServiceRequestLog(String requestMsg, String requestStatus, String requestType,
           char status, int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
        this.requestMsg = requestMsg;
        this.requestStatus = requestStatus;
        this.requestType = requestType;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "CLIENT_SERVICE_REQUEST_LOG_SEQ", unique = true, nullable = false)
    public Integer getClientServiceRequestLogSeq() {
        return clientServiceRequestLogSeq;
    }

    public void setClientServiceRequestLogSeq(Integer clientServiceRequestLogSeq) {
        this.clientServiceRequestLogSeq = clientServiceRequestLogSeq;
    }

    @Column(name = "REQUEST_MSG", length = 500, nullable = false)
    public String getRequestMsg() {
        return requestMsg;
    }

    public void setRequestMsg(String requestMsg) {
        this.requestMsg = requestMsg;
    }

    @Column(name = "REQUEST_STATUS", length = 20, nullable = false)
    public String getRequestStatus() {
        return requestStatus;
    }

    public void setRequestStatus(String requestStatus) {
        this.requestStatus = requestStatus;
    }

    @Column(name = "REQUEST_TYPE", length = 20, nullable = false)
    public String getRequestType() {
        return requestType;
    }

    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_DTTM", nullable = false, length = 19)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_DTTM", length = 19)
    public Date getUpdateDttm() {
        return this.updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }
}