package com.ripplehire.candidate.entities;

// Generated Sep 1, 2014 7:18:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientInterviewStatus generated by hbm2java
 */
@Entity
@Table(name = "client_interview_status")
public class ClientInterviewStatus implements java.io.Serializable {

	private Integer clientInterviewStatusSeq;
	private InterviewStageMstr interviewStageMstr;
	private int companyMstrSeq;
	private String clientInterviewRoundCd;
	private String cleintInterviewSubstatus;
	private Integer jumpInterviewStageMstr;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<ClientInterviewStatusLang> clientInterviewStatusLangs = new HashSet<ClientInterviewStatusLang>(
			0);
	private Set<EmplRefrl> emplRefrls = new HashSet<EmplRefrl>(0);

	public ClientInterviewStatus() {
	}

	public ClientInterviewStatus(int companyMstrSeq, char status,
			int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public ClientInterviewStatus(InterviewStageMstr interviewStageMstr,
			int companyMstrSeq, String clientInterviewRoundCd,
			String cleintInterviewSubstatus, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm,
			Set<ClientInterviewStatusLang> clientInterviewStatusLangs,
			Set<EmplRefrl> emplRefrls) {
		this.interviewStageMstr = interviewStageMstr;
		this.companyMstrSeq = companyMstrSeq;
		this.clientInterviewRoundCd = clientInterviewRoundCd;
		this.cleintInterviewSubstatus = cleintInterviewSubstatus;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.clientInterviewStatusLangs = clientInterviewStatusLangs;
		this.emplRefrls = emplRefrls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CLIENT_INTERVIEW_STATUS_SEQ", unique = true, nullable = false)
	public Integer getClientInterviewStatusSeq() {
		return this.clientInterviewStatusSeq;
	}

	public void setClientInterviewStatusSeq(Integer clientInterviewStatusSeq) {
		this.clientInterviewStatusSeq = clientInterviewStatusSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INTERVIEW_STAGE_MSTR_SEQ")
	public InterviewStageMstr getInterviewStageMstr() {
		return this.interviewStageMstr;
	}

	public void setInterviewStageMstr(InterviewStageMstr interviewStageMstr) {
		this.interviewStageMstr = interviewStageMstr;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "CLIENT_INTERVIEW_ROUND_CD", length = 50)
	public String getClientInterviewRoundCd() {
		return this.clientInterviewRoundCd;
	}

	public void setClientInterviewRoundCd(String clientInterviewRoundCd) {
		this.clientInterviewRoundCd = clientInterviewRoundCd;
	}

	@Column(name = "CLEINT_INTERVIEW_SUBSTATUS", length = 50)
	public String getCleintInterviewSubstatus() {
		return this.cleintInterviewSubstatus;
	}

	public void setCleintInterviewSubstatus(String cleintInterviewSubstatus) {
		this.cleintInterviewSubstatus = cleintInterviewSubstatus;
	}

    @Column(name = "JUMP_INTERVIEW_STAGE_MSTR_SEQ")
	public Integer getJumpInterviewStageMstr() {
		return jumpInterviewStageMstr;
	}

	public void setJumpInterviewStageMstr(Integer jumpInterviewStageMstr) {
		this.jumpInterviewStageMstr = jumpInterviewStageMstr;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientInterviewStatus")
	public Set<ClientInterviewStatusLang> getClientInterviewStatusLangs() {
		return this.clientInterviewStatusLangs;
	}

	public void setClientInterviewStatusLangs(
			Set<ClientInterviewStatusLang> clientInterviewStatusLangs) {
		this.clientInterviewStatusLangs = clientInterviewStatusLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientInterviewStatus")
	public Set<EmplRefrl> getEmplRefrls() {
		return this.emplRefrls;
	}

	public void setEmplRefrls(Set<EmplRefrl> emplRefrls) {
		this.emplRefrls = emplRefrls;
	}

}
