package com.ripplehire.candidate.entities;

// Generated Jul 11, 2014 7:18:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientInterviewStatus generated by hbm2java
 */
@Entity
@Table(name = "coins_service_log")
public class CoinsServiceLog implements java.io.Serializable {
    private Integer coinsServiceLogSeq;
    private UserProfile userProfile;
    private EmplRefrl emplRefrl;
    private String serviceApiName;
    private String requestMsg;
    private String responseMsg;
    private String responseCd;
    private String requestStatus;
    private String requestType;
    private String transactionId;
    private Integer transactionAmount;
    private String transactionMsg;
    private Integer totalBalance;
    private char status;
    private int createdBy;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;

    public CoinsServiceLog(){}

    public CoinsServiceLog(UserProfile userProfile, EmplRefrl emplRefrl, String serviceApiName, String requestMsg, String responseMsg, String responseCd, String requestStatus,
                           String requestType, String transactionId, Integer transactionAmount, String transactionMsg, Integer totalBalance, char status, int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
        this.userProfile = userProfile;
        this.emplRefrl = emplRefrl;
        this.serviceApiName = serviceApiName;
        this.requestMsg = requestMsg;
        this.responseMsg = responseMsg;
        this.responseCd = responseCd;
        this.requestStatus = requestStatus;
        this.requestType = requestType;
        this.transactionId = transactionId;
        this.transactionAmount = transactionAmount;
        this.transactionMsg = transactionMsg;
        this.totalBalance = totalBalance;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "COINS_SERVICE_LOG_SEQ", unique = true, nullable = false)
    public Integer getCoinsServiceLogSeq() {
        return coinsServiceLogSeq;
    }

    public void setCoinsServiceLogSeq(Integer coinsServiceLogSeq) {
        this.coinsServiceLogSeq = coinsServiceLogSeq;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_PROFILE_SEQ", nullable = false)
    public UserProfile getUserProfile() {
        return userProfile;
    }

    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMPL_REFRL_SEQ", nullable = false)
    public EmplRefrl getEmplRefrl() {
        return emplRefrl;
    }

    public void setEmplRefrl(EmplRefrl emplRefrl) {
        this.emplRefrl = emplRefrl;
    }

    @Column(name = "SERVICE_API_NAME", length = 50)
    public String getServiceApiName() {
        return serviceApiName;
    }

    public void setServiceApiName(String serviceApiName) {
        this.serviceApiName = serviceApiName;
    }

    @Column(name = "REQUEST_MSG", length = 500)
    public String getRequestMsg() {
        return requestMsg;
    }

    public void setRequestMsg(String requestMsg) {
        this.requestMsg = requestMsg;
    }

    @Column(name = "RESPONSE_MSG", length = 500)
    public String getResponseMsg() {
        return responseMsg;
    }

    public void setResponseMsg(String responseMsg) {
        this.responseMsg = responseMsg;
    }

    @Column(name = "RESPONSE_CD", length = 20)
    public String getResponseCd() {
        return responseCd;
    }

    public void setResponseCd(String responseCd) {
        this.responseCd = responseCd;
    }

    @Column(name = "REQUEST_STATUS", length = 20, nullable = false)
    public String getRequestStatus() {
        return requestStatus;
    }

    public void setRequestStatus(String requestStatus) {
        this.requestStatus = requestStatus;
    }

    @Column(name = "REQUEST_TYPE", length = 20, nullable = false)
    public String getRequestType() {
        return requestType;
    }

    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    @Column(name = "TRANSACTION_ID", length = 200, nullable = false)
    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    @Column(name = "TRANSACTION_AMOUNT", length = 20)
    public Integer getTransactionAmount() {
        return transactionAmount;
    }

    public void setTransactionAmount(Integer transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    @Column(name = "TRANSACTION_MSG", length = 20)
    public String getTransactionMsg() {
        return transactionMsg;
    }

    public void setTransactionMsg(String transactionMsg) {
        this.transactionMsg = transactionMsg;
    }

    @Column(name = "TOTAL_BALANCE", length = 20)
    public Integer getTotalBalance() {
        return totalBalance;
    }

    public void setTotalBalance(Integer totalBalance) {
        this.totalBalance = totalBalance;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_DTTM", nullable = false, length = 19)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_DTTM", length = 19)
    public Date getUpdateDttm() {
        return this.updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }
}