package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyMstrLang generated by hbm2java
 */
@Entity
@Table(name = "company_mstr_lang")
public class CompanyMstrLang implements java.io.Serializable {

	private Integer companyMstrLangSeq;
	private LangMstr langMstr;
	private int companyMstrSeq;
	private String companyName;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public CompanyMstrLang() {
	}

	public CompanyMstrLang(LangMstr langMstr, int companyMstrSeq,
			String companyName, char status, int createdBy, Date createDttm) {
		this.langMstr = langMstr;
		this.companyMstrSeq = companyMstrSeq;
		this.companyName = companyName;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CompanyMstrLang(LangMstr langMstr, int companyMstrSeq,
			String companyName, char status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm) {
		this.langMstr = langMstr;
		this.companyMstrSeq = companyMstrSeq;
		this.companyName = companyName;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "COMPANY_MSTR_LANG_SEQ", unique = true, nullable = false)
	public Integer getCompanyMstrLangSeq() {
		return this.companyMstrLangSeq;
	}

	public void setCompanyMstrLangSeq(Integer companyMstrLangSeq) {
		this.companyMstrLangSeq = companyMstrLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "COMPANY_NAME", nullable = false, length = 400)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
