package com.ripplehire.candidate.entities;
// Generated Jul 8, 2016 5:17:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyHelpConfig generated by hbm2java
 */
@Entity
@Table(name = "company_help_config")
public class CompanyHelpConfig implements java.io.Serializable {

	private Integer companyHelpConfigSeq;
	private int companyMstrSeq;
	private String helpSectionFor;
	private String sectionType;
	private String sectionHeader;
	private String question;
	private String answer;
	private int priority;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public CompanyHelpConfig() {
	}

	public CompanyHelpConfig(int companyMstrSeq, String helpSectionFor, String sectionType, String question,
			String answer, int priority, char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.helpSectionFor = helpSectionFor;
		this.sectionType = sectionType;
		this.question = question;
		this.answer = answer;
		this.priority = priority;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CompanyHelpConfig(int companyMstrSeq, String helpSectionFor, String sectionType, String question,
			String answer, int priority, char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.helpSectionFor = helpSectionFor;
		this.sectionType = sectionType;
		this.question = question;
		this.answer = answer;
		this.priority = priority;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "COMPANY_HELP_CONFIG_SEQ", unique = true, nullable = false)
	public Integer getCompanyHelpConfigSeq() {
		return this.companyHelpConfigSeq;
	}

	public void setCompanyHelpConfigSeq(Integer companyHelpConfigSeq) {
		this.companyHelpConfigSeq = companyHelpConfigSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "HELP_SECTION_FOR", nullable = false, length = 50)
	public String getHelpSectionFor() {
		return this.helpSectionFor;
	}

	public void setHelpSectionFor(String helpSectionFor) {
		this.helpSectionFor = helpSectionFor;
	}

	@Column(name = "SECTION_TYPE", nullable = false, length = 50)
	public String getSectionType() {
		return this.sectionType;
	}

	public void setSectionType(String sectionType) {
		this.sectionType = sectionType;
	}

	@Column(name = "SECTION_HEADER", nullable = false, length = 100)
	public String getSectionHeader() {
		return sectionHeader;
	}

	public void setSectionHeader(String sectionHeader) {
		this.sectionHeader = sectionHeader;
	}

	@Column(name = "QUESTION", nullable = false, length = 1000)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "ANSWER", nullable = false)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "PRIORITY", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
