package com.ripplehire.candidate.entities;

// Generated Jul 14, 2015 6:30:24 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyFacebookConfig generated by hbm2java
 */
@Entity
@Table(name = "company_facebook_config")
public class CompanyFacebookConfig implements java.io.Serializable {

	private Integer companyFacebookConfigSeq;
	private Integer companyMstrSeq;
	private String companyPageId;
	private char status;
	private int createdBy;
	private Date createdDttm;
	private Integer updatedBy;
	private Date updatedDttm;

	public CompanyFacebookConfig() {
	}

	public CompanyFacebookConfig(String companyPageId, int createdBy,
			Date createdDttm) {
		this.companyPageId = companyPageId;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public CompanyFacebookConfig(Integer companyMstrSeq, String companyPageId, char status,
			int createdBy, Date createdDttm, Integer updatedBy, Date updatedDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.companyPageId = companyPageId;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "COMPANY_FACEBOOK_CONFIG_SEQ", unique = true, nullable = false)
	public Integer getCompanyFacebookConfigSeq() {
		return this.companyFacebookConfigSeq;
	}

	public void setCompanyFacebookConfigSeq(Integer companyFacebookConfigSeq) {
		this.companyFacebookConfigSeq = companyFacebookConfigSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ")
	public Integer getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(Integer companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "COMPANY_PAGE_ID", nullable = false, length = 500)
	public String getCompanyPageId() {
		return this.companyPageId;
	}

	public void setCompanyPageId(String companyPageId) {
		this.companyPageId = companyPageId;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

}
