package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContestReward generated by hbm2java
 */
@Entity
@Table(name = "contest_reward")
public class ContestReward implements java.io.Serializable {

	private Integer contestRewardSeq;
	private Reward reward;
	private Contest contest;
	private int companyMstrSeq;
	private int contestWinPosition;
	private String rewardCriteria;
	private Character status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public ContestReward() {
	}

	public ContestReward(Reward reward, Contest contest, int companyMstrSeq,
			int contestWinPosition, String rewardCriteria, int createdBy,
			Date createDttm) {
		this.reward = reward;
		this.contest = contest;
		this.companyMstrSeq = companyMstrSeq;
		this.contestWinPosition = contestWinPosition;
		this.rewardCriteria = rewardCriteria;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public ContestReward(Reward reward, Contest contest, int companyMstrSeq,
			int contestWinPosition, String rewardCriteria, Character status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
		this.reward = reward;
		this.contest = contest;
		this.companyMstrSeq = companyMstrSeq;
		this.contestWinPosition = contestWinPosition;
		this.rewardCriteria = rewardCriteria;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CONTEST_REWARD_SEQ", unique = true, nullable = false)
	public Integer getContestRewardSeq() {
		return this.contestRewardSeq;
	}

	public void setContestRewardSeq(Integer contestRewardSeq) {
		this.contestRewardSeq = contestRewardSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REWARD_SEQ", nullable = false)
	public Reward getReward() {
		return this.reward;
	}

	public void setReward(Reward reward) {
		this.reward = reward;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONTEST_SEQ", nullable = false)
	public Contest getContest() {
		return this.contest;
	}

	public void setContest(Contest contest) {
		this.contest = contest;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "CONTEST_WIN_POSITION", nullable = false)
	public int getContestWinPosition() {
		return this.contestWinPosition;
	}

	public void setContestWinPosition(int contestWinPosition) {
		this.contestWinPosition = contestWinPosition;
	}

	@Column(name = "REWARD_CRITERIA", nullable = false, length = 50)
	public String getRewardCriteria() {
		return this.rewardCriteria;
	}

	public void setRewardCriteria(String rewardCriteria) {
		this.rewardCriteria = rewardCriteria;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
