package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContestWinner generated by hbm2java
 */
@Entity
@Table(name = "contest_winner")
public class ContestWinner implements java.io.Serializable {

	private Integer contestWinnerSeq;
	private UserProfile userProfile;
	private Contest contest;
	private int companyMstrSeq;
	private String rewardCriteriaCd;
	private int contestWinPosition;
	private int activityCount;
	private String deleteComments;
	private Character status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public ContestWinner() {
	}

	public ContestWinner(UserProfile userProfile, Contest contest,
			int companyMstrSeq, String rewardCriteriaCd,
			int contestWinPosition, int activityCount, int createdBy,
			Date createDttm) {
		this.userProfile = userProfile;
		this.contest = contest;
		this.companyMstrSeq = companyMstrSeq;
		this.rewardCriteriaCd = rewardCriteriaCd;
		this.contestWinPosition = contestWinPosition;
		this.activityCount = activityCount;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public ContestWinner(UserProfile userProfile, Contest contest,
			int companyMstrSeq, String rewardCriteriaCd,
			int contestWinPosition, int activityCount, String deleteComments,
			Character status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm) {
		this.userProfile = userProfile;
		this.contest = contest;
		this.companyMstrSeq = companyMstrSeq;
		this.rewardCriteriaCd = rewardCriteriaCd;
		this.contestWinPosition = contestWinPosition;
		this.activityCount = activityCount;
		this.deleteComments = deleteComments;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CONTEST_WINNER_SEQ", unique = true, nullable = false)
	public Integer getContestWinnerSeq() {
		return this.contestWinnerSeq;
	}

	public void setContestWinnerSeq(Integer contestWinnerSeq) {
		this.contestWinnerSeq = contestWinnerSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PROFILE_SEQ", nullable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONTEST_SEQ", nullable = false)
	public Contest getContest() {
		return this.contest;
	}

	public void setContest(Contest contest) {
		this.contest = contest;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "REWARD_CRITERIA_CD", nullable = false, length = 50)
	public String getRewardCriteriaCd() {
		return this.rewardCriteriaCd;
	}

	public void setRewardCriteriaCd(String rewardCriteriaCd) {
		this.rewardCriteriaCd = rewardCriteriaCd;
	}

	@Column(name = "CONTEST_WIN_POSITION", nullable = false)
	public int getContestWinPosition() {
		return this.contestWinPosition;
	}

	public void setContestWinPosition(int contestWinPosition) {
		this.contestWinPosition = contestWinPosition;
	}

	@Column(name = "ACTIVITY_COUNT", nullable = false)
	public int getActivityCount() {
		return this.activityCount;
	}

	public void setActivityCount(int activityCount) {
		this.activityCount = activityCount;
	}

	@Column(name = "DELETE_COMMENTS", length = 1000)
	public String getDeleteComments() {
		return this.deleteComments;
	}

	public void setDeleteComments(String deleteComments) {
		this.deleteComments = deleteComments;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
