package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country")
public class Country implements java.io.Serializable {

	private Integer countrySeq;
	private String countryName;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Set<State> states = new HashSet<State>(0);
	private Set<CountryLang> countryLangs = new HashSet<CountryLang>(0);
	private Set<City> cities = new HashSet<City>(0);

	public Country() {
	}

	public Country(String countryName, char status, int createdBy,
			Date createDttm) {
		this.countryName = countryName;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public Country(String countryName, char status, int createdBy,
			Date createDttm, Set<State> states, Set<CountryLang> countryLangs,
			Set<City> cities) {
		this.countryName = countryName;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.states = states;
		this.countryLangs = countryLangs;
		this.cities = cities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "COUNTRY_SEQ", unique = true, nullable = false)
	public Integer getCountrySeq() {
		return this.countrySeq;
	}

	public void setCountrySeq(Integer countrySeq) {
		this.countrySeq = countrySeq;
	}

	@Column(name = "COUNTRY_NAME", nullable = false, length = 60)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<State> getStates() {
		return this.states;
	}

	public void setStates(Set<State> states) {
		this.states = states;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<CountryLang> getCountryLangs() {
		return this.countryLangs;
	}

	public void setCountryLangs(Set<CountryLang> countryLangs) {
		this.countryLangs = countryLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
