package com.ripplehire.candidate.entities;

// Generated Aug 12, 2014 2:57:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CountryMstrLang generated by hbm2java
 */
@Entity
@Table(name = "country_mstr_lang")
public class CountryMstrLang implements java.io.Serializable {

	private Integer countryMstrLangSeq;
	private LangMstr langMstr;
	private CountryMstr countryMstr;
	private String countryDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public CountryMstrLang() {
	}

	public CountryMstrLang(LangMstr langMstr, CountryMstr countryMstr,
			String countryDesc, char status, int createdBy, Date createDttm) {
		this.langMstr = langMstr;
		this.countryMstr = countryMstr;
		this.countryDesc = countryDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CountryMstrLang(LangMstr langMstr, CountryMstr countryMstr,
			String countryDesc, char status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm) {
		this.langMstr = langMstr;
		this.countryMstr = countryMstr;
		this.countryDesc = countryDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "COUNTRY_MSTR_LANG_SEQ", unique = true, nullable = false)
	public Integer getCountryMstrLangSeq() {
		return this.countryMstrLangSeq;
	}

	public void setCountryMstrLangSeq(Integer countryMstrLangSeq) {
		this.countryMstrLangSeq = countryMstrLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_MSTR_SEQ", nullable = false)
	public CountryMstr getCountryMstr() {
		return this.countryMstr;
	}

	public void setCountryMstr(CountryMstr countryMstr) {
		this.countryMstr = countryMstr;
	}

	@Column(name = "COUNTRY_DESC", nullable = false, length = 100)
	public String getCountryDesc() {
		return this.countryDesc;
	}

	public void setCountryDesc(String countryDesc) {
		this.countryDesc = countryDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
