package com.ripplehire.candidate.entities;

// Generated Aug 12, 2014 2:57:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CountryMstr generated by hbm2java
 */
@Entity
@Table(name = "country_mstr")
public class CountryMstr implements java.io.Serializable {

	private Integer countryMstrSeq;
	private int companyMstrSeq;
	private int countryClientKey;
	private String countryDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<CandidateResumedetails> candidateResumedetailses = new HashSet<CandidateResumedetails>(
			0);
	private Set<CountryMstrLang> countryMstrLangs = new HashSet<CountryMstrLang>(
			0);

	public CountryMstr() {
	}

	public CountryMstr(int companyMstrSeq, int countryClientKey,
			String countryDesc, char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.countryClientKey = countryClientKey;
		this.countryDesc = countryDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CountryMstr(int companyMstrSeq, int countryClientKey,
			String countryDesc, char status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm,
			Set<CandidateResumedetails> candidateResumedetailses,
			Set<CountryMstrLang> countryMstrLangs) {
		this.companyMstrSeq = companyMstrSeq;
		this.countryClientKey = countryClientKey;
		this.countryDesc = countryDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.candidateResumedetailses = candidateResumedetailses;
		this.countryMstrLangs = countryMstrLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "COUNTRY_MSTR_SEQ", unique = true, nullable = false)
	public Integer getCountryMstrSeq() {
		return this.countryMstrSeq;
	}

	public void setCountryMstrSeq(Integer countryMstrSeq) {
		this.countryMstrSeq = countryMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "COUNTRY_CLIENT_KEY", nullable = false)
	public int getCountryClientKey() {
		return this.countryClientKey;
	}

	public void setCountryClientKey(int countryClientKey) {
		this.countryClientKey = countryClientKey;
	}

	@Column(name = "COUNTRY_DESC", nullable = false, length = 100)
	public String getCountryDesc() {
		return this.countryDesc;
	}

	public void setCountryDesc(String countryDesc) {
		this.countryDesc = countryDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryMstr")
	public Set<CandidateResumedetails> getCandidateResumedetailses() {
		return this.candidateResumedetailses;
	}

	public void setCandidateResumedetailses(
			Set<CandidateResumedetails> candidateResumedetailses) {
		this.candidateResumedetailses = candidateResumedetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryMstr")
	public Set<CountryMstrLang> getCountryMstrLangs() {
		return this.countryMstrLangs;
	}

	public void setCountryMstrLangs(Set<CountryMstrLang> countryMstrLangs) {
		this.countryMstrLangs = countryMstrLangs;
	}

}
