package com.ripplehire.candidate.entities;

// Generated May 10, 2014 6:09:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CurrencyMstr generated by hbm2java
 */
@Entity
@Table(name = "currency_mstr")
public class CurrencyMstr implements java.io.Serializable {

	private Integer currencyMstrSeq;
	private String currencyCd;
	private String currencySymbol;
	private double rupeeValue;
	private String currencyDesc;
	private Character status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<JobDetail> jobDetails = new HashSet<JobDetail>(0);
	private Set<CandidateResumedetails> candidateResumedetailses = new HashSet<CandidateResumedetails>(
			0);
	private Set<CompanyMstr> companyMstrs = new HashSet<CompanyMstr>(0);

	public CurrencyMstr() {
	}

	public CurrencyMstr(String currencyCd, String currencySymbol,
			double rupeeValue, String currencyDesc, int createdBy,
			Date createDttm) {
		this.currencyCd = currencyCd;
		this.currencySymbol = currencySymbol;
		this.rupeeValue = rupeeValue;
		this.currencyDesc = currencyDesc;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CurrencyMstr(String currencyCd, String currencySymbol, double rupeeValue, String currencyDesc,
						Character status, int createdBy, Date createDttm, Integer updatedBy, Date updateDttm,
						Set<JobDetail> jobDetails, Set<CompanyMstr> companyMstrs,
						Set<CandidateResumedetails> candidateResumedetailses) {
		this.currencyCd = currencyCd;
		this.currencySymbol = currencySymbol;
		this.rupeeValue = rupeeValue;
		this.currencyDesc = currencyDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.jobDetails = jobDetails;
		this.companyMstrs = companyMstrs;
		this.candidateResumedetailses = candidateResumedetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CURRENCY_MSTR_SEQ", unique = true, nullable = false)
	public Integer getCurrencyMstrSeq() {
		return this.currencyMstrSeq;
	}

	public void setCurrencyMstrSeq(Integer currencyMstrSeq) {
		this.currencyMstrSeq = currencyMstrSeq;
	}

	@Column(name = "CURRENCY_CD", nullable = false, length = 50)
	public String getCurrencyCd() {
		return this.currencyCd;
	}

	public void setCurrencyCd(String currencyCd) {
		this.currencyCd = currencyCd;
	}

	@Column(name = "CURRENCY_SYMBOL", nullable = false, length = 50)
	public String getCurrencySymbol() {
		return this.currencySymbol;
	}

	public void setCurrencySymbol(String currencySymbol) {
		this.currencySymbol = currencySymbol;
	}

	@Column(name = "RUPEE_VALUE", nullable = false, precision = 22, scale = 0)
	public double getRupeeValue() {
		return this.rupeeValue;
	}

	public void setRupeeValue(double rupeeValue) {
		this.rupeeValue = rupeeValue;
	}

	@Column(name = "CURRENCY_DESC", nullable = false, length = 100)
	public String getCurrencyDesc() {
		return this.currencyDesc;
	}

	public void setCurrencyDesc(String currencyDesc) {
		this.currencyDesc = currencyDesc;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currencyMstr")
	public Set<CandidateResumedetails> getCandidateResumedetailses() {
		return this.candidateResumedetailses;
	}

	public void setCandidateResumedetailses(
			Set<CandidateResumedetails> candidateResumedetailses) {
		this.candidateResumedetailses = candidateResumedetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currencyMstr")
	public Set<CompanyMstr> getCompanyMstrs() {
		return this.companyMstrs;
	}

	public void setCompanyMstrs(Set<CompanyMstr> companyMstrs) {
		this.companyMstrs = companyMstrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currencyMstr")
	public Set<JobDetail> getJobDetails() {
		return this.jobDetails;
	}

	public void setJobDetails(Set<JobDetail> jobDetails) {
		this.jobDetails = jobDetails;
	}
}
