package com.ripplehire.candidate.entities;

// Generated Aug 12, 2014 2:57:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CurrentEmployerMstr generated by hbm2java
 */
@Entity
@Table(name = "current_employer_mstr")
public class CurrentEmployerMstr implements java.io.Serializable {

	private Integer currentEmployerMstrSeq;
	private int companyMstrSeq;
	private int currentEmployerClientKey;
	private String currentEmployerDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<CandidateResumedetails> candidateResumedetailses = new HashSet<CandidateResumedetails>(
			0);
	private Set<CurrentEmployerMstrLang> currentEmployerMstrLangs = new HashSet<CurrentEmployerMstrLang>(
			0);

	public CurrentEmployerMstr() {
	}

	public CurrentEmployerMstr(int companyMstrSeq,
			int currentEmployerClientKey, String currentEmployerDesc,
			char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.currentEmployerClientKey = currentEmployerClientKey;
		this.currentEmployerDesc = currentEmployerDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CurrentEmployerMstr(int companyMstrSeq,
			int currentEmployerClientKey, String currentEmployerDesc,
			char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm,
			Set<CandidateResumedetails> candidateResumedetailses,
			Set<CurrentEmployerMstrLang> currentEmployerMstrLangs) {
		this.companyMstrSeq = companyMstrSeq;
		this.currentEmployerClientKey = currentEmployerClientKey;
		this.currentEmployerDesc = currentEmployerDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.candidateResumedetailses = candidateResumedetailses;
		this.currentEmployerMstrLangs = currentEmployerMstrLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CURRENT_EMPLOYER_MSTR_SEQ", unique = true, nullable = false)
	public Integer getCurrentEmployerMstrSeq() {
		return this.currentEmployerMstrSeq;
	}

	public void setCurrentEmployerMstrSeq(Integer currentEmployerMstrSeq) {
		this.currentEmployerMstrSeq = currentEmployerMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "CURRENT_EMPLOYER_CLIENT_KEY", nullable = false)
	public int getCurrentEmployerClientKey() {
		return this.currentEmployerClientKey;
	}

	public void setCurrentEmployerClientKey(int currentEmployerClientKey) {
		this.currentEmployerClientKey = currentEmployerClientKey;
	}

	@Column(name = "CURRENT_EMPLOYER_DESC", nullable = false, length = 100)
	public String getCurrentEmployerDesc() {
		return this.currentEmployerDesc;
	}

	public void setCurrentEmployerDesc(String currentEmployerDesc) {
		this.currentEmployerDesc = currentEmployerDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currentEmployerMstr")
	public Set<CandidateResumedetails> getCandidateResumedetailses() {
		return this.candidateResumedetailses;
	}

	public void setCandidateResumedetailses(
			Set<CandidateResumedetails> candidateResumedetailses) {
		this.candidateResumedetailses = candidateResumedetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "currentEmployerMstr")
	public Set<CurrentEmployerMstrLang> getCurrentEmployerMstrLangs() {
		return this.currentEmployerMstrLangs;
	}

	public void setCurrentEmployerMstrLangs(
			Set<CurrentEmployerMstrLang> currentEmployerMstrLangs) {
		this.currentEmployerMstrLangs = currentEmployerMstrLangs;
	}

}
