package com.ripplehire.candidate.entities;

// Generated Aug 12, 2014 2:57:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CurrentLocationMstrLang generated by hbm2java
 */
@Entity
@Table(name = "current_location_mstr_lang")
public class CurrentLocationMstrLang implements java.io.Serializable {

	private Integer currentLocationMstrLangSeq;
	private CurrentLocationMstr currentLocationMstr;
	private LangMstr langMstr;
	private String currentLocationDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public CurrentLocationMstrLang() {
	}

	public CurrentLocationMstrLang(CurrentLocationMstr currentLocationMstr,
			LangMstr langMstr, String currentLocationDesc, char status,
			int createdBy, Date createDttm) {
		this.currentLocationMstr = currentLocationMstr;
		this.langMstr = langMstr;
		this.currentLocationDesc = currentLocationDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public CurrentLocationMstrLang(CurrentLocationMstr currentLocationMstr,
			LangMstr langMstr, String currentLocationDesc, char status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
		this.currentLocationMstr = currentLocationMstr;
		this.langMstr = langMstr;
		this.currentLocationDesc = currentLocationDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CURRENT_LOCATION_MSTR_LANG_SEQ", unique = true, nullable = false)
	public Integer getCurrentLocationMstrLangSeq() {
		return this.currentLocationMstrLangSeq;
	}

	public void setCurrentLocationMstrLangSeq(Integer currentLocationMstrLangSeq) {
		this.currentLocationMstrLangSeq = currentLocationMstrLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENT_LOCATION_MSTR_SEQ", nullable = false)
	public CurrentLocationMstr getCurrentLocationMstr() {
		return this.currentLocationMstr;
	}

	public void setCurrentLocationMstr(CurrentLocationMstr currentLocationMstr) {
		this.currentLocationMstr = currentLocationMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@Column(name = "CURRENT_LOCATION_DESC", nullable = false, length = 100)
	public String getCurrentLocationDesc() {
		return this.currentLocationDesc;
	}

	public void setCurrentLocationDesc(String currentLocationDesc) {
		this.currentLocationDesc = currentLocationDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
