package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmailTemplateConfigLang generated by hbm2java
 */
@Entity
@Table(name = "email_template_config_lang")
public class EmailTemplateConfigLang implements java.io.Serializable {

	private Integer emailTemplateConfigLangSeq;
	private LangMstr langMstr;
	private EmailTemplateConfig emailTemplateConfig;
	private String emailSubject;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public EmailTemplateConfigLang() {
	}

	public EmailTemplateConfigLang(LangMstr langMstr,
			EmailTemplateConfig emailTemplateConfig, char status,
			int createdBy, Date createDttm) {
		this.langMstr = langMstr;
		this.emailTemplateConfig = emailTemplateConfig;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public EmailTemplateConfigLang(LangMstr langMstr,
			EmailTemplateConfig emailTemplateConfig, String emailSubject,
			char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm) {
		this.langMstr = langMstr;
		this.emailTemplateConfig = emailTemplateConfig;
		this.emailSubject = emailSubject;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EMAIL_TEMPLATE_CONFIG_LANG_SEQ", unique = true, nullable = false)
	public Integer getEmailTemplateConfigLangSeq() {
		return this.emailTemplateConfigLangSeq;
	}

	public void setEmailTemplateConfigLangSeq(Integer emailTemplateConfigLangSeq) {
		this.emailTemplateConfigLangSeq = emailTemplateConfigLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMAIL_TEMPLATE_CONFIG_SEQ", nullable = false)
	public EmailTemplateConfig getEmailTemplateConfig() {
		return this.emailTemplateConfig;
	}

	public void setEmailTemplateConfig(EmailTemplateConfig emailTemplateConfig) {
		this.emailTemplateConfig = emailTemplateConfig;
	}

	@Column(name = "EMAIL_SUBJECT", length = 400)
	public String getEmailSubject() {
		return this.emailSubject;
	}

	public void setEmailSubject(String emailSubject) {
		this.emailSubject = emailSubject;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
