package com.ripplehire.candidate.entities;

// Generated Jan 7, 2015 11:50:00 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpCandConv generated by hbm2java
 */
@Entity
@Table(name = "emp_cand_conv")
public class EmpCandConv implements java.io.Serializable {

	private Integer empCandConvSeq;
	private EmplRefrl emplRefrl;
	private String sender;
	private String message;
	private char status;
	private String refrlSatusCode;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public EmpCandConv() {
	}

	public EmpCandConv(EmplRefrl emplRefrl, String sender, char status,
			int createdBy, Date createDttm) {
		this.emplRefrl = emplRefrl;
		this.sender = sender;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public EmpCandConv(EmplRefrl emplRefrl, String sender, String message,
			char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm) {
		this.emplRefrl = emplRefrl;
		this.sender = sender;
		this.message = message;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EMP_CAND_CONV_SEQ", unique = true, nullable = false)
	public Integer getEmpCandConvSeq() {
		return this.empCandConvSeq;
	}

	public void setEmpCandConvSeq(Integer empCandConvSeq) {
		this.empCandConvSeq = empCandConvSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_REFRL_SEQ", nullable = false)
	public EmplRefrl getEmplRefrl() {
		return this.emplRefrl;
	}

	public void setEmplRefrl(EmplRefrl emplRefrl) {
		this.emplRefrl = emplRefrl;
	}

	@Column(name = "SENDER", nullable = false, length = 50)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	@Column(name = "MESSAGE", nullable = false, length = 400)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}


	@Column(name = "REFERL_STATUS_CODE", nullable = false, length = 50)
	public String getRefrlSatusCode() {
		return refrlSatusCode;
	}

	public void setRefrlSatusCode(String refrlSatusCode) {
		this.refrlSatusCode = refrlSatusCode;
	}


	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
