package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmplLevel generated by hbm2java
 */
@Entity
@Table(name = "empl_level")
public class EmplLevel implements java.io.Serializable {

	private Integer emplLevelSeq;
	private UserProfile userProfile;
	private int companyMstrSeq;
	private int completedLevel;
	private int reputationPoints;
	private String empNotification;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public EmplLevel() {
	}

	public EmplLevel(UserProfile userProfile, int companyMstrSeq,
			int completedLevel, int reputationPoints, char status,
			int createdBy, Date createDttm) {
		this.userProfile = userProfile;
		this.companyMstrSeq = companyMstrSeq;
		this.completedLevel = completedLevel;
		this.reputationPoints = reputationPoints;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public EmplLevel(UserProfile userProfile, int companyMstrSeq,
			int completedLevel, int reputationPoints, String empNotification,
			char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm) {
		this.userProfile = userProfile;
		this.companyMstrSeq = companyMstrSeq;
		this.completedLevel = completedLevel;
		this.reputationPoints = reputationPoints;
		this.empNotification = empNotification;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EMPL_LEVEL_SEQ", unique = true, nullable = false)
	public Integer getEmplLevelSeq() {
		return this.emplLevelSeq;
	}

	public void setEmplLevelSeq(Integer emplLevelSeq) {
		this.emplLevelSeq = emplLevelSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PROFILE_SEQ", nullable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "COMPLETED_LEVEL", nullable = false)
	public int getCompletedLevel() {
		return this.completedLevel;
	}

	public void setCompletedLevel(int completedLevel) {
		this.completedLevel = completedLevel;
	}

	@Column(name = "REPUTATION_POINTS", nullable = false)
	public int getReputationPoints() {
		return this.reputationPoints;
	}

	public void setReputationPoints(int reputationPoints) {
		this.reputationPoints = reputationPoints;
	}

	@Column(name = "EMP_NOTIFICATION", length = 1)
	public String getEmpNotification() {
		return this.empNotification;
	}

	public void setEmpNotification(String empNotification) {
		this.empNotification = empNotification;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
