package com.ripplehire.candidate.entities;
// Generated Feb 10, 2016 4:56:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeFormFields generated by hbm2java
 */
@Entity
@Table(name = "employee_form_fields")
public class EmployeeFormFields implements java.io.Serializable {

	private Integer employeeFormFieldSeq;
	private int companyMstrSeq;
	private String fieldLabel;
	private String fieldSubLabel;
	private String fieldName;
	private String fieldPlaceholder;
	private String fieldType;
    private String formType;
	private Character fieldRequired;
	private Integer fieldMaxLength;
	private String fieldGroup;
	private String fieldSubGroup;
	private String fieldClass;
	private Integer priority;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public EmployeeFormFields() {
	}

	public EmployeeFormFields(int companyMstrSeq, char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public EmployeeFormFields(int companyMstrSeq, String fieldLabel, String fieldSubLabel, String fieldName,
			String fieldPlaceholder, String fieldType, Character fieldRequired, Integer fieldMaxLength,
			String fieldGroup, String fieldSubGroup, String fieldClass, Integer priority, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.fieldLabel = fieldLabel;
		this.fieldSubLabel = fieldSubLabel;
		this.fieldName = fieldName;
		this.fieldPlaceholder = fieldPlaceholder;
		this.fieldType = fieldType;
		this.fieldRequired = fieldRequired;
		this.fieldMaxLength = fieldMaxLength;
		this.fieldGroup = fieldGroup;
		this.fieldSubGroup = fieldSubGroup;
		this.fieldClass = fieldClass;
		this.priority = priority;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_FORM_FIELD_SEQ", unique = true, nullable = false)
	public Integer getEmployeeFormFieldSeq() {
		return this.employeeFormFieldSeq;
	}

	public void setEmployeeFormFieldSeq(Integer employeeFormFieldSeq) {
		this.employeeFormFieldSeq = employeeFormFieldSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}


	@Column(name = "FIELD_LABEL", length = 100)
	public String getFieldLabel() {
		return this.fieldLabel;
	}

	public void setFieldLabel(String fieldLabel) {
		this.fieldLabel = fieldLabel;
	}

	@Column(name = "FIELD_SUB_LABEL", length = 100)
	public String getFieldSubLabel() {
		return this.fieldSubLabel;
	}

	public void setFieldSubLabel(String fieldSubLabel) {
		this.fieldSubLabel = fieldSubLabel;
	}

	@Column(name = "FIELD_NAME", length = 100)
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "FIELD_PLACEHOLDER", length = 100)
	public String getFieldPlaceholder() {
		return this.fieldPlaceholder;
	}

	public void setFieldPlaceholder(String fieldPlaceholder) {
		this.fieldPlaceholder = fieldPlaceholder;
	}

	@Column(name = "FIELD_TYPE", length = 100)
	public String getFieldType() {
		return this.fieldType;
	}

	public void setFieldType(String fieldType) {
		this.fieldType = fieldType;
	}

    @Column(name = "FORM_TYPE", length = 100)
    public String getFormType() {
        return formType;
    }

    public void setFormType(String formType) {
        this.formType = formType;
    }

    @Column(name = "FIELD_REQUIRED", length = 1)
	public Character getFieldRequired() {
		return this.fieldRequired;
	}

	public void setFieldRequired(Character fieldRequired) {
		this.fieldRequired = fieldRequired;
	}

	@Column(name = "FIELD_MAX_LENGTH")
	public Integer getFieldMaxLength() {
		return this.fieldMaxLength;
	}

	public void setFieldMaxLength(Integer fieldMaxLength) {
		this.fieldMaxLength = fieldMaxLength;
	}

	@Column(name = "FIELD_GROUP", length = 50)
	public String getFieldGroup() {
		return this.fieldGroup;
	}

	public void setFieldGroup(String fieldGroup) {
		this.fieldGroup = fieldGroup;
	}

	@Column(name = "FIELD_SUB_GROUP", length = 50)
	public String getFieldSubGroup() {
		return this.fieldSubGroup;
	}

	public void setFieldSubGroup(String fieldSubGroup) {
		this.fieldSubGroup = fieldSubGroup;
	}

	@Column(name = "FIELD_CLASS", length = 100)
	public String getFieldClass() {
		return this.fieldClass;
	}

	public void setFieldClass(String fieldClass) {
		this.fieldClass = fieldClass;
	}

	@Column(name = "PRIORITY")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
