package com.ripplehire.candidate.entities;

// Generated Jun 11, 2015 7:19:30 PM by Hibernate Tools 4.0.0

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * EmplRefrl generated by hbm2java
 */
@Entity
@Table(name = "empl_refrl")
public class EmplRefrl implements java.io.Serializable {

    private Integer emplRefrlSeq;
    private Candidate candidate;
    private InterviewStageMstr interviewStageMstr;
    private RefrlChannelMstr refrlChannelMstr;
    private RelationshipMstr relationshipMstr;
    private CandidateResumedetails candidateResumedetails;
    private Job job;
    private ClientInterviewStatus clientInterviewStatus;
    private RefrlStatusMstr refrlStatusMstr;
    private Campaign campaign;
    private UserProfile userProfile;
    private UserProfile submittedBy;
    private Contest contest;
    private int companyMstrSeq;
    private String ripplehireSeq;
    private String clientCandidateId;
    private String refrlModeCd;
    private String shiftStatus;
    private String refrlToken;
    private Integer refrlRating;
    private String refrlComments;
    private int candidateClicks;
    private String socialMediaId;
    private String isLegacy;
    private String referReason;
    private String referTime;
    private String isReferFresher;
    private String isReferChannelFacebook;
    private String allowRefererName;
    private Integer parentEmplRefrlSeq;
    private String countThrottle;
    private char status;
    private Date clientUpdateDttm;
    private int createdBy;
    private Date applyDate;
    private Date walkinDate;
    private Date joiningDate;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;
    private DuplicateCandidateLog duplicateCandidateLog;
    private String vendorId;
    private int lifeCycleState;
    private Character allowRedemption = 'N';
    private InterviewDetails interviewDetails;
    private Set<InterviewSchedule> interviewSchedules = new HashSet<InterviewSchedule>(0);
    private Integer prevUserProfileSeq;
    private Integer prevRefrlChannelMstrSeq;
    private Set<EmplReward> emplRewards = new HashSet<EmplReward>(0);
    private Set<CandidateLog> candidateLogs = new HashSet<CandidateLog>(0);
    private Set<EmpCandConv> empCandConvs = new HashSet<EmpCandConv>(0);
    private Set<EmplActivity> emplActivitys = new HashSet<EmplActivity>(0);
    private Set<InterviewDetails> interviewDetailses = new HashSet<InterviewDetails>(0);
    private Set<CandidateUploadResumeDetails> candidateUploadResumeDetailses = new HashSet<CandidateUploadResumeDetails>(0);

    public EmplRefrl() {

    }




    public EmplRefrl(RefrlChannelMstr refrlChannelMstr,
                     RefrlStatusMstr refrlStatusMstr, UserProfile userProfile, UserProfile submittedBy,
                     int companyMstrSeq, String shiftStatus, int candidateClicks,
                     char status, int createdBy, Date createDttm) {
        this.refrlChannelMstr = refrlChannelMstr;
        this.refrlStatusMstr = refrlStatusMstr;
        this.userProfile = userProfile;
        this.submittedBy = submittedBy;
        this.companyMstrSeq = companyMstrSeq;
        this.shiftStatus = shiftStatus;
        this.candidateClicks = candidateClicks;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
    }

    public EmplRefrl(Candidate candidate,
                     InterviewStageMstr interviewStageMstr,
                     RefrlChannelMstr refrlChannelMstr,
                     RelationshipMstr relationshipMstr,
                     CandidateResumedetails candidateResumedetails, Job job,
                     ClientInterviewStatus clientInterviewStatus,
                     RefrlStatusMstr refrlStatusMstr, Campaign campaign,
                     UserProfile userProfile, UserProfile submittedBy, Contest contest, int companyMstrSeq,
                     String ripplehireSeq, String clientCandidateId, String refrlModeCd,
                     String shiftStatus, String refrlToken, Integer refrlRating,
                     String refrlComments, int candidateClicks, String socialMediaId,
                     String isLegacy, String referReason, String referTime,
                     String isReferFresher, String isReferChannelFacebook,
                     String allowRefererName, Integer parentEmplRefrlSeq, String countThrottle, char status,
                     Date clientUpdateDttm, int createdBy, Date applyDate,
                     Date walkinDate, Date joiningDate, Date createDttm,
                     Integer updatedBy, Date updateDttm, String vendorId,
                     Set<EmplReward> emplRewards, Set<CandidateLog> candidateLogs,
                     Set<EmpCandConv> empCandConvs,
                     Set<EmplActivity> emplActivitys,
                     Set<InterviewSchedule> interviewSchedules,
                     Set<InterviewDetails> interviewDetailses,
                     Set<CandidateUploadResumeDetails> candidateUploadResumeDetailses,
                     int lifeCycleState, DuplicateCandidateLog duplicateCandidateLog
    ) {
        this.candidate = candidate;

        this.interviewStageMstr = interviewStageMstr;
        this.refrlChannelMstr = refrlChannelMstr;
        this.relationshipMstr = relationshipMstr;
        this.candidateResumedetails = candidateResumedetails;
        this.duplicateCandidateLog = duplicateCandidateLog;
        this.job = job;
        this.clientInterviewStatus = clientInterviewStatus;
        this.refrlStatusMstr = refrlStatusMstr;
        this.campaign = campaign;
        this.userProfile = userProfile;
        this.submittedBy = submittedBy;
        this.contest = contest;
        this.companyMstrSeq = companyMstrSeq;
        this.ripplehireSeq = ripplehireSeq;
        this.clientCandidateId = clientCandidateId;
        this.refrlModeCd = refrlModeCd;
        this.shiftStatus = shiftStatus;
        this.refrlToken = refrlToken;
        this.refrlRating = refrlRating;
        this.refrlComments = refrlComments;
        this.candidateClicks = candidateClicks;
        this.socialMediaId = socialMediaId;
        this.isLegacy = isLegacy;
        this.referReason = referReason;
        this.referTime = referTime;
        this.isReferFresher = isReferFresher;
        this.isReferChannelFacebook = isReferChannelFacebook;
        this.allowRefererName = allowRefererName;
        this.parentEmplRefrlSeq = parentEmplRefrlSeq;
        this.countThrottle = countThrottle;
        this.status = status;
        this.clientUpdateDttm = clientUpdateDttm;
        this.createdBy = createdBy;
        this.applyDate = applyDate;
        this.walkinDate = walkinDate;
        this.joiningDate = joiningDate;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
        this.vendorId = vendorId;
        this.emplRewards = emplRewards;
        this.candidateLogs = candidateLogs;
        this.emplActivitys = emplActivitys;
        this.empCandConvs = empCandConvs;
        this.interviewDetailses = interviewDetailses;
        this.candidateUploadResumeDetailses = candidateUploadResumeDetailses;
        this.interviewSchedules = interviewSchedules;
        this.lifeCycleState = lifeCycleState;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "EMPL_REFRL_SEQ", unique = true, nullable = false)
    public Integer getEmplRefrlSeq() {
        return this.emplRefrlSeq;
    }

    public void setEmplRefrlSeq(Integer emplRefrlSeq) {
        this.emplRefrlSeq = emplRefrlSeq;
    }

    @Column(name="ALLOW_REDEMPTION",length=1,nullable = false)
    public Character getAllowRedemption() {
        return allowRedemption;
    }

    public void setAllowRedemption(Character allowRedemption) {
        this.allowRedemption = allowRedemption;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CANDIDATE_SEQ")
    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INTERVIEW_STAGE_MSTR_SEQ")
    public InterviewStageMstr getInterviewStageMstr() {
        return this.interviewStageMstr;
    }

    public void setInterviewStageMstr(InterviewStageMstr interviewStageMstr) {
        this.interviewStageMstr = interviewStageMstr;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REFRL_CHANNEL_MSTR_SEQ", nullable = false)
    public RefrlChannelMstr getRefrlChannelMstr() {
        return this.refrlChannelMstr;
    }

    public void setRefrlChannelMstr(RefrlChannelMstr refrlChannelMstr) {
        this.refrlChannelMstr = refrlChannelMstr;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "RELATIONSHIP_MSTR_SEQ")
    public RelationshipMstr getRelationshipMstr() {
        return this.relationshipMstr;
    }

    public void setRelationshipMstr(RelationshipMstr relationshipMstr) {
        this.relationshipMstr = relationshipMstr;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CANDIDATE_RESUMEDETAILS_SEQ")
    public CandidateResumedetails getCandidateResumedetails() {
        return this.candidateResumedetails;
    }

    public void setCandidateResumedetails(
            CandidateResumedetails candidateResumedetails) {
        this.candidateResumedetails = candidateResumedetails;
    }



    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DUPLICATE_CANDIDATE_LOG_SEQ")
    public DuplicateCandidateLog getDuplicateCandidateLog() {
        return duplicateCandidateLog;
    }

    public void setDuplicateCandidateLog(DuplicateCandidateLog duplicateCandidateLog) {
        this.duplicateCandidateLog = duplicateCandidateLog;
    }



    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "JOB_SEQ")
    public Job getJob() {
        return this.job;
    }

    public void setJob(Job job) {
        this.job = job;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CLIENT_INTERVIEW_STATUS_SEQ")
    public ClientInterviewStatus getClientInterviewStatus() {
        return this.clientInterviewStatus;
    }

    public void setClientInterviewStatus(
            ClientInterviewStatus clientInterviewStatus) {
        this.clientInterviewStatus = clientInterviewStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REFRL_STATUS_MSTR_SEQ", nullable = false)
    public RefrlStatusMstr getRefrlStatusMstr() {
        return this.refrlStatusMstr;
    }

    public void setRefrlStatusMstr(RefrlStatusMstr refrlStatusMstr) {
        this.refrlStatusMstr = refrlStatusMstr;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CAMPAIGN_SEQ")
    public Campaign getCampaign() {
        return this.campaign;
    }

    public void setCampaign(Campaign campaign) {
        this.campaign = campaign;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_PROFILE_SEQ", nullable = false)
    public UserProfile getUserProfile() {
        return this.userProfile;
    }

    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SUBMITTED_BY")
    public UserProfile getSubmittedBy() {
        return submittedBy;
    }

    public void setSubmittedBy(UserProfile submittedBy) {
        this.submittedBy = submittedBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONTEST_SEQ")
    public Contest getContest() {
        return this.contest;
    }

    public void setContest(Contest contest) {
        this.contest = contest;
    }

    @Column(name = "COMPANY_MSTR_SEQ", nullable = false)
    public int getCompanyMstrSeq() {
        return this.companyMstrSeq;
    }

    public void setCompanyMstrSeq(int companyMstrSeq) {
        this.companyMstrSeq = companyMstrSeq;
    }

    @Column(name = "RIPPLEHIRE_SEQ", length = 50)
    public String getRipplehireSeq() {
        return this.ripplehireSeq;
    }

    public void setRipplehireSeq(String ripplehireSeq) {
        this.ripplehireSeq = ripplehireSeq;
    }

    @Column(name = "CLIENT_CANDIDATE_ID", length = 100)
    public String getClientCandidateId() {
        return this.clientCandidateId;
    }

    public void setClientCandidateId(String clientCandidateId) {
        this.clientCandidateId = clientCandidateId;
    }

    @Column(name = "REFRL_MODE_CD", length = 50)
    public String getRefrlModeCd() {
        return this.refrlModeCd;
    }

    public void setRefrlModeCd(String refrlModeCd) {
        this.refrlModeCd = refrlModeCd;
    }

    @Column(name = "SHIFT_STATUS", nullable = false, length = 50)
    public String getShiftStatus() {
        return this.shiftStatus;
    }

    public void setShiftStatus(String shiftStatus) {
        this.shiftStatus = shiftStatus;
    }

    @Column(name = "REFRL_TOKEN", length = 200)
    public String getRefrlToken() {
        return this.refrlToken;
    }

    public void setRefrlToken(String refrlToken) {
        this.refrlToken = refrlToken;
    }

    @Column(name = "REFRL_RATING")
    public Integer getRefrlRating() {
        return this.refrlRating;
    }

    public void setRefrlRating(Integer refrlRating) {
        this.refrlRating = refrlRating;
    }

    @Column(name = "REFRL_COMMENTS")
    public String getRefrlComments() {
        return this.refrlComments;
    }

    public void setRefrlComments(String refrlComments) {
        this.refrlComments = refrlComments;
    }

    @Column(name = "CANDIDATE_CLICKS", nullable = false)
    public int getCandidateClicks() {
        return this.candidateClicks;
    }

    public void setCandidateClicks(int candidateClicks) {
        this.candidateClicks = candidateClicks;
    }

    @Column(name = "SOCIAL_MEDIA_ID", length = 50)
    public String getSocialMediaId() {
        return this.socialMediaId;
    }

    public void setSocialMediaId(String socialMediaId) {
        this.socialMediaId = socialMediaId;
    }

    @Column(name = "IS_LEGACY", length = 1)
    public String getIsLegacy() {
        return this.isLegacy;
    }

    public void setIsLegacy(String isLegacy) {
        this.isLegacy = isLegacy;
    }

    @Column(name = "REFER_REASON")
    public String getReferReason() {
        return this.referReason;
    }

    public void setReferReason(String referReason) {
        this.referReason = referReason;
    }

    @Column(name = "REFER_TIME")
    public String getReferTime() {
        return this.referTime;
    }

    public void setReferTime(String referTime) {
        this.referTime = referTime;
    }

    @Column(name = "IS_REFER_FRESHER", length = 1)
    public String getIsReferFresher() {
        return this.isReferFresher;
    }

    public void setIsReferFresher(String isReferFresher) {
        this.isReferFresher = isReferFresher;
    }

    @Column(name = "IS_REFER_CHANNEL_FACEBOOK", length = 1)
    public String getIsReferChannelFacebook() {
        return this.isReferChannelFacebook;
    }

    public void setIsReferChannelFacebook(String isReferChannelFacebook) {
        this.isReferChannelFacebook = isReferChannelFacebook;
    }

    @Column(name = "ALLOW_REFERER_NAME", length = 1)
    public String getAllowRefererName() {
        return this.allowRefererName;
    }

    public void setAllowRefererName(String allowRefererName) {
        this.allowRefererName = allowRefererName;
    }

    @Column(name = "PARENT_EMPL_REFRL_SEQ")
    public Integer getParentEmplRefrlSeq() {
        return this.parentEmplRefrlSeq;
    }

    public void setParentEmplRefrlSeq(Integer parentEmplRefrlSeq) {
        this.parentEmplRefrlSeq = parentEmplRefrlSeq;
    }

    @Column(name = "COUNT_THROTTLE")
    public String getCountThrottle() {
        return countThrottle;
    }

    public void setCountThrottle(String countThrottle) {
        this.countThrottle = countThrottle;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }



    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CLIENT_UPDATE_DTTM", length = 19)
    public Date getClientUpdateDttm() {
        return this.clientUpdateDttm;
    }

    public void setClientUpdateDttm(Date clientUpdateDttm) {
        this.clientUpdateDttm = clientUpdateDttm;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "APPLY_DATE", length = 10)
    public Date getApplyDate() {
        return this.applyDate;
    }

    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "WALKIN_DATE", length = 10)
    public Date getWalkinDate() {
        return this.walkinDate;
    }

    public void setWalkinDate(Date walkinDate) {
        this.walkinDate = walkinDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "JOINING_DATE", length = 10)
    public Date getJoiningDate() {
        return this.joiningDate;
    }

    public void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DTTM", nullable = false, length = 19)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DTTM", length = 19)
    public Date getUpdateDttm() {
        return this.updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }

    @Column(name = "VENDOR_ID", length = 50)
    public String getVendorId() {
        return this.vendorId;
    }

    public void setVendorId(String vendorId) {
        this.vendorId = vendorId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INTERVIEW_DETAIL_SEQ")
    public InterviewDetails getInterviewDetails() {
        return this.interviewDetails;
    }

    public void setInterviewDetails(InterviewDetails interviewDetails) {
        this.interviewDetails = interviewDetails;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "emplRefrl")
    public Set<EmplReward> getEmplRewards() {
        return this.emplRewards;
    }

    public void setEmplRewards(Set<EmplReward> emplRewards) {
        this.emplRewards = emplRewards;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "emplRefrl")
    public Set<CandidateLog> getCandidateLogs() {
        return this.candidateLogs;
    }

    public void setCandidateLogs(Set<CandidateLog> candidateLogs) {
        this.candidateLogs = candidateLogs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "emplRefrl")
    public Set<EmpCandConv> getEmpCandConvs() {
        return this.empCandConvs;
    }

    public void setEmpCandConvs(Set<EmpCandConv> empCandConvs) {
        this.empCandConvs = empCandConvs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "emplRefrl")
    public Set<InterviewDetails> getInterviewDetailses() {
        return this.interviewDetailses;
    }

    public void setInterviewDetailses(Set<InterviewDetails> interviewDetailses) {
        this.interviewDetailses = interviewDetailses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "emplRefrl")
    public Set<EmplActivity> getEmplActivitys() {
        return this.emplActivitys;
    }

    public void setEmplActivitys(Set<EmplActivity> emplActivitys) {
        this.emplActivitys = emplActivitys;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "emplRefrl")
    public Set<CandidateUploadResumeDetails> getCandidateUploadResumeDetailses() {
        return this.candidateUploadResumeDetailses;
    }

    public void setCandidateUploadResumeDetailses(
            Set<CandidateUploadResumeDetails> candidateUploadResumeDetailses) {
        this.candidateUploadResumeDetailses = candidateUploadResumeDetailses;
    }

    @Column(name = "PREV_USER_PROFILE_SEQ")
    public Integer getPrevUserProfileSeq() {
        return prevUserProfileSeq;
    }

    public void setPrevUserProfileSeq(Integer prevUserProfileSeq) {
        this.prevUserProfileSeq = prevUserProfileSeq;
    }

    @Column(name = "PREV_REFRL_CHANNEL_MSTR_SEQ")
    public Integer getPrevRefrlChannelMstrSeq() {
        return prevRefrlChannelMstrSeq;
    }

    public void setPrevRefrlChannelMstrSeq(Integer prevRefrlChannelMstrSeq) {
        this.prevRefrlChannelMstrSeq = prevRefrlChannelMstrSeq;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "emplRefrl")
    public Set<InterviewSchedule> getInterviewSchedules() {
        return this.interviewSchedules;
    }

    public void setInterviewSchedules(Set<InterviewSchedule> interviewSchedules) {
        this.interviewSchedules = interviewSchedules;
    }

    @Column(name = "LIFE_CYCLE_STATE", nullable = false, length = 1)
    public int getLifeCycleState() {
        return this.lifeCycleState;
    }

    public void setLifeCycleState(int lifeCycleState) {
        this.lifeCycleState = lifeCycleState;
    }

}
