package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * EmployeeMstr generated by hbm2java
 */
@Entity
@Table(name = "employee_mstr")
public class EmployeeMstr implements java.io.Serializable {

    private Integer employeeMstrSeq;
    private UserProfile userProfile;
    private int companyMstrSeq;
    private EmployeeMstrDetails employeeMstrDetails;
    private String companyEmplId;
    private String firstName;
    private String lastName;
    private String emailAddr;
    private String phoneNo;
    private String department;
    private String location;
    private char isRecruiter;
    private char isInterviewer;
    private char employeeType;
    private String employeeLevel;
    private char ijpAllowed;
    private Date empJoiningDate;
    private Date dob;
    private char status;
    private int createdBy;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;

    public EmployeeMstr() {
    }

    public EmployeeMstr(UserProfile userProfile, int companyMstrSeq, String firstName, String lastName, char isRecruiter, char isInterviewer, char employeeType, char status, int createdBy, Date createDttm) {
        this.userProfile = userProfile;
        this.companyMstrSeq = companyMstrSeq;
        this.firstName = firstName;
        this.lastName = lastName;
        this.isRecruiter = isRecruiter;
        this.isInterviewer = isInterviewer;
        this.employeeType = employeeType;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
    }

    public EmployeeMstr(UserProfile userProfile, int companyMstrSeq, EmployeeMstrDetails employeeMstrDetails, String companyEmplId, String firstName, String lastName, String emailAddr, String phoneNo, String department, String location, char isRecruiter, char isInterviewer, char employeeType, String employeeLevel, char ijpAllowed, Date empJoiningDate, char status, int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
        this.userProfile = userProfile;
        this.companyMstrSeq = companyMstrSeq;
        this.employeeMstrDetails = employeeMstrDetails;
        this.companyEmplId = companyEmplId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.emailAddr = emailAddr;
        this.phoneNo = phoneNo;
        this.department = department;
        this.location = location;
        this.isRecruiter = isRecruiter;
        this.isInterviewer = isInterviewer;
        this.employeeType = employeeType;
        this.employeeLevel = employeeLevel;
        this.ijpAllowed = ijpAllowed;
        this.empJoiningDate = empJoiningDate;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "EMPLOYEE_MSTR_SEQ", unique = true, nullable = false)
    public Integer getEmployeeMstrSeq() {
        return this.employeeMstrSeq;
    }

    public void setEmployeeMstrSeq(Integer employeeMstrSeq) {
        this.employeeMstrSeq = employeeMstrSeq;
    }

    @ManyToOne
    @JoinColumn(name = "USER_PROFILE_SEQ", nullable = false)
    public UserProfile getUserProfile() {
        return this.userProfile;
    }

    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }

    @Column(name = "COMPANY_MSTR_SEQ", nullable = false)
    public int getCompanyMstrSeq() {
        return this.companyMstrSeq;
    }

    public void setCompanyMstrSeq(int companyMstrSeq) {
        this.companyMstrSeq = companyMstrSeq;
    }

    @ManyToOne
    @JoinColumn(name = "EMPLOYEE_MSTR_DETAILS_SEQ")
    public EmployeeMstrDetails getEmployeeMstrDetails() {
        return employeeMstrDetails;
    }

    public void setEmployeeMstrDetails(EmployeeMstrDetails employeeMstrDetails) {
        this.employeeMstrDetails = employeeMstrDetails;
    }

    @Column(name = "COMPANY_EMPL_ID", length = 20)
    public String getCompanyEmplId() {
        return this.companyEmplId;
    }

    public void setCompanyEmplId(String companyEmplId) {
        this.companyEmplId = companyEmplId;
    }

    @Column(name = "FIRST_NAME", nullable = false, length = 30)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "LAST_NAME", nullable = false, length = 30)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "EMAIL_ADDR", length = 50)
    public String getEmailAddr() {
        return this.emailAddr;
    }

    public void setEmailAddr(String emailAddr) {
        this.emailAddr = emailAddr;
    }

    @Column(name = "PHONE_NO", length = 15)
    public String getPhoneNo() {
        return this.phoneNo;
    }

    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    @Column(name = "LOCATION", length = 200)
    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Column(name = "DEPARTMENT", length = 200)
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @Column(name = "IS_RECRUITER", nullable = false, length = 1)
    public char getIsRecruiter() {
        return this.isRecruiter;
    }

    public void setIsRecruiter(char isRecruiter) {
        this.isRecruiter = isRecruiter;
    }

    @Column(name = "IS_INTERVIEWER", nullable = false, length = 1)
    public char getIsInterviewer() {
        return this.isInterviewer;
    }

    public void setIsInterviewer(char isInterviewer) {
        this.isInterviewer = isInterviewer;
    }

    @Column(name = "EMPLOYEE_TYPE", nullable = false, length = 1)
    public char getEmployeeType() {
        return this.employeeType;
    }

    public void setEmployeeType(char employeeType) {
        this.employeeType = employeeType;
    }

    @Column(name = "EMPLOYEE_LEVEL", length = 50)
    public String getEmployeeLevel() {
        return employeeLevel;
    }

    public void setEmployeeLevel(String employeeLevel) {
        this.employeeLevel = employeeLevel;
    }

    @Column(name = "IJP_ALLOWED", nullable = false, length = 1,columnDefinition = "char(1) DEFAULT Y ")
    public char getIjpAllowed() {
        return ijpAllowed;
    }

    public void setIjpAllowed(char ijpAllowed) {
        this.ijpAllowed = ijpAllowed;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "EMP_JOINING_DATE")
    public Date getEmpJoiningDate() {
        return empJoiningDate;
    }

    public void setEmpJoiningDate(Date empJoiningDate) {
        this.empJoiningDate = empJoiningDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DOB")
    public Date getDob() {
        return dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DTTM", nullable = false, length = 19)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DTTM", length = 19)
    public Date getUpdateDttm() {
        return this.updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }
}
