package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmplMedal generated by hbm2java
 */
@Entity
@Table(name = "empl_medal")
public class EmplMedal implements java.io.Serializable {

	private Integer emplMedalSeq;
	private RewardMedal rewardMedal;
	private UserProfile userProfile;
	private int companyMstrSeq;
	private int medalCount;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public EmplMedal() {
	}

	public EmplMedal(RewardMedal rewardMedal, UserProfile userProfile,
			int companyMstrSeq, int medalCount, char status, int createdBy,
			Date createDttm) {
		this.rewardMedal = rewardMedal;
		this.userProfile = userProfile;
		this.companyMstrSeq = companyMstrSeq;
		this.medalCount = medalCount;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public EmplMedal(RewardMedal rewardMedal, UserProfile userProfile,
			int companyMstrSeq, int medalCount, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm) {
		this.rewardMedal = rewardMedal;
		this.userProfile = userProfile;
		this.companyMstrSeq = companyMstrSeq;
		this.medalCount = medalCount;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EMPL_MEDAL_SEQ", unique = true, nullable = false)
	public Integer getEmplMedalSeq() {
		return this.emplMedalSeq;
	}

	public void setEmplMedalSeq(Integer emplMedalSeq) {
		this.emplMedalSeq = emplMedalSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REWARD_MEDAL_SEQ", nullable = false)
	public RewardMedal getRewardMedal() {
		return this.rewardMedal;
	}

	public void setRewardMedal(RewardMedal rewardMedal) {
		this.rewardMedal = rewardMedal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PROFILE_SEQ", nullable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "MEDAL_COUNT", nullable = false)
	public int getMedalCount() {
		return this.medalCount;
	}

	public void setMedalCount(int medalCount) {
		this.medalCount = medalCount;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
