package com.ripplehire.candidate.entities;
// Generated 9 Sep, 2016 2:12:35 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EtlFileLog generated by hbm2java
 */
@Entity
@Table(name = "etl_file_log")
public class EtlFileLog implements java.io.Serializable {

	private Integer etlFileLogSeq;
	private int companyMstrSeq;
	private String etlType;
	private String uploadedBy;
	private String uploadedFileSubDirectory;
	private String uploadedFile;
	private String uploadedFileRefName;
	private String uploadStatus;
	private String processedFileSubDirectory;
	private String processedFile;
	private String processedFileRefName;
	private String errorDetails;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private char status;

	public EtlFileLog() {
	}

	public EtlFileLog(int companyMstrSeq, String etlType, String uploadedBy, String uploadedFile, int createdBy,
			Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.etlType = etlType;
		this.uploadedBy = uploadedBy;
		this.uploadedFile = uploadedFile;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public EtlFileLog(int companyMstrSeq, String etlType, String uploadedBy, String uploadedFile, String uploadStatus,
			String processedFile, String errorDetails, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.etlType = etlType;
		this.uploadedBy = uploadedBy;
		this.uploadedFile = uploadedFile;
		this.uploadStatus = uploadStatus;
		this.processedFile = processedFile;
		this.errorDetails = errorDetails;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ETL_FILE_LOG_SEQ", unique = true, nullable = false)
	public Integer getEtlFileLogSeq() {
		return this.etlFileLogSeq;
	}

	public void setEtlFileLogSeq(Integer etlFileLogSeq) {
		this.etlFileLogSeq = etlFileLogSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "ETL_TYPE", nullable = false, length = 50)
	public String getEtlType() {
		return this.etlType;
	}

	public void setEtlType(String etlType) {
		this.etlType = etlType;
	}

	@Column(name = "UPLOADED_BY", nullable = false, length = 100)
	public String getUploadedBy() {
		return this.uploadedBy;
	}

	public void setUploadedBy(String uploadedBy) {
		this.uploadedBy = uploadedBy;
	}

	@Column(name = "UPLOADED_FILE_SUB_DIRECTORY", length = 400)
	public String getUploadedFileSubDirectory() {
		return uploadedFileSubDirectory;
	}

	public void setUploadedFileSubDirectory(String uploadedFileSubDirectory) {
		this.uploadedFileSubDirectory = uploadedFileSubDirectory;
	}

	@Column(name = "UPLOADED_FILE", nullable = false, length = 100)
	public String getUploadedFile() {
		return this.uploadedFile;
	}

	public void setUploadedFile(String uploadedFile) {
		this.uploadedFile = uploadedFile;
	}

	@Column(name = "UPLOADED_FILE_REF_NAME", nullable = false, length = 150)
	public String getUploadedFileRefName() {		return uploadedFileRefName;	}

	public void setUploadedFileRefName(String uploadedFileRefName) {		this.uploadedFileRefName = uploadedFileRefName;	}

	@Column(name = "UPLOAD_STATUS", length = 100)
	public String getUploadStatus() {
		return this.uploadStatus;
	}

	public void setUploadStatus(String uploadStatus) {
		this.uploadStatus = uploadStatus;
	}

	@Column(name = "PROCESSED_FILE_SUB_DIRECTORY", length = 400)
	public String getProcessedFileSubDirectory() {
		return processedFileSubDirectory;
	}

	public void setProcessedFileSubDirectory(String processedFileSubDirectory) {
		this.processedFileSubDirectory = processedFileSubDirectory;
	}

	@Column(name = "PROCESSED_FILE", length = 100)
	public String getProcessedFile() {
		return this.processedFile;
	}

	public void setProcessedFile(String processedFile) {
		this.processedFile = processedFile;
	}

	@Column(name = "PROCESSED_FILE_REF_NAME", length = 150)
	public String getProcessedFileRefName() {		return processedFileRefName;	}

	public void setProcessedFileRefName(String processedFileRefName) {		this.processedFileRefName = processedFileRefName;	}

	@Column(name = "ERROR_DETAILS")
	public String getErrorDetails() {
		return this.errorDetails;
	}

	public void setErrorDetails(String errorDetails) {
		this.errorDetails = errorDetails;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}


	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

}
