package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FbUserNetwork generated by hbm2java
 */
@Entity
@Table(name = "fb_user_network")
public class FbUserNetwork implements java.io.Serializable {

	private Integer fbUserNetworkSeq;
	private UserProfile userProfile;
	private String friendUserId;
	private String friendFirstName;
	private String friendLastName;
	private String friendPublicProfileUrl;
	private String friendLocation;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public FbUserNetwork() {
	}

	public FbUserNetwork(UserProfile userProfile, String friendUserId,
			char status, int createdBy, Date createDttm) {
		this.userProfile = userProfile;
		this.friendUserId = friendUserId;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public FbUserNetwork(UserProfile userProfile, String friendUserId,
			String friendFirstName, String friendLastName,
			String friendPublicProfileUrl, String friendLocation, char status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
		this.userProfile = userProfile;
		this.friendUserId = friendUserId;
		this.friendFirstName = friendFirstName;
		this.friendLastName = friendLastName;
		this.friendPublicProfileUrl = friendPublicProfileUrl;
		this.friendLocation = friendLocation;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FB_USER_NETWORK_SEQ", unique = true, nullable = false)
	public Integer getFbUserNetworkSeq() {
		return this.fbUserNetworkSeq;
	}

	public void setFbUserNetworkSeq(Integer fbUserNetworkSeq) {
		this.fbUserNetworkSeq = fbUserNetworkSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PROFILE_SEQ", nullable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "FRIEND_USER_ID", nullable = false)
	public String getFriendUserId() {
		return this.friendUserId;
	}

	public void setFriendUserId(String friendUserId) {
		this.friendUserId = friendUserId;
	}

	@Column(name = "FRIEND_FIRST_NAME")
	public String getFriendFirstName() {
		return this.friendFirstName;
	}

	public void setFriendFirstName(String friendFirstName) {
		this.friendFirstName = friendFirstName;
	}

	@Column(name = "FRIEND_LAST_NAME")
	public String getFriendLastName() {
		return this.friendLastName;
	}

	public void setFriendLastName(String friendLastName) {
		this.friendLastName = friendLastName;
	}

	@Column(name = "FRIEND_PUBLIC_PROFILE_URL", length = 1000)
	public String getFriendPublicProfileUrl() {
		return this.friendPublicProfileUrl;
	}

	public void setFriendPublicProfileUrl(String friendPublicProfileUrl) {
		this.friendPublicProfileUrl = friendPublicProfileUrl;
	}

	@Column(name = "FRIEND_LOCATION")
	public String getFriendLocation() {
		return this.friendLocation;
	}

	public void setFriendLocation(String friendLocation) {
		this.friendLocation = friendLocation;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
