package com.ripplehire.candidate.entities;

// Generated Apr 8, 2015 4:42:08 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FraudChecklist generated by hbm2java
 */
@Entity
@Table(name = "fraud_checklist")
public class FraudChecklist implements java.io.Serializable {


	private Integer checkSeq;
	private int companyMstrSeq;
	private String checkType;
	private String keywords;
	private String status;
	private int createdBy;
	private Date createdDttm;
	private Integer updatedBy;
	private Date updatedDttm;

	public FraudChecklist() {
	}

	public FraudChecklist(int companyMstrSeq, String checkType,
			String keywords, String status, int createdBy, Date createdDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.checkType = checkType;
		this.keywords = keywords;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public FraudChecklist(int companyMstrSeq, String checkType,
			String keywords, String status, int createdBy, Date createdDttm,
			Integer updatedBy, Date updatedDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.checkType = checkType;
		this.keywords = keywords;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CHECK_SEQ", unique = true, nullable = false)
	public Integer getCheckSeq() {
		return this.checkSeq;
	}

	public void setCheckSeq(Integer checkSeq) {
		this.checkSeq = checkSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "CHECK_TYPE", nullable = false, length = 100)
	public String getCheckType() {
		return this.checkType;
	}

	public void setCheckType(String checkType) {
		this.checkType = checkType;
	}

	@Column(name = "KEYWORDS", nullable = false, length = 300)
	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	@Column(name = "STATUS", nullable = false, length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

}
