package com.ripplehire.candidate.entities;

// Generated Aug 12, 2014 2:57:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GenderMstr generated by hbm2java
 */
@Entity
@Table(name = "gender_mstr")
public class GenderMstr implements java.io.Serializable {

	private Integer genderMstrSeq;
	private int companyMstrSeq;
	private int genderClientKey;
	private String genderDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<GenderMstrLang> genderMstrLangs = new HashSet<GenderMstrLang>(0);
	private Set<CandidateResumedetails> candidateResumedetailses = new HashSet<CandidateResumedetails>(
			0);

	public GenderMstr() {
	}

	public GenderMstr(int companyMstrSeq, int genderClientKey,
			String genderDesc, char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.genderClientKey = genderClientKey;
		this.genderDesc = genderDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public GenderMstr(int companyMstrSeq, int genderClientKey,
			String genderDesc, char status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm,
			Set<GenderMstrLang> genderMstrLangs,
			Set<CandidateResumedetails> candidateResumedetailses) {
		this.companyMstrSeq = companyMstrSeq;
		this.genderClientKey = genderClientKey;
		this.genderDesc = genderDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.genderMstrLangs = genderMstrLangs;
		this.candidateResumedetailses = candidateResumedetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "GENDER_MSTR_SEQ", unique = true, nullable = false)
	public Integer getGenderMstrSeq() {
		return this.genderMstrSeq;
	}

	public void setGenderMstrSeq(Integer genderMstrSeq) {
		this.genderMstrSeq = genderMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "GENDER_CLIENT_KEY", nullable = false)
	public int getGenderClientKey() {
		return this.genderClientKey;
	}

	public void setGenderClientKey(int genderClientKey) {
		this.genderClientKey = genderClientKey;
	}

	@Column(name = "GENDER_DESC", nullable = false, length = 50)
	public String getGenderDesc() {
		return this.genderDesc;
	}

	public void setGenderDesc(String genderDesc) {
		this.genderDesc = genderDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genderMstr")
	public Set<GenderMstrLang> getGenderMstrLangs() {
		return this.genderMstrLangs;
	}

	public void setGenderMstrLangs(Set<GenderMstrLang> genderMstrLangs) {
		this.genderMstrLangs = genderMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genderMstr")
	public Set<CandidateResumedetails> getCandidateResumedetailses() {
		return this.candidateResumedetailses;
	}

	public void setCandidateResumedetailses(
			Set<CandidateResumedetails> candidateResumedetailses) {
		this.candidateResumedetailses = candidateResumedetailses;
	}

}
