package com.ripplehire.candidate.entities;

// Generated Aug 12, 2014 2:57:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GenderMstrLang generated by hbm2java
 */
@Entity
@Table(name = "gender_mstr_lang")
public class GenderMstrLang implements java.io.Serializable {

	private Integer genderMstrLangSeq;
	private GenderMstr genderMstr;
	private LangMstr langMstr;
	private String genderDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public GenderMstrLang() {
	}

	public GenderMstrLang(GenderMstr genderMstr, LangMstr langMstr,
			String genderDesc, char status, int createdBy, Date createDttm) {
		this.genderMstr = genderMstr;
		this.langMstr = langMstr;
		this.genderDesc = genderDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public GenderMstrLang(GenderMstr genderMstr, LangMstr langMstr,
			String genderDesc, char status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm) {
		this.genderMstr = genderMstr;
		this.langMstr = langMstr;
		this.genderDesc = genderDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "GENDER_MSTR_LANG_SEQ", unique = true, nullable = false)
	public Integer getGenderMstrLangSeq() {
		return this.genderMstrLangSeq;
	}

	public void setGenderMstrLangSeq(Integer genderMstrLangSeq) {
		this.genderMstrLangSeq = genderMstrLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GENDER_MSTR_SEQ", nullable = false)
	public GenderMstr getGenderMstr() {
		return this.genderMstr;
	}

	public void setGenderMstr(GenderMstr genderMstr) {
		this.genderMstr = genderMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@Column(name = "GENDER_DESC", nullable = false, length = 100)
	public String getGenderDesc() {
		return this.genderDesc;
	}

	public void setGenderDesc(String genderDesc) {
		this.genderDesc = genderDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
