package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GoalActivity generated by hbm2java
 */
@Entity
@Table(name = "goal_activity")
public class GoalActivity implements java.io.Serializable {

	private Integer goalActivitySeq;
	private ActivityMstr activityMstr;
	private Goal goal;
	private int companyMstrSeq;
	private int activityCount;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public GoalActivity() {
	}

	public GoalActivity(ActivityMstr activityMstr, Goal goal,
			int companyMstrSeq, int activityCount, char status, int createdBy,
			Date createDttm) {
		this.activityMstr = activityMstr;
		this.goal = goal;
		this.companyMstrSeq = companyMstrSeq;
		this.activityCount = activityCount;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public GoalActivity(ActivityMstr activityMstr, Goal goal,
			int companyMstrSeq, int activityCount, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm) {
		this.activityMstr = activityMstr;
		this.goal = goal;
		this.companyMstrSeq = companyMstrSeq;
		this.activityCount = activityCount;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "GOAL_ACTIVITY_SEQ", unique = true, nullable = false)
	public Integer getGoalActivitySeq() {
		return this.goalActivitySeq;
	}

	public void setGoalActivitySeq(Integer goalActivitySeq) {
		this.goalActivitySeq = goalActivitySeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTIVITY_MSTR_SEQ", nullable = false)
	public ActivityMstr getActivityMstr() {
		return this.activityMstr;
	}

	public void setActivityMstr(ActivityMstr activityMstr) {
		this.activityMstr = activityMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GOAL_SEQ", nullable = false)
	public Goal getGoal() {
		return this.goal;
	}

	public void setGoal(Goal goal) {
		this.goal = goal;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "ACTIVITY_COUNT", nullable = false)
	public int getActivityCount() {
		return this.activityCount;
	}

	public void setActivityCount(int activityCount) {
		this.activityCount = activityCount;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
