package com.ripplehire.candidate.entities;
// Generated 13 Sep, 2016 1:33:22 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * IciciLocationCodeMapping generated by hbm2java
 */
@Entity
@Table(name = "icici_location_code_mapping")
public class IciciLocationCodeMapping implements java.io.Serializable {

    private Integer iciciLocationCodeMappingSeq;
    private String locationCode;
    private String state;
    private String rhr;
    private String shr;
    private String zhr;
    private String market;
    private String channel;
    private String function;
    private String businessUnit;
    private char status;
    private Integer createdBy;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;

    public IciciLocationCodeMapping() {
    }

    public IciciLocationCodeMapping(String locationCode, String state, String rhr, String shr, String zhr, String market, String channel, String function, String businessUnit, char status, Integer createdBy, Date createDttm) {
        this.locationCode = locationCode;
        this.state = state;
        this.rhr = rhr;
        this.shr = shr;
        this.zhr = zhr;
        this.market = market;
        this.channel = channel;
        this.function = function;
        this.businessUnit = businessUnit;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
    }

    public IciciLocationCodeMapping(String locationCode, String state, String rhr, String shr, String zhr, String market, String channel, String function, String businessUnit, char status, Integer createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
        this.locationCode = locationCode;
        this.state = state;
        this.rhr = rhr;
        this.shr = shr;
        this.zhr = zhr;
        this.market = market;
        this.channel = channel;
        this.function = function;
        this.businessUnit = businessUnit;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ICICI_LOCATION_CODE_MAPPING_SEQ", unique = true, nullable = false)
    public Integer getIciciLocationCodeMappingSeq() {
        return iciciLocationCodeMappingSeq;
    }

    public void setIciciLocationCodeMappingSeq(Integer iciciLocationCodeMappingSeq) {
        this.iciciLocationCodeMappingSeq = iciciLocationCodeMappingSeq;
    }

    @Column(name = "LOCATION_CODE", length = 500)
    public String getLocationCode() {
        return locationCode;
    }

    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    @Column(name = "STATE", length = 500)
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "RHR", length = 500)
    public String getRhr() {
        return rhr;
    }

    public void setRhr(String rhr) {
        this.rhr = rhr;
    }

    @Column(name = "SHR", length = 500)
    public String getShr() {
        return shr;
    }

    public void setShr(String shr) {
        this.shr = shr;
    }

    @Column(name = "ZHR", length = 500)
    public String getZhr() {
        return zhr;
    }

    public void setZhr(String zhr) {
        this.zhr = zhr;
    }

    @Column(name = "MARKET", length = 500)
    public String getMarket() {
        return market;
    }

    public void setMarket(String market) {
        this.market = market;
    }

    @Column(name = "CHANNEL", length = 500)
    public String getChannel() {
        return channel;
    }

    public void setChannel(String channel) {
        this.channel = channel;
    }

    @Column(name = "FUNCTION", length = 500)
    public String getFunction() {
        return function;
    }

    public void setFunction(String function) {
        this.function = function;
    }

    @Column(name = "BUSINESS_UNIT", length = 500)
    public String getBusinessUnit() {
        return businessUnit;
    }

    public void setBusinessUnit(String businessUnit) {
        this.businessUnit = businessUnit;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }


    @Column(name = "CREATED_BY", nullable = false)
    public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DTTM", nullable = false)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DTTM")
    public Date getUpdateDttm() {
        return updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }
}
