package com.ripplehire.candidate.entities;
// Generated 18 Jan, 2017 10:08:19 AM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InterviewScheduleEmailLogMap generated by hbm2java
 */
@Entity
@Table(name = "interview_schedule_email_log_map", catalog = "buddyto")
public class InterviewScheduleEmailLogMap implements java.io.Serializable {

    private Integer interviewScheduleEmailLogMapSeq;
    private EmailLog emailLog;
    private InterviewSchedule interviewSchedule;
    private int companyMstrSeq;
    private int createdBy;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;

    public InterviewScheduleEmailLogMap() {
    }

    public InterviewScheduleEmailLogMap(EmailLog emailLog, InterviewSchedule interviewSchedule, int companyMstrSeq,
                                        int createdBy, Date createDttm) {
        this.emailLog = emailLog;
        this.interviewSchedule = interviewSchedule;
        this.companyMstrSeq = companyMstrSeq;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
    }

    public InterviewScheduleEmailLogMap(EmailLog emailLog, InterviewSchedule interviewSchedule, int companyMstrSeq,
                                        int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
        this.emailLog = emailLog;
        this.interviewSchedule = interviewSchedule;
        this.companyMstrSeq = companyMstrSeq;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "INTERVIEW_SCHEDULE_EMAIL_LOG_MAP_SEQ", unique = true, nullable = false)
    public Integer getInterviewScheduleEmailLogMapSeq() {
        return this.interviewScheduleEmailLogMapSeq;
    }

    public void setInterviewScheduleEmailLogMapSeq(Integer interviewScheduleEmailLogMapSeq) {
        this.interviewScheduleEmailLogMapSeq = interviewScheduleEmailLogMapSeq;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMAIL_LOG_SEQ", nullable = false)
    public EmailLog getEmailLog() {
        return this.emailLog;
    }

    public void setEmailLog(EmailLog emailLog) {
        this.emailLog = emailLog;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INTERVIEW_SCHEDULE_SEQ", nullable = false)
    public InterviewSchedule getInterviewSchedule() {
        return this.interviewSchedule;
    }

    public void setInterviewSchedule(InterviewSchedule interviewSchedule) {
        this.interviewSchedule = interviewSchedule;
    }

    @Column(name = "COMPANY_MSTR_SEQ", nullable = false)
    public int getCompanyMstrSeq() {
        return this.companyMstrSeq;
    }

    public void setCompanyMstrSeq(int companyMstrSeq) {
        this.companyMstrSeq = companyMstrSeq;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DTTM", nullable = false, length = 19)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DTTM", length = 19)
    public Date getUpdateDttm() {
        return this.updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }

}
