package com.ripplehire.candidate.entities;
// Generated 30 Mar, 2017 11:21:44 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InterviewSchedule generated by hbm2java
 */
@Entity
@Table(name = "interview_schedule")
public class InterviewSchedule implements java.io.Serializable {

    private Integer interviewScheduleSeq;
    private EmplRefrl emplRefrl;
    private Interview interview;
    private TimezoneMstr timezoneMstr;
    private int companyMstrSeq;
    private int createdBy;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;
    private String location;
    private char sendMailToInterviewer;
    private char sendMailToCandidate;
    private String locationInfo;
    private String timezoneCd;
    private Integer timezoneOffset;
    private Date startDttm;
    private Date endDttm;
    private char status;
    private Integer interviewScheduleCancelReasonSeq;
    private char sendEmailToCandidate;
    private char sendEmailToInterviewer;
    private char sendEmailCopy;
    private String icsFileId;
    private String candidateAlternateEmailId;
    private Set<InterviewScheduleEmailLogMap> interviewScheduleEmailLogMaps = new HashSet<InterviewScheduleEmailLogMap>(
            0);
    private Set<InterviewComments> interviewCommentses = new HashSet<InterviewComments>(0);
    private Set<InterviewFeedbackComments> interviewFeedbackCommentses = new HashSet<InterviewFeedbackComments>(0);
    private Set<InterviewScheduleAttendee> interviewScheduleAttendees = new HashSet<InterviewScheduleAttendee>(0);
    private Set<InterviewTask> interviewTasks = new HashSet<InterviewTask>(0);
    private Set<InterviewFeedbackAnswers> interviewFeedbackAnswerses = new HashSet<InterviewFeedbackAnswers>(0);

    public InterviewSchedule() {
    }

    public InterviewSchedule(EmplRefrl emplRefrl, int companyMstrSeq, int createdBy,
                             Date createDttm, char sendMailToInterviewer, char sendMailToCandidate, Date startDttm, Date endDttm,
                             char status, String icsFileId) {
        this.emplRefrl = emplRefrl;
        this.companyMstrSeq = companyMstrSeq;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.sendMailToInterviewer = sendMailToInterviewer;
        this.sendMailToCandidate = sendMailToCandidate;
        this.startDttm = startDttm;
        this.endDttm = endDttm;
        this.status = status;
        this.icsFileId = icsFileId;
    }

    public InterviewSchedule(Integer interviewScheduleSeq, EmplRefrl emplRefrl, Interview interview, TimezoneMstr timezoneMstr, int companyMstrSeq, int createdBy, Date createDttm, Integer updatedBy, Date updateDttm, String location, char sendMailToInterviewer, char sendMailToCandidate, String locationInfo, String timezoneCd, Integer timezoneOffset, Date startDttm, Date endDttm, char status, Integer interviewScheduleCancelReasonSeq, char sendEmailToCandidate, char sendEmailToInterviewer, char sendEmailCopy, String icsFileId, String candidateAlternateEmailId, Set<InterviewScheduleEmailLogMap> interviewScheduleEmailLogMaps, Set<InterviewComments> interviewCommentses, Set<InterviewFeedbackComments> interviewFeedbackCommentses, Set<InterviewScheduleAttendee> interviewScheduleAttendees, Set<InterviewTask> interviewTasks, Set<InterviewFeedbackAnswers> interviewFeedbackAnswerses) {
        this.interviewScheduleSeq = interviewScheduleSeq;
        this.emplRefrl = emplRefrl;
        this.interview = interview;
        this.timezoneMstr = timezoneMstr;
        this.companyMstrSeq = companyMstrSeq;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
        this.location = location;
        this.sendMailToInterviewer = sendMailToInterviewer;
        this.sendMailToCandidate = sendMailToCandidate;
        this.locationInfo = locationInfo;
        this.timezoneCd = timezoneCd;
        this.timezoneOffset = timezoneOffset;
        this.startDttm = startDttm;
        this.endDttm = endDttm;
        this.status = status;
        this.interviewScheduleCancelReasonSeq = interviewScheduleCancelReasonSeq;
        this.sendEmailToCandidate = sendEmailToCandidate;
        this.sendEmailToInterviewer = sendEmailToInterviewer;
        this.sendEmailCopy = sendEmailCopy;
        this.icsFileId = icsFileId;
        this.candidateAlternateEmailId = candidateAlternateEmailId;
        this.interviewScheduleEmailLogMaps = interviewScheduleEmailLogMaps;
        this.interviewCommentses = interviewCommentses;
        this.interviewFeedbackCommentses = interviewFeedbackCommentses;
        this.interviewScheduleAttendees = interviewScheduleAttendees;
        this.interviewTasks = interviewTasks;
        this.interviewFeedbackAnswerses = interviewFeedbackAnswerses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "INTERVIEW_SCHEDULE_SEQ", unique = true, nullable = false)
    public Integer getInterviewScheduleSeq() {
        return this.interviewScheduleSeq;
    }

    public void setInterviewScheduleSeq(Integer interviewScheduleSeq) {
        this.interviewScheduleSeq = interviewScheduleSeq;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMPL_REFRL_SEQ", nullable = false)
    public EmplRefrl getEmplRefrl() {
        return this.emplRefrl;
    }

    public void setEmplRefrl(EmplRefrl emplRefrl) {
        this.emplRefrl = emplRefrl;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INTERVIEW_SEQ")
    public Interview getInterview() {
        return this.interview;
    }

    public void setInterview(Interview interview) {
        this.interview = interview;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TIMEZONE_MSTR_SEQ")
    public TimezoneMstr getTimezoneMstr() {
        return timezoneMstr;
    }

    @Column(name = "TIMEZONE_CD", length = 5)
    public String getTimezoneCd() {
        return timezoneCd;
    }

    public void setTimezoneCd(String timezoneCd) {
        this.timezoneCd = timezoneCd;
    }

    @Column(name = "TIMEZONE_OFFSET")
    public Integer getTimezoneOffset() {
        return timezoneOffset;
    }

    public void setTimezoneOffset(Integer timezoneOffset) {
        this.timezoneOffset = timezoneOffset;
    }

    public void setTimezoneMstr(TimezoneMstr timezoneMstr) {
        this.timezoneMstr = timezoneMstr;
    }

    @Column(name = "COMPANY_MSTR_SEQ", nullable = false)
    public int getCompanyMstrSeq() {
        return this.companyMstrSeq;
    }

    public void setCompanyMstrSeq(int companyMstrSeq) {
        this.companyMstrSeq = companyMstrSeq;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DTTM", nullable = false, length = 19)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DTTM", length = 19)
    public Date getUpdateDttm() {
        return this.updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }

    @Column(name = "LOCATION", length = 50)
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Column(name = "INTERVIEW_SCHEDULE_CANCEL_REASON_SEQ")
    public Integer getInterviewScheduleCancelReasonSeq() {
        return this.interviewScheduleCancelReasonSeq;
    }

    public void setInterviewScheduleCancelReasonSeq(Integer interviewScheduleCancelReasonSeq) {
        this.interviewScheduleCancelReasonSeq = interviewScheduleCancelReasonSeq;
    }

    @Column(name = "SEND_MAIL_TO_INTERVIEWER", nullable = false, length = 1)
    public char getSendMailToInterviewer() {
        return this.sendMailToInterviewer;
    }

    public void setSendMailToInterviewer(char sendMailToInterviewer) {
        this.sendMailToInterviewer = sendMailToInterviewer;
    }

    @Column(name = "SEND_MAIL_TO_CANDIDATE", nullable = false, length = 1)
    public char getSendMailToCandidate() {
        return this.sendMailToCandidate;
    }

    public void setSendMailToCandidate(char sendMailToCandidate) {
        this.sendMailToCandidate = sendMailToCandidate;
    }

    @Column(name = "LOCATION_INFO", length = 50)
    public String getLocationInfo() {
        return this.locationInfo;
    }

    public void setLocationInfo(String locationInfo) {
        this.locationInfo = locationInfo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START_DTTM", nullable = false, length = 19)
    public Date getStartDttm() {
        return this.startDttm;
    }

    public void setStartDttm(Date startDttm) {
        this.startDttm = startDttm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "END_DTTM", nullable = false, length = 19)
    public Date getEndDttm() {
        return this.endDttm;
    }

    public void setEndDttm(Date endDttm) {
        this.endDttm = endDttm;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "ICS_FILE_ID", nullable = false, length = 20)
    public String getIcsFileId() {
        return this.icsFileId;
    }

    public void setIcsFileId(String icsFileId) {
        this.icsFileId = icsFileId;
    }

    @Column(name = "SEND_ME_COPY", length = 1)
    public char getSendEmailCopy() {
        return sendEmailCopy;
    }

    public void setSendEmailCopy(char sendEmailCopy) {
        this.sendEmailCopy = sendEmailCopy;
    }

    @Column(name = "CANDIDATE_ALTERNATE_EMAIL_ID", length = 1000)
    public String getCandidateAlternateEmailId() {
        return this.candidateAlternateEmailId;
    }

    public void setCandidateAlternateEmailId(String candidateAlternateEmailId) {
        this.candidateAlternateEmailId = candidateAlternateEmailId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewSchedule")
    public Set<InterviewScheduleEmailLogMap> getInterviewScheduleEmailLogMaps() {
        return this.interviewScheduleEmailLogMaps;
    }

    public void setInterviewScheduleEmailLogMaps(Set<InterviewScheduleEmailLogMap> interviewScheduleEmailLogMaps) {
        this.interviewScheduleEmailLogMaps = interviewScheduleEmailLogMaps;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewSchedule")
    public Set<InterviewComments> getInterviewCommentses() {
        return this.interviewCommentses;
    }

    public void setInterviewCommentses(Set<InterviewComments> interviewCommentses) {
        this.interviewCommentses = interviewCommentses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewSchedule")
    public Set<InterviewFeedbackComments> getInterviewFeedbackCommentses() {
        return this.interviewFeedbackCommentses;
    }

    public void setInterviewFeedbackCommentses(Set<InterviewFeedbackComments> interviewFeedbackCommentses) {
        this.interviewFeedbackCommentses = interviewFeedbackCommentses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewSchedule")
    public Set<InterviewScheduleAttendee> getInterviewScheduleAttendees() {
        return this.interviewScheduleAttendees;
    }

    public void setInterviewScheduleAttendees(Set<InterviewScheduleAttendee> interviewScheduleAttendees) {
        this.interviewScheduleAttendees = interviewScheduleAttendees;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewSchedule")
    public Set<InterviewTask> getInterviewTasks() {
        return this.interviewTasks;
    }

    public void setInterviewTasks(Set<InterviewTask> interviewTasks) {
        this.interviewTasks = interviewTasks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewSchedule")
    public Set<InterviewFeedbackAnswers> getInterviewFeedbackAnswerses() {
        return this.interviewFeedbackAnswerses;
    }

    public void setInterviewFeedbackAnswerses(Set<InterviewFeedbackAnswers> interviewFeedbackAnswerses) {
        this.interviewFeedbackAnswerses = interviewFeedbackAnswerses;
    }

}