package com.ripplehire.candidate.entities;
// Generated 6 Mar, 2017 7:37:22 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InterviewFeedbackAnswers generated by hbm2java
 */
@Entity
@Table(name = "interview_feedback_answers")
public class InterviewFeedbackAnswers implements java.io.Serializable {

    private Integer interviewFeedbackAnswersSeq;
    private InterviewFeedbackQuestions interviewFeedbackQuestions;
    private InterviewSchedule interviewSchedule;
    private Interview interview;
    private int companyMstrSeq;
    private Integer feedbackRating;
    private char status;
    private int createdBy;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;

    public InterviewFeedbackAnswers() {
    }

    public InterviewFeedbackAnswers(InterviewFeedbackQuestions interviewFeedbackQuestions,
                                    Interview interview, Integer feedbackRating, int companyMstrSeq, char status, int createdBy, Date createDttm) {
        this.interviewFeedbackQuestions = interviewFeedbackQuestions;
        this.interview = interview;
        this.feedbackRating = feedbackRating;
        this.companyMstrSeq = companyMstrSeq;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
    }

    public InterviewFeedbackAnswers(InterviewFeedbackQuestions interviewFeedbackQuestions,
                                    Interview interview, int companyMstrSeq, Integer feedbackRating, char status, int createdBy,
                                    Date createDttm, Integer updatedBy, Date updateDttm) {
        this.interviewFeedbackQuestions = interviewFeedbackQuestions;
        this.interview = interview;
        this.companyMstrSeq = companyMstrSeq;
        this.feedbackRating = feedbackRating;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "INTERVIEW_FEEDBACK_ANSWERS_SEQ", unique = true, nullable = false)
    public Integer getInterviewFeedbackAnswersSeq() {
        return this.interviewFeedbackAnswersSeq;
    }

    public void setInterviewFeedbackAnswersSeq(Integer interviewFeedbackAnswersSeq) {
        this.interviewFeedbackAnswersSeq = interviewFeedbackAnswersSeq;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INTERVIEW_FEEDBACK_QUESTIONS_SEQ", nullable = false)
    public InterviewFeedbackQuestions getInterviewFeedbackQuestions() {
        return this.interviewFeedbackQuestions;
    }

    public void setInterviewFeedbackQuestions(InterviewFeedbackQuestions interviewFeedbackQuestions) {
        this.interviewFeedbackQuestions = interviewFeedbackQuestions;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INTERVIEW_SCHEDULE_SEQ", nullable = false)
    public InterviewSchedule getInterviewSchedule() {
        return this.interviewSchedule;
    }

    public void setInterviewSchedule(InterviewSchedule interviewSchedule) {
        this.interviewSchedule = interviewSchedule;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INTERVIEW_SEQ", nullable = false)
    public Interview getInterview() { return interview;	}

    public void setInterview(Interview interview) { this.interview = interview;	}

    @Column(name = "COMPANY_MSTR_SEQ", nullable = false)
    public int getCompanyMstrSeq() {
        return this.companyMstrSeq;
    }

    public void setCompanyMstrSeq(int companyMstrSeq) {
        this.companyMstrSeq = companyMstrSeq;
    }

    @Column(name = "FEEDBACK_RATING")
    public Integer getFeedbackRating() {
        return this.feedbackRating;
    }

    public void setFeedbackRating(Integer feedbackRating) {
        this.feedbackRating = feedbackRating;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DTTM", nullable = false, length = 19)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DTTM", length = 19)
    public Date getUpdateDttm() {
        return this.updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }

}
