package com.ripplehire.candidate.entities;
// Generated 14 Mar, 2017 7:29:51 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InterviewFeedbackComments generated by hbm2java
 */
@Entity
@Table(name = "interview_feedback_comments")
public class InterviewFeedbackComments implements java.io.Serializable {

	private Integer interviewFeedbackCommentSeq;
	private Integer companyMstrSeq;
	private Interviewer interviewer;
	private InterviewSchedule interviewSchedule;
	private Interview interview;
	private String feedbackComment;
	private String feedbackResult;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public InterviewFeedbackComments() {
	}

	public InterviewFeedbackComments(Integer companyMstrSeq, Interviewer interviewer, Interview interview, String feedbackComment, String feedbackResult, char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.interviewer = interviewer;
		this.interview = interview;
		this.feedbackComment = feedbackComment;
		this.feedbackResult = feedbackResult;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public InterviewFeedbackComments(Interviewer interviewer, Interview interview,
			String feedbackComment, String feedbackResult, char status, int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
		this.interviewer = interviewer;
		this.interview = interview;
		this.feedbackComment = feedbackComment;
		this.feedbackResult = feedbackResult;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "INTERVIEW_FEEDBACK_COMMENT_SEQ", unique = true, nullable = false)
	public Integer getInterviewFeedbackCommentSeq() {
		return this.interviewFeedbackCommentSeq;
	}

	public void setInterviewFeedbackCommentSeq(Integer interviewFeedbackCommentSeq) {
		this.interviewFeedbackCommentSeq = interviewFeedbackCommentSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INTERVIEWER_SEQ", nullable = false)
	public Interviewer getInterviewer() {
		return this.interviewer;
	}

	public void setInterviewer(Interviewer interviewer) {
		this.interviewer = interviewer;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public Integer getCompanyMstrSeq() {
		return companyMstrSeq;
	}

	public void setCompanyMstrSeq(Integer companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INTERVIEW_SCHEDULE_SEQ", nullable = false)
	public InterviewSchedule getInterviewSchedule() {
		return this.interviewSchedule;
	}

	public void setInterviewSchedule(InterviewSchedule interviewSchedule) {
		this.interviewSchedule = interviewSchedule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INTERVIEW_SEQ")
	public Interview getInterview() { 		return interview;	}

	public void setInterview(Interview interview) { 		this.interview = interview;	}

	@Column(name = "FEEDBACK_COMMENT", length = 1200)
	public String getFeedbackComment() {
		return this.feedbackComment;
	}

	public void setFeedbackComment(String feedbackComment) {
		this.feedbackComment = feedbackComment;
	}

	@Column(name = "FEEDBACK_RESULT", length = 50)
	public String getFeedbackResult() {
		return feedbackResult;
	}

	public void setFeedbackResult(String feedbackResult) {
		this.feedbackResult = feedbackResult;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
