package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InterviewSkillRating generated by hbm2java
 */
@Entity
@Table(name = "interview_skill_rating")
public class InterviewSkillRating implements java.io.Serializable {

	private Integer interviewSkillRatingSeq;
	private InterviewDetails interviewDetails;
	private int companyMstrSeq;
	private int skillCd;
	private String skillText;
	private int skillRating;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public InterviewSkillRating() {
	}

	public InterviewSkillRating(InterviewDetails interviewDetails,
			int companyMstrSeq, int skillCd, String skillText, int skillRating,
			char status, int createdBy, Date createDttm) {
		this.interviewDetails = interviewDetails;
		this.companyMstrSeq = companyMstrSeq;
		this.skillCd = skillCd;
		this.skillText = skillText;
		this.skillRating = skillRating;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public InterviewSkillRating(InterviewDetails interviewDetails,
			int companyMstrSeq, int skillCd, String skillText, int skillRating,
			char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm) {
		this.interviewDetails = interviewDetails;
		this.companyMstrSeq = companyMstrSeq;
		this.skillCd = skillCd;
		this.skillText = skillText;
		this.skillRating = skillRating;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "INTERVIEW_SKILL_RATING_SEQ", unique = true, nullable = false)
	public Integer getInterviewSkillRatingSeq() {
		return this.interviewSkillRatingSeq;
	}

	public void setInterviewSkillRatingSeq(Integer interviewSkillRatingSeq) {
		this.interviewSkillRatingSeq = interviewSkillRatingSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INTERVIEW_DETAIL_SEQ", nullable = false)
	public InterviewDetails getInterviewDetails() {
		return this.interviewDetails;
	}

	public void setInterviewDetails(InterviewDetails interviewDetails) {
		this.interviewDetails = interviewDetails;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "SKILL_CD", nullable = false)
	public int getSkillCd() {
		return this.skillCd;
	}

	public void setSkillCd(int skillCd) {
		this.skillCd = skillCd;
	}

	@Column(name = "SKILL_TEXT", nullable = false, length = 100)
	public String getSkillText() {
		return this.skillText;
	}

	public void setSkillText(String skillText) {
		this.skillText = skillText;
	}

	@Column(name = "SKILL_RATING", nullable = false)
	public int getSkillRating() {
		return this.skillRating;
	}

	public void setSkillRating(int skillRating) {
		this.skillRating = skillRating;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
