package com.ripplehire.candidate.entities;
// Generated 30 Mar, 2017 11:21:44 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InterviewReviewTask generated by hbm2java
 */
@Entity
@Table(name = "interview_review_task")
public class InterviewReviewTask implements java.io.Serializable {

	private Integer interviewReviewTaskSeq;
	private InterviewReview interviewReview;
	private Interviewer interviewer;
	private TaskDetails taskDetails;
	private int companyMstrSeq;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatebBy;
	private Date updateDttm;

	public InterviewReviewTask() {
	}

	public InterviewReviewTask(InterviewReview interviewReview, Interviewer interviewer, TaskDetails taskDetails,
			int companyMstrSeq, char status, int createdBy, Date createDttm) {
		this.interviewReview = interviewReview;
		this.interviewer = interviewer;
		this.taskDetails = taskDetails;
		this.companyMstrSeq = companyMstrSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public InterviewReviewTask(InterviewReview interviewReview, Interviewer interviewer, TaskDetails taskDetails,
			int companyMstrSeq, char status, int createdBy, Date createDttm, Integer updatebBy, Date updateDttm) {
		this.interviewReview = interviewReview;
		this.interviewer = interviewer;
		this.taskDetails = taskDetails;
		this.companyMstrSeq = companyMstrSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatebBy = updatebBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "INTERVIEW_REVIEW_TASK_SEQ", unique = true, nullable = false)
	public Integer getInterviewReviewTaskSeq() {
		return this.interviewReviewTaskSeq;
	}

	public void setInterviewReviewTaskSeq(Integer interviewReviewTaskSeq) {
		this.interviewReviewTaskSeq = interviewReviewTaskSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INTERVIEW_REVIEW_SEQ", nullable = false)
	public InterviewReview getInterviewReview() {
		return this.interviewReview;
	}

	public void setInterviewReview(InterviewReview interviewReview) {
		this.interviewReview = interviewReview;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INTERVIEWER_SEQ", nullable = false)
	public Interviewer getInterviewer() {
		return this.interviewer;
	}

	public void setInterviewer(Interviewer interviewer) {
		this.interviewer = interviewer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TASK_DETAILS_SEQ", nullable = false)
	public TaskDetails getTaskDetails() {
		return this.taskDetails;
	}

	public void setTaskDetails(TaskDetails taskDetails) {
		this.taskDetails = taskDetails;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATEB_BY")
	public Integer getUpdatebBy() {
		return this.updatebBy;
	}

	public void setUpdatebBy(Integer updatebBy) {
		this.updatebBy = updatebBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
