package com.ripplehire.candidate.entities;
// Generated 6 Mar, 2017 7:37:22 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InterviewFeedbackQuestions generated by hbm2java
 */
@Entity
@Table(name = "interview_feedback_questions")
public class InterviewFeedbackQuestions implements java.io.Serializable {

    private Integer interviewFeedbackQuestionsSeq;
    private int companyMstrSeq;
    private String topicDetails;
    private String guidelines;
    private Integer priority;
    private String isRequired;
    private String topicStatus;
    private String interviewType;
    private char status;
    private int createdBy;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;
    private Set<InterviewFeedbackAnswers> interviewFeedbackAnswerses = new HashSet<InterviewFeedbackAnswers>(0);
    private Set<InterviewKitQuestion> interviewKitQuestions = new HashSet<InterviewKitQuestion>(0);


    public InterviewFeedbackQuestions() {
    }

    public InterviewFeedbackQuestions(int companyMstrSeq, String topicDetails, String guidelines, String isRequired,
                                      String topicStatus, String interviewType, char status, int createdBy, Date createDttm) {
        this.companyMstrSeq = companyMstrSeq;
        this.topicDetails = topicDetails;
        this.guidelines = guidelines;
        this.isRequired = isRequired;
        this.topicStatus = topicStatus;
        this.interviewType = interviewType;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
    }

    public InterviewFeedbackQuestions(Integer interviewFeedbackQuestionsSeq, int companyMstrSeq, String topicDetails, String guidelines, Integer priority, String isRequired, String topicStatus, String interviewType, char status, int createdBy, Date createDttm, Integer updatedBy, Date updateDttm, Set<InterviewFeedbackAnswers> interviewFeedbackAnswerses, Set<InterviewKitQuestion> interviewKitQuestions) {
        this.interviewFeedbackQuestionsSeq = interviewFeedbackQuestionsSeq;
        this.companyMstrSeq = companyMstrSeq;
        this.topicDetails = topicDetails;
        this.guidelines = guidelines;
        this.priority = priority;
        this.isRequired = isRequired;
        this.topicStatus = topicStatus;
        this.interviewType = interviewType;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
        this.interviewFeedbackAnswerses = interviewFeedbackAnswerses;
        this.interviewKitQuestions = interviewKitQuestions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "INTERVIEW_FEEDBACK_QUESTIONS_SEQ", unique = true, nullable = false)
    public Integer getInterviewFeedbackQuestionsSeq() {
        return this.interviewFeedbackQuestionsSeq;
    }

    public void setInterviewFeedbackQuestionsSeq(Integer interviewFeedbackQuestionsSeq) {
        this.interviewFeedbackQuestionsSeq = interviewFeedbackQuestionsSeq;
    }

    @Column(name = "COMPANY_MSTR_SEQ", nullable = false)
    public int getCompanyMstrSeq() {
        return this.companyMstrSeq;
    }

    public void setCompanyMstrSeq(int companyMstrSeq) {
        this.companyMstrSeq = companyMstrSeq;
    }

    @Column(name = "TOPIC_DETAILS", nullable = false, length = 300)
    public String getTopicDetails() {
        return this.topicDetails;
    }

    public void setTopicDetails(String topicDetails) {
        this.topicDetails = topicDetails;
    }

    @Column(name = "GUIDELINES", nullable = false)
    public String getGuidelines() {
        return this.guidelines;
    }

    public void setGuidelines(String guidelines) {
        this.guidelines = guidelines;
    }

    @Column(name = "PRIORITY")
    public Integer getPriority() {
        return this.priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    @Column(name = "IS_REQUIRED", nullable = false, length = 2)
    public String getIsRequired() {
        return this.isRequired;
    }

    public void setIsRequired(String isRequired) {
        this.isRequired = isRequired;
    }

    @Column(name = "TOPIC_STATUS", nullable = false, length = 50)
    public String getTopicStatus() {
        return this.topicStatus;
    }

    public void setTopicStatus(String topicStatus) {
        this.topicStatus = topicStatus;
    }

    @Column(name = "INTERVIEW_TYPE", nullable = false, length = 50)
    public String getInterviewType() {
        return this.interviewType;
    }

    public void setInterviewType(String interviewType) {
        this.interviewType = interviewType;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DTTM", nullable = false, length = 19)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DTTM", length = 19)
    public Date getUpdateDttm() {
        return this.updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewFeedbackQuestions")
    public Set<InterviewFeedbackAnswers> getInterviewFeedbackAnswerses() {
        return this.interviewFeedbackAnswerses;
    }

    public void setInterviewFeedbackAnswerses(Set<InterviewFeedbackAnswers> interviewFeedbackAnswerses) {
        this.interviewFeedbackAnswerses = interviewFeedbackAnswerses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "interviewFeedbackQuestions")
    public Set<InterviewKitQuestion> getInterviewKitQuestions() {
        return interviewKitQuestions;
    }

    public void setInterviewKitQuestions(Set<InterviewKitQuestion> interviewKitQuestions) {
        this.interviewKitQuestions = interviewKitQuestions;
    }
}
