package com.ripplehire.candidate.entities;
// Generated 16 May, 2017 1:27:45 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobApprovalDetails generated by hbm2java
 */
@Entity
@Table(name = "job_approval_details")
public class JobApprovalDetails implements java.io.Serializable {

	private Integer jobApprovalDetailsSeq;
	private Job job;
	private UserProfile userProfile;
	private int companyMstrSeq;
	private int level;
	private String shiftStatus;
	private String action;
	private String reason;
	private String comments;
	private Character status;
	private int createdBy;
	private Date createdDttm;
	private Integer updateBy;
	private Date updateDttm;

	public JobApprovalDetails() {
	}

	public JobApprovalDetails(Job job, int companyMstrSeq, int level, String shiftStatus, String action, String reason,
			String comments, int createdBy, Date createdDttm) {
		this.job = job;
		this.companyMstrSeq = companyMstrSeq;
		this.level = level;
		this.shiftStatus = shiftStatus;
		this.action = action;
		this.reason = reason;
		this.comments = comments;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public JobApprovalDetails(Job job, UserProfile userProfile, int companyMstrSeq, int level, String shiftStatus,
			String action, String reason, String comments, Character status, int createdBy, Date createdDttm, Integer updateBy,
			Date updateDttm) {
		this.job = job;
		this.userProfile = userProfile;
		this.companyMstrSeq = companyMstrSeq;
		this.level = level;
		this.shiftStatus = shiftStatus;
		this.action = action;
		this.reason = reason;
		this.comments = comments;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updateBy = updateBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "JOB_APPROVAL_DETAILS_SEQ", unique = true, nullable = false)
	public Integer getJobApprovalDetailsSeq() {
		return this.jobApprovalDetailsSeq;
	}

	public void setJobApprovalDetailsSeq(Integer jobApprovalDetailsSeq) {
		this.jobApprovalDetailsSeq = jobApprovalDetailsSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_SEQ", nullable = false)
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PROFILE_SEQ")
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "LEVEL", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	@Column(name = "SHIFT_STATUS", nullable = false, length = 20)
	public String getShiftStatus() {
		return this.shiftStatus;
	}

	public void setShiftStatus(String shiftStatus) {
		this.shiftStatus = shiftStatus;
	}

	@Column(name = "ACTION", length = 20)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "REASON", length = 300)
	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "COMMENTS", length = 500)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATE_BY")
	public Integer getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
