package com.ripplehire.candidate.entities;
// Generated 16 May, 2017 1:27:45 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobApprover generated by hbm2java
 */
@Entity
@Table(name = "job_approver")
public class JobApprover implements java.io.Serializable {

	private Integer jobApproverSeq;
	private Job job;
	private UserGroup userGroup;
	private UserProfile userProfile;
	private int companyMstrSeq;
	private String type;
	private int level;
	private Character status;
	private int createdBy;
	private Date createdDttm;
	private Integer updateBy;
	private Date updateDttm;

	public JobApprover() {
	}

	public JobApprover(Job job, int companyMstrSeq, String type, int level, int createdBy, Date createdDttm) {
		this.job = job;
		this.companyMstrSeq = companyMstrSeq;
		this.type = type;
		this.level = level;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public JobApprover(Job job, UserGroup userGroup, UserProfile userProfile, int companyMstrSeq, String type,
			int level, Character status, int createdBy, Date createdDttm, Integer updateBy, Date updateDttm) {
		this.job = job;
		this.userGroup = userGroup;
		this.userProfile = userProfile;
		this.companyMstrSeq = companyMstrSeq;
		this.type = type;
		this.level = level;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updateBy = updateBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "JOB_APPROVER_SEQ", unique = true, nullable = false)
	public Integer getJobApproverSeq() {
		return this.jobApproverSeq;
	}

	public void setJobApproverSeq(Integer jobApproverSeq) {
		this.jobApproverSeq = jobApproverSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_SEQ", nullable = false)
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_GROUP_SEQ")
	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PROFILE_SEQ")
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "TYPE", nullable = false, length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "LEVEL", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATE_BY")
	public Integer getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
