package com.ripplehire.candidate.entities;
// Generated 26 Apr, 2017 3:05:58 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobDetail generated by hbm2java
 */
@Entity
@Table(name = "job_detail")
public class JobDetail implements java.io.Serializable {

	private Integer jobDetailSeq;
	private UserProfile userProfileByRecruitingLead;
	private CurrencyMstr currencyMstr;
	private UserProfile userProfileBySourcingLead;
	private UserProfile userProfileByHiringManager;
	private int companyMstrSeq;
	private String department;
	private String client;
	private String jobLevel;
	private String skillType;
	private Integer hiringDeadline;
	private String primarySkills;
	private String secondarySkills;
	private String custom1;
	private String custom2;
	private String custom3;
	private String custom4;
	private String custom5;
	private String custom6;
	private String custom7;
	private String custom8;
	private String custom9;
	private String custom10;
	private String custom11;
	private String custom12;
	private String custom13;
	private String custom14;
	private String custom15;
    private String custom16;
    private String custom17;
    private String custom18;
    private String custom19;
    private String custom20;
	private String jobRequestType;
	private Character budgetAllocated;
	private Integer budgetAnnum;
	private Date joiningDeadline;
	private char status;
	private int createdBy;
	private Date createdDttm;
	private Integer updatedBy;
	private Date updatedDttm;
	private Date requestDate;
	private Date recruitmentStartDate;
	private String origDept;
	private String country;
	private String withdrawReason;

	public JobDetail() {
	}

	public JobDetail(int companyMstrSeq, char status, int createdBy, Date createdDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public JobDetail(UserProfile userProfileByRecruitingLead, CurrencyMstr currencyMstr,
					 UserProfile userProfileBySourcingLead, UserProfile userProfileByHiringManager, int companyMstrSeq,
					 String department, String client, String jobLevel, String skillType, Integer hiringDeadline,
					 String primarySkills, String secondarySkills, String custom1, String custom2, String custom3,
					 String custom4, String custom5, String custom6, String custom7, String custom8, String custom9,
					 String custom10, String jobRequestType, Character budgetAllocated, Integer budgetAnnum,
					 Date joiningDeadline, char status, int createdBy, Date createdDttm, Integer updatedBy, Date updatedDttm,
					 Date requestDate, Date recruitmentStartDate, String origDept, String country, String withdrawReason) {
		this.userProfileByRecruitingLead = userProfileByRecruitingLead;
		this.currencyMstr = currencyMstr;
		this.userProfileBySourcingLead = userProfileBySourcingLead;
		this.userProfileByHiringManager = userProfileByHiringManager;
		this.companyMstrSeq = companyMstrSeq;
		this.department = department;
		this.client = client;
		this.jobLevel = jobLevel;
		this.skillType = skillType;
		this.hiringDeadline = hiringDeadline;
		this.primarySkills = primarySkills;
		this.secondarySkills = secondarySkills;
		this.custom1 = custom1;
		this.custom2 = custom2;
		this.custom3 = custom3;
		this.custom4 = custom4;
		this.custom5 = custom5;
		this.custom6 = custom6;
		this.custom7 = custom7;
		this.custom8 = custom8;
		this.custom9 = custom9;
		this.custom10 = custom10;
		this.jobRequestType = jobRequestType;
		this.budgetAllocated = budgetAllocated;
		this.budgetAnnum = budgetAnnum;
		this.joiningDeadline = joiningDeadline;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
		this.requestDate = requestDate;
		this.recruitmentStartDate = recruitmentStartDate;
		this.origDept = origDept;
		this.country = country;
		this.withdrawReason = withdrawReason;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "JOB_DETAIL_SEQ", unique = true, nullable = false)
	public Integer getJobDetailSeq() {
		return this.jobDetailSeq;
	}

	public void setJobDetailSeq(Integer jobDetailSeq) {
		this.jobDetailSeq = jobDetailSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RECRUITING_LEAD")
	public UserProfile getUserProfileByRecruitingLead() {
		return this.userProfileByRecruitingLead;
	}

	public void setUserProfileByRecruitingLead(UserProfile userProfileByRecruitingLead) {
		this.userProfileByRecruitingLead = userProfileByRecruitingLead;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CURRENCY_MSTR_SEQ")
	public CurrencyMstr getCurrencyMstr() {
		return this.currencyMstr;
	}

	public void setCurrencyMstr(CurrencyMstr currencyMstr) {
		this.currencyMstr = currencyMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOURCING_LEAD")
	public UserProfile getUserProfileBySourcingLead() {
		return this.userProfileBySourcingLead;
	}

	public void setUserProfileBySourcingLead(UserProfile userProfileBySourcingLead) {
		this.userProfileBySourcingLead = userProfileBySourcingLead;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "HIRING_MANAGER")
	public UserProfile getUserProfileByHiringManager() {
		return this.userProfileByHiringManager;
	}

	public void setUserProfileByHiringManager(UserProfile userProfileByHiringManager) {
		this.userProfileByHiringManager = userProfileByHiringManager;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "DEPARTMENT", length = 100)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "CLIENT", length = 100)
	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	@Column(name = "JOB_LEVEL", length = 20)
	public String getJobLevel() {
		return this.jobLevel;
	}

	public void setJobLevel(String jobLevel) {
		this.jobLevel = jobLevel;
	}

	@Column(name = "SKILL_TYPE", length = 100)
	public String getSkillType() {
		return this.skillType;
	}

	public void setSkillType(String skillType) {
		this.skillType = skillType;
	}

	@Column(name = "HIRING_DEADLINE")
	public Integer getHiringDeadline() {
		return this.hiringDeadline;
	}

	public void setHiringDeadline(Integer hiringDeadline) {
		this.hiringDeadline = hiringDeadline;
	}

	@Column(name = "PRIMARY_SKILLS", length = 200)
	public String getPrimarySkills() {
		return this.primarySkills;
	}

	public void setPrimarySkills(String primarySkills) {
		this.primarySkills = primarySkills;
	}

	@Column(name = "SECONDARY_SKILLS", length = 200)
	public String getSecondarySkills() {
		return this.secondarySkills;
	}

	public void setSecondarySkills(String secondarySkills) {
		this.secondarySkills = secondarySkills;
	}

	@Column(name = "CUSTOM1", length = 500)
	public String getCustom1() {
		return this.custom1;
	}

	public void setCustom1(String custom1) {
		this.custom1 = custom1;
	}

	@Column(name = "CUSTOM2", length = 500)
	public String getCustom2() {
		return this.custom2;
	}

	public void setCustom2(String custom2) {
		this.custom2 = custom2;
	}

	@Column(name = "CUSTOM3", length = 500)
	public String getCustom3() {
		return this.custom3;
	}

	public void setCustom3(String custom3) {
		this.custom3 = custom3;
	}

	@Column(name = "CUSTOM4", length = 500)
	public String getCustom4() {
		return this.custom4;
	}

	public void setCustom4(String custom4) {
		this.custom4 = custom4;
	}

	@Column(name = "CUSTOM5", length = 500)
	public String getCustom5() {
		return this.custom5;
	}

	public void setCustom5(String custom5) {
		this.custom5 = custom5;
	}

	@Column(name = "CUSTOM6", length = 500)
	public String getCustom6() {
		return this.custom6;
	}

	public void setCustom6(String custom6) {
		this.custom6 = custom6;
	}

	@Column(name = "CUSTOM7", length = 500)
	public String getCustom7() {
		return this.custom7;
	}

	public void setCustom7(String custom7) {
		this.custom7 = custom7;
	}

	@Column(name = "CUSTOM8", length = 500)
	public String getCustom8() {
		return this.custom8;
	}

	public void setCustom8(String custom8) {
		this.custom8 = custom8;
	}

	@Column(name = "CUSTOM9", length = 500)
	public String getCustom9() {
		return this.custom9;
	}

	public void setCustom9(String custom9) {
		this.custom9 = custom9;
	}

	@Column(name = "CUSTOM10", length = 500)
	public String getCustom10() {
		return this.custom10;
	}

	public void setCustom10(String custom10) {
		this.custom10 = custom10;
	}

	@Column(name = "CUSTOM11", length = 500)
	public String getCustom11() {
		return this.custom11;
	}

	public void setCustom11(String custom11) {
		this.custom11 = custom11;
	}

	@Column(name = "CUSTOM12", length = 500)
	public String getCustom12() {
		return this.custom12;
	}

	public void setCustom12(String custom12) {
		this.custom12 = custom12;
	}

	@Column(name = "CUSTOM13", length = 500)
	public String getCustom13() {
		return this.custom13;
	}

	public void setCustom13(String custom13) {
		this.custom13 = custom13;
	}

	@Column(name = "CUSTOM14", length = 500)
	public String getCustom14() {
		return this.custom14;
	}

	public void setCustom14(String custom14) {
		this.custom14 = custom14;
	}

	@Column(name = "CUSTOM15", length = 500)
	public String getCustom15() {
		return this.custom15;
	}

	public void setCustom15(String custom15) {
		this.custom15 = custom15;
	}


	@Column(name = "JOB_REQUEST_TYPE", length = 100)
	public String getJobRequestType() {
		return this.jobRequestType;
	}

	public void setJobRequestType(String jobRequestType) {
		this.jobRequestType = jobRequestType;
	}

	@Column(name = "BUDGET_ALLOCATED", length = 1)
	public Character getBudgetAllocated() {
		return this.budgetAllocated;
	}

	public void setBudgetAllocated(Character budgetAllocated) {
		this.budgetAllocated = budgetAllocated;
	}

	@Column(name = "BUDGET_ANNUM")
	public Integer getBudgetAnnum() {
		return this.budgetAnnum;
	}

	public void setBudgetAnnum(Integer budgetAnnum) {
		this.budgetAnnum = budgetAnnum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOINING_DEADLINE", length = 19)
	public Date getJoiningDeadline() {
		return this.joiningDeadline;
	}

	public void setJoiningDeadline(Date joiningDeadline) {
		this.joiningDeadline = joiningDeadline;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQUEST_DATE", length = 19)
	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECRUITMENT_START_DATE", length = 19)
	public Date getRecruitmentStartDate() {
		return this.recruitmentStartDate;
	}

	public void setRecruitmentStartDate(Date recruitmentStartDate) {
		this.recruitmentStartDate = recruitmentStartDate;
	}

	@Column(name = "orig_dept", length = 50)
	public String getOrigDept() {
		return this.origDept;
	}

	public void setOrigDept(String origDept) {
		this.origDept = origDept;
	}

	@Column(name = "COUNTRY", length = 200)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "WITHDRAW_REASON", length = 200)
	public String getWithdrawReason() {
		return withdrawReason;
	}

	public void setWithdrawReason(String withdrawReason) {
		this.withdrawReason = withdrawReason;
	}

	@Column(name = "CUSTOM16", length = 500)
	public String getCustom16() {
		return custom16;
	}

	public void setCustom16(String custom16) {
		this.custom16 = custom16;
	}

	@Column(name = "CUSTOM17", length = 500)
	public String getCustom17() {
		return custom17;
	}

	public void setCustom17(String custom17) {
		this.custom17 = custom17;
	}

	@Column(name = "CUSTOM18", length = 500)
	public String getCustom18() {
		return custom18;
	}

	public void setCustom18(String custom18) {
		this.custom18 = custom18;
	}

	@Column(name = "CUSTOM19", length = 500)
	public String getCustom19() {
		return custom19;
	}

	public void setCustom19(String custom19) {
		this.custom19 = custom19;
	}

	@Column(name = "CUSTOM20", length = 500)
	public String getCustom20() {
		return custom20;
	}

	public void setCustom20(String custom20) {
		this.custom20 = custom20;
	}
}