package com.ripplehire.candidate.entities;
// Generated Feb 9, 2016 6:38:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobFormField generated by hbm2java
 */
@Entity
@Table(name = "job_form_field")
/*Temporary change for code implementation. Plz Revert back the name before deploying.*/
public class JobFormField implements java.io.Serializable {

	private Integer jobFormFieldsSeq;
	private int companyMstrSeq;
	private String fieldLabel;
	private String fieldName;
	private String fieldPlaceholder;
	private String fieldType;
	private Character fieldRequired;
	private String fieldClass;
	private String groupClass;
	private String fieldInputClass;
	private String fieldPostText;
	private String fieldInfoText;
	private Integer fieldMaxLength;
	private String fieldTable;
	private String fieldJobRole;
	private String fieldFetchType;
	private Integer colSize;
	private String fieldGroup;
	private String fieldSubGroup;
	private Integer editPriority;
	private Integer exportPriority;
	private String viewGroup;
	private String viewSubGroup;
	private Integer viewPriority;
	private Character isEditable;
	private Character isOverridable;
	private String fieldExport;
	private Character status;
	private Character requestField;
	private Character requestRequired;
	private Character requestEditable;
	private Character isApiField;
	private int createdBy;
	private Date createdDttm;
	private Integer updateBy;
	private Date updateDttm;

	public JobFormField() {
	}

	public JobFormField(int companyMstrSeq, int createdBy, Date createdDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public JobFormField(String fieldLabel, String fieldName, String fieldPlaceholder, String fieldType, Character fieldRequired,
						String fieldClass, String groupClass, String fieldInputClass, String fieldPostText, String fieldInfoText, Integer fieldMaxLength, String fieldTable,
						String fieldJobRole, String fieldFetchType, Integer colSize, String fieldGroup, String fieldSubGroup, Integer editPriority, Integer exportPriority,
						String viewGroup, String viewSubGroup, Integer viewPriority, Character isEditable, Character isOverridable, String fieldExport,
						Character requestField, Character requestRequired, Character requestEditable, Character isApiField) {
		this.fieldLabel = fieldLabel;
		this.fieldName = fieldName;
		this.fieldPlaceholder = fieldPlaceholder;
		this.fieldType = fieldType;
		this.fieldRequired = fieldRequired;
		this.fieldClass = fieldClass;
		this.groupClass = groupClass;
		this.fieldInputClass = fieldInputClass;
		this.fieldPostText = fieldPostText;
		this.fieldInfoText = fieldInfoText;
		this.fieldMaxLength = fieldMaxLength;
		this.fieldTable = fieldTable;
		this.fieldJobRole = fieldJobRole;
		this.fieldFetchType = fieldFetchType;
		this.colSize = colSize;
		this.fieldGroup = fieldGroup;
		this.fieldSubGroup = fieldSubGroup;
		this.editPriority = editPriority;
		this.exportPriority = exportPriority;
		this.viewGroup = viewGroup;
		this.viewSubGroup = viewSubGroup;
		this.viewPriority = viewPriority;
		this.isEditable = isEditable;
		this.isOverridable = isOverridable;
		this.isApiField = isApiField;
		this.fieldExport = fieldExport;
		this.requestField = requestField;
		this.requestRequired = requestRequired;
		this.requestEditable = requestEditable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "JOB_FORM_FIELDS_SEQ", unique = true, nullable = false)
	public Integer getJobFormFieldsSeq() {
		return this.jobFormFieldsSeq;
	}

	public void setJobFormFieldsSeq(Integer jobFormFieldsSeq) {
		this.jobFormFieldsSeq = jobFormFieldsSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "FIELD_LABEL", length = 100)
	public String getFieldLabel() {
		return this.fieldLabel;
	}

	public void setFieldLabel(String fieldLabel) {
		this.fieldLabel = fieldLabel;
	}

	@Column(name = "FIELD_NAME", length = 100)
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "FIELD_PLACEHOLDER", length = 100)
	public String getFieldPlaceholder() {
		return this.fieldPlaceholder;
	}

	public void setFieldPlaceholder(String fieldPlaceholder) {
		this.fieldPlaceholder = fieldPlaceholder;
	}

	@Column(name = "FIELD_TYPE", length = 50)
	public String getFieldType() {
		return this.fieldType;
	}

	public void setFieldType(String fieldType) {
		this.fieldType = fieldType;
	}

	@Column(name = "FIELD_REQUIRED", length = 1)
	public Character getFieldRequired() {
		return this.fieldRequired;
	}

	public void setFieldRequired(Character fieldRequired) {
		this.fieldRequired = fieldRequired;
	}

	@Column(name = "FIELD_CLASS", length = 50)
	public String getFieldClass() {
		return this.fieldClass;
	}

	public void setFieldClass(String fieldClass) {
		this.fieldClass = fieldClass;
	}

	@Column(name = "GROUP_CLASS", length = 50)
	public String getGroupClass() {
		return this.groupClass;
	}

	public void setGroupClass(String groupClass) {
		this.groupClass = groupClass;
	}

	@Column(name = "FIELD_INPUT_CLASS", length = 50)
	public String getFieldInputClass() {
		return this.fieldInputClass;
	}

	public void setFieldInputClass(String fieldInputClass) {
		this.fieldInputClass = fieldInputClass;
	}

	@Column(name = "FIELD_POST_TEXT", length = 10)
	public String getFieldPostText() {
		return this.fieldPostText;
	}

	public void setFieldPostText(String fieldPostText) {
		this.fieldPostText = fieldPostText;
	}

	@Column(name = "FIELD_INFO_TEXT", length = 200)
	public String getFieldInfoText() {
		return this.fieldInfoText;
	}

	public void setFieldInfoText(String fieldInfoText) {
		this.fieldInfoText = fieldInfoText;
	}

	@Column(name = "FIELD_MAX_LENGTH")
	public Integer getFieldMaxLength() {
		return this.fieldMaxLength;
	}

	public void setFieldMaxLength(Integer fieldMaxLength) {
		this.fieldMaxLength = fieldMaxLength;
	}

	@Column(name = "FIELD_TABLE", length = 50)
	public String getFieldTable() {
		return this.fieldTable;
	}

	public void setFieldTable(String fieldTable) {
		this.fieldTable = fieldTable;
	}

	@Column(name = "FIELD_JOB_ROLE", length = 50)
	public String getFieldJobRole() {
		return this.fieldJobRole;
	}

	public void setFieldJobRole(String fieldJobRole) {
		this.fieldJobRole = fieldJobRole;
	}

	@Column(name = "COL_SIZE")
	public Integer getColSize() {
		return this.colSize;
	}

	public void setColSize(Integer colSize) {
		this.colSize = colSize;
	}

	@Column(name = "FIELD_GROUP", length = 50)
	public String getFieldGroup() {
		return this.fieldGroup;
	}

	public void setFieldGroup(String fieldGroup) {
		this.fieldGroup = fieldGroup;
	}

	@Column(name = "FIELD_SUB_GROUP", length = 50)
	public String getFieldSubGroup() {
		return this.fieldSubGroup;
	}

	public void setFieldSubGroup(String fieldSubGroup) {
		this.fieldSubGroup = fieldSubGroup;
	}

	@Column(name = "EDIT_PRIORITY")
	public Integer getEditPriority() {
		return this.editPriority;
	}

	public void setEditPriority(Integer editPriority) {
		this.editPriority = editPriority;
	}

	@Column(name = "EXPORT_PRIORITY")
	public Integer getExportPriority() {
		return this.exportPriority;
	}

	public void setExportPriority(Integer exportPriority) {
		this.exportPriority = exportPriority;
	}

	@Column(name = "VIEW_GROUP", length = 50)
	public String getViewGroup() {
		return viewGroup;
	}

	public void setViewGroup(String viewGroup) {
		this.viewGroup = viewGroup;
	}

	@Column(name = "VIEW_SUB_GROUP", length = 50)
	public String getViewSubGroup() {
		return viewSubGroup;
	}

	public void setViewSubGroup(String viewSubGroup) {
		this.viewSubGroup = viewSubGroup;
	}

	@Column(name = "VIEW_PRIORITY")
	public Integer getViewPriority() {
		return viewPriority;
	}

	public void setViewPriority(Integer viewPriority) {
		this.viewPriority = viewPriority;
	}

	@Column(name = "IS_EDITABLE",nullable = false, length = 1)
	public Character getIsEditable() {
		return this.isEditable;
	}

	public void setIsEditable(Character isEditable) {
		this.isEditable = isEditable;
	}

	@Column(name = "IS_OVERRIDABLE",nullable = true, length = 1)
	public Character getIsOverridable() {
		return isOverridable;
	}

	public void setIsOverridable(Character isOverridable) {
		this.isOverridable = isOverridable;
	}

	@Column(name = "IS_API_FIELD",nullable = false, length = 1)
	public Character getIsApiField() {
		return isApiField;
	}

	public void setIsApiField(Character isApiField) {
		this.isApiField = isApiField;
	}

	@Column(name = "FIELD_EXPORT", length = 50)
	public String getFieldExport() {
		return fieldExport;
	}

	public void setFieldExport(String fieldExport) {
		this.fieldExport = fieldExport;
	}

	@Column(name = "HM_FIELD",nullable = false, length = 1)
	public Character getRequestField() {
		return requestField;
	}

	public void setRequestField(Character requestField) {
		this.requestField = requestField;
	}

	@Column(name = "HM_REQUIRED",nullable = false, length = 1)
	public Character getRequestRequired() {
		return requestRequired;
	}

	public void setRequestRequired(Character requestRequired) {
		this.requestRequired = requestRequired;
	}

	@Column(name = "HM_EDITABLE",nullable = false, length = 1)
	public Character getRequestEditable() {
		return requestEditable;
	}

	public void setRequestEditable(Character requestEditable) {
		this.requestEditable = requestEditable;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATE_BY")
	public Integer getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@Column(name = "FIELD_FETCH_TYPE", length = 50)
	public String getFieldFetchType() {
		return fieldFetchType;
	}

	public void setFieldFetchType(String fieldFetchType) {
		this.fieldFetchType = fieldFetchType;
	}
}
