package com.ripplehire.candidate.entities;
// Generated 18 Apr, 2017 2:55:35 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobHistory generated by hbm2java
 */
@Entity
@Table(name = "job_history")
public class JobHistory implements java.io.Serializable {

	private Integer jobHistorySeq;
	private JobStatusMstr jobStatusMstr;
	private Job job;
	private int companyMstrSeq;
	private String action;
	private String jobStatus;
	private int jobOpenings;
	private String comment;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<JobAudit> jobAudits = new HashSet<JobAudit>(0);

	public JobHistory() {
	}

	public JobHistory(JobStatusMstr jobStatusMstr, Job job, int companyMstrSeq, String action, String jobStatus,
					  int jobOpenings, String comment, char status, int createdBy, Date createDttm, Integer updatedBy,
					  Date updateDttm, Set<JobAudit> jobAudits) {
		this.jobStatusMstr = jobStatusMstr;
		this.job = job;
		this.companyMstrSeq = companyMstrSeq;
		this.action = action;
		this.jobStatus = jobStatus;
		this.jobOpenings = jobOpenings;
		this.comment = comment;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.jobAudits = jobAudits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "JOB_HISTORY_SEQ", unique = true, nullable = false)
	public Integer getJobHistorySeq() {
		return this.jobHistorySeq;
	}

	public void setJobHistorySeq(Integer jobHistorySeq) {
		this.jobHistorySeq = jobHistorySeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_STATUS_SEQ")
	public JobStatusMstr getJobStatusMstr() {
		return this.jobStatusMstr;
	}

	public void setJobStatusMstr(JobStatusMstr jobStatusMstr) {
		this.jobStatusMstr = jobStatusMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_SEQ", nullable = false)
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "ACTION", length = 50)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "JOB_STATUS", length = 50)
	public String getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	@Column(name = "JOB_OPENINGS", nullable = false)
	public int getJobOpenings() {
		return this.jobOpenings;
	}

	public void setJobOpenings(int jobOpenings) {
		this.jobOpenings = jobOpenings;
	}

	@Column(name = "comment", length = 100)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobHistory")
	public Set<JobAudit> getJobAudits() {
		return this.jobAudits;
	}

	public void setJobAudits(Set<JobAudit> jobAudits) {
		this.jobAudits = jobAudits;
	}

}