package com.ripplehire.candidate.entities;

// Generated Aug 26, 2014 7:46:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobLevelConfig generated by hbm2java
 */
@Entity
@Table(name = "job_level_config")
public class JobLevelConfig implements java.io.Serializable {

	private Integer jobLevelConfigSeq;
	private int companyMstrSeq;
	private String jobLevelCode;
	private Integer maxExpYears;
	private Integer maxExpMonths;
	private Integer minExpYears;
	private Integer minExpMonths;
	private Integer jobLevelReward;
	private Integer jobLevelPoints;
	private String jobRewardBand;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public JobLevelConfig() {
	}

	public JobLevelConfig(int companyMstrSeq, String jobLevelCode, char status,
			int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.jobLevelCode = jobLevelCode;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public JobLevelConfig(int companyMstrSeq, String jobLevelCode,
			Integer maxExpYears, Integer maxExpMonths, Integer minExpYears, Integer minExpMonths, Integer jobLevelReward,
			Integer jobLevelPoints, String jobRewardBand, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.jobLevelCode = jobLevelCode;
		this.maxExpYears = maxExpYears;
		this.maxExpMonths = maxExpMonths;
		this.minExpYears = minExpYears;
		this.minExpMonths = minExpMonths;
		this.jobLevelReward = jobLevelReward;
		this.jobLevelPoints = jobLevelPoints;
		this.jobRewardBand = jobRewardBand;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "JOB_LEVEL_CONFIG_SEQ", unique = true, nullable = false)
	public Integer getJobLevelConfigSeq() {
		return this.jobLevelConfigSeq;
	}

	public void setJobLevelConfigSeq(Integer jobLevelConfigSeq) {
		this.jobLevelConfigSeq = jobLevelConfigSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "JOB_LEVEL_CODE", nullable = false, length = 10)
	public String getJobLevelCode() {
		return this.jobLevelCode;
	}

	public void setJobLevelCode(String jobLevelCode) {
		this.jobLevelCode = jobLevelCode;
	}

	@Column(name = "MAX_EXP_YEARS")
	public Integer getMaxExpYears() {
		return this.maxExpYears;
	}

	public void setMaxExpYears(Integer maxExpYears) {
		this.maxExpYears = maxExpYears;
	}
	
	@Column(name = "MAX_EXP_MONTHS")
	public Integer getMaxExpMonths() {
		return this.maxExpMonths;
	}

	public void setMaxExpMonths(Integer maxExpMonths) {
		this.maxExpMonths = maxExpMonths;
	}

	@Column(name = "MIN_EXP_YEARS")
	public Integer getMinExpYears() {
		return this.minExpYears;
	}

	public void setMinExpYears(Integer minExpYears) {
		this.minExpYears = minExpYears;
	}
	
	@Column(name = "MIN_EXP_MONTHS")
	public Integer getMinExpMonths() {
		return this.minExpMonths;
	}

	public void setMinExpMonths(Integer minExpMonths) {
		this.minExpMonths = minExpMonths;
	}

	@Column(name = "JOB_LEVEL_REWARD")
	public Integer getJobLevelReward() {
		return this.jobLevelReward;
	}

	public void setJobLevelReward(Integer jobLevelReward) {
		this.jobLevelReward = jobLevelReward;
	}

	@Column(name = "JOB_LEVEL_POINTS")
	public Integer getJobLevelPoints() {
		return this.jobLevelPoints;
	}

	public void setJobLevelPoints(Integer jobLevelPoints) {
		this.jobLevelPoints = jobLevelPoints;
	}

	@Column(name = "JOB_REWARD_BAND")
	public String getJobRewardBand() {
		return this.jobRewardBand;
	}

	public void setJobRewardBand(String jobRewardBand) {
		this.jobRewardBand = jobRewardBand;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
