package com.ripplehire.candidate.entities;

// Generated Nov 21, 2014 4:27:12 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * JobMailer generated by hbm2java
 */
@Entity
@Table(name = "job_mailer")
public class JobMailer implements java.io.Serializable {

    private Integer jobMailerSeq;
    private Campaign campaign;
    private Contest contest;
    private int companySeq;
    private String subject;
    private String jobMailerBanner;
    private String jobMailTitle;
    private String jobMailSubTitle;
    private String jobMailSubTitle2;
    private Date sendDttm;
    private String jobMailStatus;
    private Integer jobCount;
    private char status;
    private int createdBy;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;

    public JobMailer() {
    }

    public JobMailer(int companySeq, String jobMailStatus,
                     char status, int createdBy, Date createDttm) {
        this.companySeq = companySeq;
        this.jobMailStatus = jobMailStatus;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
    }

    public JobMailer(int jobMailerSeq, Campaign campaign, Contest contest,
                     int companySeq, String subject, String jobMailerBanner, String jobMailTitle,
                     String jobMailSubTitle, String jobMailSubTitle2,
                     Date sendDttm, String jobMailStatus, Integer jobCount, char status, int createdBy, 
                     Date createDttm, Integer updatedBy, Date updateDttm) {
        this.jobMailerSeq = jobMailerSeq;
        this.campaign = campaign;
        this.contest = contest;
        this.companySeq = companySeq;
        this.subject = subject;
        this.jobMailerBanner = jobMailerBanner;
        this.jobMailTitle = jobMailTitle;
        this.jobMailSubTitle = jobMailSubTitle;
        this.jobMailSubTitle2 = jobMailSubTitle2;
        this.sendDttm = sendDttm;
        this.jobMailStatus = jobMailStatus;
        this.jobCount = jobCount;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "JOB_MAILER_SEQ", unique = true, nullable = false)
    public Integer getJobMailerSeq() {
        return this.jobMailerSeq;
    }

    public void setJobMailerSeq(Integer jobMailerSeq) {
        this.jobMailerSeq = jobMailerSeq;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CAMPAIGN_SEQ")
    public Campaign getCampaign() {
        return this.campaign;
    }

    public void setCampaign(Campaign campaign) {
        this.campaign = campaign;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CONTEST_SEQ")
    public Contest getContest() {
        return this.contest;
    }

    public void setContest(Contest contest) {
        this.contest = contest;
    }

    @Column(name = "COMPANY_SEQ", nullable = false)
    public int getCompanySeq() {
        return this.companySeq;
    }

    public void setCompanySeq(int companySeq) {
        this.companySeq = companySeq;
    }

    @Column(name = "SUBJECT", length = 45)
    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    @Column(name = "JOB_MAILER_BANNER", length = 45)
    public String getJobMailerBanner() {
        return this.jobMailerBanner;
    }

    public void setJobMailerBanner(String jobMailerBanner) {
        this.jobMailerBanner = jobMailerBanner;
    }
    
    @Column(name = "JOB_MAIL_TITLE", length = 100)
    public String getJobMailTitle() {
        return this.jobMailTitle;
    }

    public void setJobMailTitle(String jobMailTitle) {
        this.jobMailTitle = jobMailTitle;
    }
    
    @Column(name = "JOB_MAIL_SUB_TITLE", length = 100)
    public String getJobMailSubTitle() {
        return this.jobMailSubTitle;
    }

    public void setJobMailSubTitle(String jobMailSubTitle) {
        this.jobMailSubTitle = jobMailSubTitle;
    }
    
    @Column(name = "JOB_MAIL_SUB_TITLE2", length = 100)
    public String getJobMailSubTitle2() {
        return this.jobMailSubTitle2;
    }

    public void setJobMailSubTitle2(String jobMailSubTitle2) {
        this.jobMailSubTitle2 = jobMailSubTitle2;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "SEND_DTTM", length = 19)
    public Date getSendDttm() {
        return this.sendDttm;
    }

    public void setSendDttm(Date sendDttm) {
        this.sendDttm = sendDttm;
    }

    @Column(name = "JOB_MAIL_STATUS", nullable = false, length = 10)
    public String getJobMailStatus() {
        return this.jobMailStatus;
    }

    public void setJobMailStatus(String jobMailStatus) {
        this.jobMailStatus = jobMailStatus;
    }
    
    @Column(name = "JOB_COUNT", length = 10)
    public Integer getJobCount() {
        return this.jobCount;
    }

    public void setJobCount(Integer jobCount) {
        this.jobCount = jobCount;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DTTM", nullable = false, length = 19)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DTTM", length = 19)
    public Date getUpdateDttm() {
        return this.updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }

}