package com.ripplehire.candidate.entities;
// Generated 9 Aug, 2016 5:39:33 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobReview generated by hbm2java
 */
@Entity
@Table(name = "job_review")
public class JobReview implements java.io.Serializable {

	private Integer jobReviewSeq;
	private Integer jobSeq;
	private Integer companyMstrSeq;
	private String jobCd;
	private String jobTitle;
	private String jobStatus;
	private String jobType;
	private String jobOthedetails;
	private String jobDesc;
	private String jobSkills;
	private Integer reqExpMin;
	private Integer reqExpMax;
	private Integer totalPositions;
	private Integer totalClosedPositions;
	private int totalCandidateClicks;
	private int totalJoblink;
	private char isHotJob;
	private Character recruiterNotification;
	private String bussinessUnit;
	private String jobSourcer;
	private String jobRequester;
	private char allowIjp;
	private char allowEmpRef;
	private char enableEeo;
	private Integer jobDetailSeq;
	private String comment;
	private char status;
	private Integer createdBy;
	private Date createDttm;
	private Integer updateBy;
	private Date updateDttm;
	private String origCd;
	private String origSeq;
	private String origPositions;
	private String comment2;
	private char isCareerSite;
	private String department;
	private String client;
	private String jobLevel;
	private String skillType;
	private Integer hiringDeadline;
	private String primarySkills;
	private String secondarySkills;
	private String custom1;
	private String custom2;
	private String custom3;
	private String custom4;
	private String custom5;
	private String custom6;
	private String custom7;
	private String custom8;
	private String custom9;
	private String custom10;
	private String custom12;
	private String custom11;
	private String custom13;
	private String custom14;
	private String custom15;
    private String custom16;
    private String custom17;
    private String custom18;
    private String custom19;
    private String custom20;
	private String clientInterview;
	private String psJobCode;
	private Date requestDate;
	private Date recruitmentStartDate;
	private String origDept;
	private String hiringTeamList;
	private String locations;
	private String country;

	public JobReview() {
	}

	public JobReview(int totalCandidateClicks, int totalJoblink, char isHotJob, char allowIjp, char allowEmpRef,
					 char enableEeo, char status, char isCareerSite) {
		this.totalCandidateClicks = totalCandidateClicks;
		this.totalJoblink = totalJoblink;
		this.isHotJob = isHotJob;
		this.allowIjp = allowIjp;
		this.allowEmpRef = allowEmpRef;
		this.enableEeo = enableEeo;
		this.status = status;
		this.isCareerSite = isCareerSite;
	}

	public JobReview(Integer jobReviewSeq, Integer jobSeq, Integer companyMstrSeq, String jobCd, String jobTitle, String jobStatus, String jobType, String jobOthedetails, String jobDesc, String jobSkills, Integer reqExpMin, Integer reqExpMax, Integer totalPositions, Integer totalClosedPositions, int totalCandidateClicks, int totalJoblink, char isHotJob, Character recruiterNotification, String bussinessUnit, String jobSourcer, String jobRequester, char allowIjp, char allowEmpRef, char enableEeo, Integer jobDetailSeq, String comment, char status, Integer createdBy, Date createDttm, Integer updateBy, Date updateDttm, String origCd, String origSeq, String origPositions, String comment2, char isCareerSite, String department, String client, String jobLevel, String skillType, Integer hiringDeadline, String primarySkills, String secondarySkills, String custom1, String custom2, String custom3, String custom4, String custom5, String custom6, String custom7, String custom8, String custom9, String custom10, String custom12, String clientInterview, String psJobCode, Date requestDate, Date recruitmentStartDate, String origDept, String hiringTeamList, String locations, String country) {
		this.jobReviewSeq = jobReviewSeq;
		this.jobSeq = jobSeq;
		this.companyMstrSeq = companyMstrSeq;
		this.jobCd = jobCd;
		this.jobTitle = jobTitle;
		this.jobStatus = jobStatus;
		this.jobType = jobType;
		this.jobOthedetails = jobOthedetails;
		this.jobDesc = jobDesc;
		this.jobSkills = jobSkills;
		this.reqExpMin = reqExpMin;
		this.reqExpMax = reqExpMax;
		this.totalPositions = totalPositions;
		this.totalClosedPositions = totalClosedPositions;
		this.totalCandidateClicks = totalCandidateClicks;
		this.totalJoblink = totalJoblink;
		this.isHotJob = isHotJob;
		this.recruiterNotification = recruiterNotification;
		this.bussinessUnit = bussinessUnit;
		this.jobSourcer = jobSourcer;
		this.jobRequester = jobRequester;
		this.allowIjp = allowIjp;
		this.allowEmpRef = allowEmpRef;
		this.enableEeo = enableEeo;
		this.jobDetailSeq = jobDetailSeq;
		this.comment = comment;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updateBy = updateBy;
		this.updateDttm = updateDttm;
		this.origCd = origCd;
		this.origSeq = origSeq;
		this.origPositions = origPositions;
		this.comment2 = comment2;
		this.isCareerSite = isCareerSite;
		this.department = department;
		this.client = client;
		this.jobLevel = jobLevel;
		this.skillType = skillType;
		this.hiringDeadline = hiringDeadline;
		this.primarySkills = primarySkills;
		this.secondarySkills = secondarySkills;
		this.custom1 = custom1;
		this.custom2 = custom2;
		this.custom3 = custom3;
		this.custom4 = custom4;
		this.custom5 = custom5;
		this.custom6 = custom6;
		this.custom7 = custom7;
		this.custom8 = custom8;
		this.custom9 = custom9;
		this.custom10 = custom10;
		this.custom12 = custom12;
		this.clientInterview = clientInterview;
		this.psJobCode = psJobCode;
		this.requestDate = requestDate;
		this.recruitmentStartDate = recruitmentStartDate;
		this.origDept = origDept;
		this.hiringTeamList = hiringTeamList;
		this.locations = locations;
		this.country = country;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "JOB_REVIEW_SEQ", unique = true, nullable = false)
	public Integer getJobReviewSeq() {
		return this.jobReviewSeq;
	}

	public void setJobReviewSeq(Integer jobReviewSeq) {
		this.jobReviewSeq = jobReviewSeq;
	}

	@Column(name = "JOB_SEQ")
	public Integer getJobSeq() {
		return this.jobSeq;
	}

	public void setJobSeq(Integer jobSeq) {
		this.jobSeq = jobSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ")
	public Integer getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(Integer companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "JOB_CD", length = 50)
	public String getJobCd() {
		return this.jobCd;
	}

	public void setJobCd(String jobCd) {
		this.jobCd = jobCd;
	}

	@Column(name = "JOB_TITLE", length = 200)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "JOB_STATUS", length = 10)
	public String getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	@Column(name = "JOB_TYPE", length = 10)
	public String getJobType() {
		return this.jobType;
	}

	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	@Column(name = "JOB_OTHEDETAILS", length = 3000)
	public String getJobOthedetails() {
		return this.jobOthedetails;
	}

	public void setJobOthedetails(String jobOthedetails) {
		this.jobOthedetails = jobOthedetails;
	}

	@Column(name = "JOB_DESC")
	public String getJobDesc() {
		return this.jobDesc;
	}

	public void setJobDesc(String jobDesc) {
		this.jobDesc = jobDesc;
	}

	@Column(name = "JOB_SKILLS", length = 9000)
	public String getJobSkills() {
		return this.jobSkills;
	}

	public void setJobSkills(String jobSkills) {
		this.jobSkills = jobSkills;
	}

	@Column(name = "REQ_EXP_MIN")
	public Integer getReqExpMin() {
		return this.reqExpMin;
	}

	public void setReqExpMin(Integer reqExpMin) {
		this.reqExpMin = reqExpMin;
	}

	@Column(name = "REQ_EXP_MAX")
	public Integer getReqExpMax() {
		return this.reqExpMax;
	}

	public void setReqExpMax(Integer reqExpMax) {
		this.reqExpMax = reqExpMax;
	}

	@Column(name = "TOTAL_POSITIONS")
	public Integer getTotalPositions() {
		return this.totalPositions;
	}

	public void setTotalPositions(Integer totalPositions) {
		this.totalPositions = totalPositions;
	}

	@Column(name = "TOTAL_CLOSED_POSITIONS")
	public Integer getTotalClosedPositions() {
		return this.totalClosedPositions;
	}

	public void setTotalClosedPositions(Integer totalClosedPositions) {
		this.totalClosedPositions = totalClosedPositions;
	}

	@Column(name = "TOTAL_CANDIDATE_CLICKS", nullable = false)
	public int getTotalCandidateClicks() {
		return this.totalCandidateClicks;
	}

	public void setTotalCandidateClicks(int totalCandidateClicks) {
		this.totalCandidateClicks = totalCandidateClicks;
	}

	@Column(name = "TOTAL_JOBLINK", nullable = false)
	public int getTotalJoblink() {
		return this.totalJoblink;
	}

	public void setTotalJoblink(int totalJoblink) {
		this.totalJoblink = totalJoblink;
	}

	@Column(name = "IS_HOT_JOB", nullable = false, length = 1)
	public char getIsHotJob() {
		return this.isHotJob;
	}

	public void setIsHotJob(char isHotJob) {
		this.isHotJob = isHotJob;
	}

	@Column(name = "RECRUITER_NOTIFICATION", length = 1)
	public Character getRecruiterNotification() {
		return this.recruiterNotification;
	}

	public void setRecruiterNotification(Character recruiterNotification) {
		this.recruiterNotification = recruiterNotification;
	}

	@Column(name = "BUSSINESS_UNIT", length = 50)
	public String getBussinessUnit() {
		return this.bussinessUnit;
	}

	public void setBussinessUnit(String bussinessUnit) {
		this.bussinessUnit = bussinessUnit;
	}

	@Column(name = "JOB_SOURCER", length = 100)
	public String getJobSourcer() {
		return this.jobSourcer;
	}

	public void setJobSourcer(String jobSourcer) {
		this.jobSourcer = jobSourcer;
	}

	@Column(name = "JOB_REQUESTER", length = 100)
	public String getJobRequester() {
		return this.jobRequester;
	}

	public void setJobRequester(String jobRequester) {
		this.jobRequester = jobRequester;
	}

	@Column(name = "ALLOW_IJP", nullable = false, length = 1)
	public char getAllowIjp() {
		return this.allowIjp;
	}

	public void setAllowIjp(char allowIjp) {
		this.allowIjp = allowIjp;
	}

	@Column(name = "ALLOW_EMP_REF", nullable = false, length = 1)
	public char getAllowEmpRef() {
		return this.allowEmpRef;
	}

	public void setAllowEmpRef(char allowEmpRef) {
		this.allowEmpRef = allowEmpRef;
	}

	@Column(name = "ENABLE_EEO", nullable = false, length = 1)
	public char getEnableEeo() {
		return this.enableEeo;
	}

	public void setEnableEeo(char enableEeo) {
		this.enableEeo = enableEeo;
	}

	@Column(name = "JOB_DETAIL_SEQ")
	public Integer getJobDetailSeq() {
		return this.jobDetailSeq;
	}

	public void setJobDetailSeq(Integer jobDetailSeq) {
		this.jobDetailSeq = jobDetailSeq;
	}

	@Column(name = "COMMENT", length = 100)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATE_BY")
	public Integer getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@Column(name = "ORIG_CD", length = 50)
	public String getOrigCd() {
		return this.origCd;
	}

	public void setOrigCd(String origCd) {
		this.origCd = origCd;
	}

	@Column(name = "ORIG_SEQ", length = 50)
	public String getOrigSeq() {
		return this.origSeq;
	}

	public void setOrigSeq(String origSeq) {
		this.origSeq = origSeq;
	}

	@Column(name = "ORIG_POSITIONS", length = 20)
	public String getOrigPositions() {
		return this.origPositions;
	}

	public void setOrigPositions(String origPositions) {
		this.origPositions = origPositions;
	}

	@Column(name = "COMMENT2", length = 45)
	public String getComment2() {
		return this.comment2;
	}

	public void setComment2(String comment2) {
		this.comment2 = comment2;
	}

	@Column(name = "IS_CAREER_SITE", nullable = false, length = 1)
	public char getIsCareerSite() {
		return this.isCareerSite;
	}

	public void setIsCareerSite(char isCareerSite) {
		this.isCareerSite = isCareerSite;
	}

	@Column(name = "DEPARTMENT", length = 100)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "CLIENT", length = 100)
	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	@Column(name = "JOB_LEVEL", length = 20)
	public String getJobLevel() {
		return this.jobLevel;
	}

	public void setJobLevel(String jobLevel) {
		this.jobLevel = jobLevel;
	}

	@Column(name = "SKILL_TYPE", length = 45)
	public String getSkillType() {
		return this.skillType;
	}

	public void setSkillType(String skillType) {
		this.skillType = skillType;
	}

	@Column(name = "HIRING_DEADLINE")
	public Integer getHiringDeadline() {
		return this.hiringDeadline;
	}

	public void setHiringDeadline(Integer hiringDeadline) {
		this.hiringDeadline = hiringDeadline;
	}

	@Column(name = "PRIMARY_SKILLS", length = 200)
	public String getPrimarySkills() {
		return this.primarySkills;
	}

	public void setPrimarySkills(String primarySkills) {
		this.primarySkills = primarySkills;
	}

	@Column(name = "SECONDARY_SKILLS", length = 200)
	public String getSecondarySkills() {
		return this.secondarySkills;
	}

	public void setSecondarySkills(String secondarySkills) {
		this.secondarySkills = secondarySkills;
	}

	@Column(name = "CUSTOM1", length = 100)
	public String getCustom1() {
		return this.custom1;
	}

	public void setCustom1(String custom1) {
		this.custom1 = custom1;
	}

	@Column(name = "CUSTOM2", length = 100)
	public String getCustom2() {
		return this.custom2;
	}

	public void setCustom2(String custom2) {
		this.custom2 = custom2;
	}

	@Column(name = "CUSTOM3", length = 100)
	public String getCustom3() {
		return this.custom3;
	}

	public void setCustom3(String custom3) {
		this.custom3 = custom3;
	}

	@Column(name = "CUSTOM4", length = 500)
	public String getCustom4() {
		return custom4;
	}

	public void setCustom4(String custom4) {
		this.custom4 = custom4;
	}

	@Column(name = "CUSTOM5", length = 500)
	public String getCustom5() {
		return custom5;
	}

	public void setCustom5(String custom5) {
		this.custom5 = custom5;
	}

	@Column(name = "CUSTOM6", length = 500)
	public String getCustom6() {
		return custom6;
	}

	public void setCustom6(String custom6) {
		this.custom6 = custom6;
	}

	@Column(name = "CUSTOM7", length = 500)
	public String getCustom7() {
		return custom7;
	}

	public void setCustom7(String custom7) {
		this.custom7 = custom7;
	}

	@Column(name = "CUSTOM8", length = 500)
	public String getCustom8() {
		return custom8;
	}

	public void setCustom8(String custom8) {
		this.custom8 = custom8;
	}

	@Column(name = "CUSTOM9", length = 500)
	public String getCustom9() {
		return custom9;
	}

	public void setCustom9(String custom9) {
		this.custom9 = custom9;
	}

	@Column(name = "CUSTOM10", length = 500)
	public String getCustom10() {
		return custom10;
	}

	public void setCustom10(String custom10) {
		this.custom10 = custom10;
	}

	@Column(name = "CUSTOM12", length = 500)
	public String getCustom12() {
		return custom12;
	}

	public void setCustom12(String custom12) {
		this.custom12 = custom12;
	}

	@Column(name = "CLIENT_INTERVIEW", length = 10)
	public String getClientInterview() {
		return this.clientInterview;
	}

	public void setClientInterview(String clientInterview) {
		this.clientInterview = clientInterview;
	}

	@Column(name = "PS_JOB_CODE", length = 50)
	public String getPsJobCode() {
		return this.psJobCode;
	}

	public void setPsJobCode(String psJobCode) {
		this.psJobCode = psJobCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQUEST_DATE", length = 19)
	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECRUITMENT_START_DATE", length = 19)
	public Date getRecruitmentStartDate() {
		return this.recruitmentStartDate;
	}

	public void setRecruitmentStartDate(Date recruitmentStartDate) {
		this.recruitmentStartDate = recruitmentStartDate;
	}

	@Column(name = "ORIG_DEPT", length = 50)
	public String getOrigDept() {
		return this.origDept;
	}

	public void setOrigDept(String origDept) {
		this.origDept = origDept;
	}

	@Column(name = "HIRING_TEAM_LIST", length = 3000)
	public String getHiringTeamList() {
		return this.hiringTeamList;
	}

	public void setHiringTeamList(String hiringTeamList) {
		this.hiringTeamList = hiringTeamList;
	}

	@Column(name = "LOCATIONS", length = 300)
	public String getLocations() {
		return this.locations;
	}

	public void setLocations(String locations) {
		this.locations = locations;
	}

	@Column(name = "COUNTRY", length = 200)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCustom11() {
		return custom11;
	}

	public void setCustom11(String custom11) {
		this.custom11 = custom11;
	}

	public String getCustom13() {
		return custom13;
	}

	public void setCustom13(String custom13) {
		this.custom13 = custom13;
	}

	public String getCustom14() {
		return custom14;
	}

	public void setCustom14(String custom14) {
		this.custom14 = custom14;
	}

	public String getCustom15() {
		return custom15;
	}

	public void setCustom15(String custom15) {
		this.custom15 = custom15;
	}

	public String getCustom16() {
		return custom16;
	}

	public void setCustom16(String custom16) {
		this.custom16 = custom16;
	}

	public String getCustom17() {
		return custom17;
	}

	public void setCustom17(String custom17) {
		this.custom17 = custom17;
	}

	public String getCustom18() {
		return custom18;
	}

	public void setCustom18(String custom18) {
		this.custom18 = custom18;
	}

	public String getCustom19() {
		return custom19;
	}

	public void setCustom19(String custom19) {
		this.custom19 = custom19;
	}

	public String getCustom20() {
		return custom20;
	}

	public void setCustom20(String custom20) {
		this.custom20 = custom20;
	}
}
