package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobRewardType generated by hbm2java
 */
@Entity
@Table(name = "job_reward_type")
public class JobRewardType implements java.io.Serializable {

	private Integer jobRewardTypeSeq;
	private ParentCompanyMstr parentCompanyMstr;
	private String rewardTypeCd;
	private String rewardTypeDesc;
	private Character status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<JobRewardPolicy> jobRewardPolicies = new HashSet<JobRewardPolicy>(
			0);
	private Set<JobRewardTypeLang> jobRewardTypeLangs = new HashSet<JobRewardTypeLang>(
			0);

	public JobRewardType() {
	}

	public JobRewardType(ParentCompanyMstr parentCompanyMstr,
			String rewardTypeCd, String rewardTypeDesc, int createdBy,
			Date createDttm) {
		this.parentCompanyMstr = parentCompanyMstr;
		this.rewardTypeCd = rewardTypeCd;
		this.rewardTypeDesc = rewardTypeDesc;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public JobRewardType(ParentCompanyMstr parentCompanyMstr,
			String rewardTypeCd, String rewardTypeDesc, Character status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm,
			Set<JobRewardPolicy> jobRewardPolicies,
			Set<JobRewardTypeLang> jobRewardTypeLangs) {
		this.parentCompanyMstr = parentCompanyMstr;
		this.rewardTypeCd = rewardTypeCd;
		this.rewardTypeDesc = rewardTypeDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.jobRewardPolicies = jobRewardPolicies;
		this.jobRewardTypeLangs = jobRewardTypeLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "JOB_REWARD_TYPE_SEQ", unique = true, nullable = false)
	public Integer getJobRewardTypeSeq() {
		return this.jobRewardTypeSeq;
	}

	public void setJobRewardTypeSeq(Integer jobRewardTypeSeq) {
		this.jobRewardTypeSeq = jobRewardTypeSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_COMPANY_MSTR_SEQ", nullable = false)
	public ParentCompanyMstr getParentCompanyMstr() {
		return this.parentCompanyMstr;
	}

	public void setParentCompanyMstr(ParentCompanyMstr parentCompanyMstr) {
		this.parentCompanyMstr = parentCompanyMstr;
	}

	@Column(name = "REWARD_TYPE_CD", nullable = false, length = 100)
	public String getRewardTypeCd() {
		return this.rewardTypeCd;
	}

	public void setRewardTypeCd(String rewardTypeCd) {
		this.rewardTypeCd = rewardTypeCd;
	}

	@Column(name = "REWARD_TYPE_DESC", nullable = false, length = 100)
	public String getRewardTypeDesc() {
		return this.rewardTypeDesc;
	}

	public void setRewardTypeDesc(String rewardTypeDesc) {
		this.rewardTypeDesc = rewardTypeDesc;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobRewardType")
	public Set<JobRewardPolicy> getJobRewardPolicies() {
		return this.jobRewardPolicies;
	}

	public void setJobRewardPolicies(Set<JobRewardPolicy> jobRewardPolicies) {
		this.jobRewardPolicies = jobRewardPolicies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobRewardType")
	public Set<JobRewardTypeLang> getJobRewardTypeLangs() {
		return this.jobRewardTypeLangs;
	}

	public void setJobRewardTypeLangs(Set<JobRewardTypeLang> jobRewardTypeLangs) {
		this.jobRewardTypeLangs = jobRewardTypeLangs;
	}

}
