package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobRewardPolicyLang generated by hbm2java
 */
@Entity
@Table(name = "job_reward_policy_lang")
public class JobRewardPolicyLang implements java.io.Serializable {

	private Integer jobRewardPolicyLangSeq;
	private JobRewardPolicy jobRewardPolicy;
	private LangMstr langMstr;
	private String jobRewardPolicyValue;
	private Character status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public JobRewardPolicyLang() {
	}

	public JobRewardPolicyLang(JobRewardPolicy jobRewardPolicy,
			LangMstr langMstr, String jobRewardPolicyValue, int createdBy,
			Date createDttm) {
		this.jobRewardPolicy = jobRewardPolicy;
		this.langMstr = langMstr;
		this.jobRewardPolicyValue = jobRewardPolicyValue;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public JobRewardPolicyLang(JobRewardPolicy jobRewardPolicy,
			LangMstr langMstr, String jobRewardPolicyValue, Character status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
		this.jobRewardPolicy = jobRewardPolicy;
		this.langMstr = langMstr;
		this.jobRewardPolicyValue = jobRewardPolicyValue;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "JOB_REWARD_POLICY_LANG_SEQ", unique = true, nullable = false)
	public Integer getJobRewardPolicyLangSeq() {
		return this.jobRewardPolicyLangSeq;
	}

	public void setJobRewardPolicyLangSeq(Integer jobRewardPolicyLangSeq) {
		this.jobRewardPolicyLangSeq = jobRewardPolicyLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_REWARD_POLICY_SEQ", nullable = false)
	public JobRewardPolicy getJobRewardPolicy() {
		return this.jobRewardPolicy;
	}

	public void setJobRewardPolicy(JobRewardPolicy jobRewardPolicy) {
		this.jobRewardPolicy = jobRewardPolicy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@Column(name = "JOB_REWARD_POLICY_VALUE", nullable = false)
	public String getJobRewardPolicyValue() {
		return this.jobRewardPolicyValue;
	}

	public void setJobRewardPolicyValue(String jobRewardPolicyValue) {
		this.jobRewardPolicyValue = jobRewardPolicyValue;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
