package com.ripplehire.candidate.entities;

// Generated May 16, 2014 11:36:58 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobRewardPolicy generated by hbm2java
 */
@Entity
@Table(name = "job_reward_policy")
public class JobRewardPolicy implements java.io.Serializable {

	private Integer jobRewardPolicySeq;
	private ParentCompanyMstr parentCompanyMstr;
	private JobRewardType jobRewardType;
	private String bandCd;
	private String jobRewardPolicyValue;
	private Character status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<JobRewardPolicyLang> jobRewardPolicyLangs = new HashSet<JobRewardPolicyLang>(
			0);

	public JobRewardPolicy() {
	}

	public JobRewardPolicy(ParentCompanyMstr parentCompanyMstr,
			JobRewardType jobRewardType, String bandCd,
			String jobRewardPolicyValue, int createdBy, Date createDttm) {
		this.parentCompanyMstr = parentCompanyMstr;
		this.jobRewardType = jobRewardType;
		this.bandCd = bandCd;
		this.jobRewardPolicyValue = jobRewardPolicyValue;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public JobRewardPolicy(ParentCompanyMstr parentCompanyMstr,
			JobRewardType jobRewardType, String bandCd,
			String jobRewardPolicyValue, Character status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm,
			Set<JobRewardPolicyLang> jobRewardPolicyLangs) {
		this.parentCompanyMstr = parentCompanyMstr;
		this.jobRewardType = jobRewardType;
		this.bandCd = bandCd;
		this.jobRewardPolicyValue = jobRewardPolicyValue;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.jobRewardPolicyLangs = jobRewardPolicyLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "JOB_REWARD_POLICY_SEQ", unique = true, nullable = false)
	public Integer getJobRewardPolicySeq() {
		return this.jobRewardPolicySeq;
	}

	public void setJobRewardPolicySeq(Integer jobRewardPolicySeq) {
		this.jobRewardPolicySeq = jobRewardPolicySeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENT_COMPANY_MSTR_SEQ", nullable = false)
	public ParentCompanyMstr getParentCompanyMstr() {
		return this.parentCompanyMstr;
	}

	public void setParentCompanyMstr(ParentCompanyMstr parentCompanyMstr) {
		this.parentCompanyMstr = parentCompanyMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_REWARD_TYPE_SEQ", nullable = false)
	public JobRewardType getJobRewardType() {
		return this.jobRewardType;
	}

	public void setJobRewardType(JobRewardType jobRewardType) {
		this.jobRewardType = jobRewardType;
	}

	@Column(name = "BAND_CD", nullable = false, length = 25)
	public String getBandCd() {
		return this.bandCd;
	}

	public void setBandCd(String bandCd) {
		this.bandCd = bandCd;
	}

	@Column(name = "JOB_REWARD_POLICY_VALUE", nullable = false, length = 20)
	public String getJobRewardPolicyValue() {
		return this.jobRewardPolicyValue;
	}

	public void setJobRewardPolicyValue(String jobRewardPolicyValue) {
		this.jobRewardPolicyValue = jobRewardPolicyValue;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobRewardPolicy")
	public Set<JobRewardPolicyLang> getJobRewardPolicyLangs() {
		return this.jobRewardPolicyLangs;
	}

	public void setJobRewardPolicyLangs(
			Set<JobRewardPolicyLang> jobRewardPolicyLangs) {
		this.jobRewardPolicyLangs = jobRewardPolicyLangs;
	}

}
