package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobRewardRule generated by hbm2java
 */
@Entity
@Table(name = "job_reward_rule")
public class JobRewardRule implements java.io.Serializable {

	private Integer jobRewardRuleSeq;
	private Reward reward;
	private int companyMstrSeq;
	private String bandCd;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public JobRewardRule() {
	}

	public JobRewardRule(Reward reward, int companyMstrSeq, String bandCd,
			char status, int createdBy, Date createDttm) {
		this.reward = reward;
		this.companyMstrSeq = companyMstrSeq;
		this.bandCd = bandCd;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public JobRewardRule(Reward reward, int companyMstrSeq, String bandCd,
			char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm) {
		this.reward = reward;
		this.companyMstrSeq = companyMstrSeq;
		this.bandCd = bandCd;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "JOB_REWARD_RULE_SEQ", unique = true, nullable = false)
	public Integer getJobRewardRuleSeq() {
		return this.jobRewardRuleSeq;
	}

	public void setJobRewardRuleSeq(Integer jobRewardRuleSeq) {
		this.jobRewardRuleSeq = jobRewardRuleSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REWARD_SEQ", nullable = false)
	public Reward getReward() {
		return this.reward;
	}

	public void setReward(Reward reward) {
		this.reward = reward;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "BAND_CD", nullable = false, length = 20)
	public String getBandCd() {
		return this.bandCd;
	}

	public void setBandCd(String bandCd) {
		this.bandCd = bandCd;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
