package com.ripplehire.candidate.entities;
// Generated 2 May, 2017 5:05:15 PM by Hibernate Tools 5.2.0.CR1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * JobSnapshot generated by hbm2java
 */
@Entity
@Table(name = "job_snapshot")
public class JobSnapshot implements Serializable {

	private int jobSnapshotSeq;
	private Job job;
	private int companyMstrSeq;
	private String jobTitle;
	private byte[]  snapshotData;
	private byte[]  approvalData;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public JobSnapshot() {
	}

	public JobSnapshot(int jobSnapshotSeq, Job job, int companyMstrSeq, String jobTitle, byte[]  snapshotData, byte[]  approvalData, char status,
			int createdBy, Date createDttm) {
		this.jobSnapshotSeq = jobSnapshotSeq;
		this.job = job;
		this.companyMstrSeq = companyMstrSeq;
		this.snapshotData = snapshotData;
		this.approvalData = approvalData;
		this.jobTitle = jobTitle;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public JobSnapshot(int jobSnapshotSeq, Job job, int companyMstrSeq, String jobTitle, byte[]  snapshotData, byte[]  approvalData, char status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
		this.jobSnapshotSeq = jobSnapshotSeq;
		this.job = job;
		this.companyMstrSeq = companyMstrSeq;
		this.jobTitle = jobTitle;
		this.snapshotData = snapshotData;
		this.approvalData = approvalData;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "JOB_SNAPSHOT_SEQ", unique = true, nullable = false)
	public int getJobSnapshotSeq() {
		return this.jobSnapshotSeq;
	}

	public void setJobSnapshotSeq(int jobSnapshotSeq) {
		this.jobSnapshotSeq = jobSnapshotSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_SEQ", nullable = false)
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "JOB_TITLE", nullable = false, length = 200)
	public String getJobTitle() {
		return jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "SNAPSHOT_DATA", nullable = false)
	public byte[]  getSnapshotData() {
		return this.snapshotData;
	}

	public void setSnapshotData(byte[]  snapshotData) {
		this.snapshotData = snapshotData;
	}

	@Column(name = "APPROVAL_DATA", nullable = false)
	public byte[]  getApprovalData() {
		return approvalData;
	}

	public void setApprovalData(byte[]  approvalData) {
		this.approvalData = approvalData;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
