package com.ripplehire.candidate.entities;
// Generated Mar 10, 2016 2:38:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobViews generated by hbm2java
 */
@Entity
@Table(name = "job_views")
public class JobViews implements java.io.Serializable {

	private Integer jobViewsSeq;
	private EmplRefrl emplRefrl;
	private Job job;
	private int companyMstrSeq;
	private int count;
	private char status;
	private Date createDttm;
	private int createdBy;
	private Date updateDttm;
	private Integer updatedBy;

	public JobViews() {
	}

	public JobViews(EmplRefrl emplRefrl, Job job, int companyMstrSeq, int count, char status, Date createDttm,
			int createdBy) {
		this.emplRefrl = emplRefrl;
		this.job = job;
		this.companyMstrSeq = companyMstrSeq;
		this.count = count;
		this.status = status;
		this.createDttm = createDttm;
		this.createdBy = createdBy;
	}

	public JobViews(EmplRefrl emplRefrl, Job job, int companyMstrSeq, int count, char status, Date createDttm,
			int createdBy, Date updateDttm, Integer updatedBy) {
		this.emplRefrl = emplRefrl;
		this.job = job;
		this.companyMstrSeq = companyMstrSeq;
		this.count = count;
		this.status = status;
		this.createDttm = createDttm;
		this.createdBy = createdBy;
		this.updateDttm = updateDttm;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "JOB_VIEWS_SEQ", unique = true, nullable = false)
	public Integer getJobViewsSeq() {
		return this.jobViewsSeq;
	}

	public void setJobViewsSeq(Integer jobViewsSeq) {
		this.jobViewsSeq = jobViewsSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPL_REFRL_SEQ", nullable = false)
	public EmplRefrl getEmplRefrl() {
		return this.emplRefrl;
	}

	public void setEmplRefrl(EmplRefrl emplRefrl) {
		this.emplRefrl = emplRefrl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_SEQ", nullable = false)
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "COUNT", nullable = false)
	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

}
