package com.ripplehire.candidate.entities;
// Generated Jun 22, 2016 8:07:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LangMstr generated by hbm2java
 */
@Entity
@Table(name = "lang_mstr")
public class LangMstr implements java.io.Serializable {

	private Integer langMstrSeq;
	private String langCd;
	private String langDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<CompanyMstrLang> companyMstrLangs = new HashSet<CompanyMstrLang>(0);
	private Set<RewardBadgeLang> rewardBadgeLangs = new HashSet<RewardBadgeLang>(0);
	private Set<RelationshipMstrLang> relationshipMstrLangs = new HashSet<RelationshipMstrLang>(0);
	private Set<UserProfile> userProfiles = new HashSet<UserProfile>(0);
	private Set<QualificationMstrLang> qualificationMstrLangs = new HashSet<QualificationMstrLang>(0);
	private Set<CityLang> cityLangs = new HashSet<CityLang>(0);
	private Set<JobRewardPolicyLang> jobRewardPolicyLangs = new HashSet<JobRewardPolicyLang>(0);
	private Set<SkillsMstrLang> skillsMstrLangs = new HashSet<SkillsMstrLang>(0);
	private Set<RefrlChannelMstrLang> refrlChannelMstrLangs = new HashSet<RefrlChannelMstrLang>(0);
	private Set<LocationMstrLang> locationMstrLangs = new HashSet<LocationMstrLang>(0);
	private Set<CurrentLocationMstrLang> currentLocationMstrLangs = new HashSet<CurrentLocationMstrLang>(0);
	private Set<JobRewardTypeLang> jobRewardTypeLangs = new HashSet<JobRewardTypeLang>(0);
	private Set<RewardTypeMstrLang> rewardTypeMstrLangs = new HashSet<RewardTypeMstrLang>(0);
	private Set<GenderMstrLang> genderMstrLangs = new HashSet<GenderMstrLang>(0);
	private Set<RefrlStatusMstrLang> refrlStatusMstrLangs = new HashSet<RefrlStatusMstrLang>(0);
	private Set<GoalLang> goalLangs = new HashSet<GoalLang>(0);
	private Set<InterviewStageMstrLang> interviewStageMstrLangs = new HashSet<InterviewStageMstrLang>(0);
	private Set<CurrentEmployerMstrLang> currentEmployerMstrLangs = new HashSet<CurrentEmployerMstrLang>(0);
	private Set<EmailTemplateConfigLang> emailTemplateConfigLangs = new HashSet<EmailTemplateConfigLang>(0);
	private Set<CountryLang> countryLangs = new HashSet<CountryLang>(0);
	private Set<CountryMstrLang> countryMstrLangs = new HashSet<CountryMstrLang>(0);
	private Set<SocialMessagesLang> socialMessagesLangs = new HashSet<SocialMessagesLang>(0);
	private Set<RewardMedalLang> rewardMedalLangs = new HashSet<RewardMedalLang>(0);
	private Set<LevelRewardLang> levelRewardLangs = new HashSet<LevelRewardLang>(0);
	private Set<ClientInterviewStatusLang> clientInterviewStatusLangs = new HashSet<ClientInterviewStatusLang>(0);
	private Set<StateLang> stateLangs = new HashSet<StateLang>(0);

	public LangMstr() {
	}

	public LangMstr(String langCd, String langDesc, char status, int createdBy, Date createDttm) {
		this.langCd = langCd;
		this.langDesc = langDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public LangMstr(String langCd, String langDesc, char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm, Set<CompanyMstrLang> companyMstrLangs, Set<RewardBadgeLang> rewardBadgeLangs,
			Set<RelationshipMstrLang> relationshipMstrLangs, Set<UserProfile> userProfiles,
			Set<QualificationMstrLang> qualificationMstrLangs, Set<CityLang> cityLangs,
			Set<JobRewardPolicyLang> jobRewardPolicyLangs, Set<SkillsMstrLang> skillsMstrLangs,
			Set<RefrlChannelMstrLang> refrlChannelMstrLangs, Set<LocationMstrLang> locationMstrLangs,
			Set<CurrentLocationMstrLang> currentLocationMstrLangs, Set<JobRewardTypeLang> jobRewardTypeLangs,
			Set<RewardTypeMstrLang> rewardTypeMstrLangs, Set<GenderMstrLang> genderMstrLangs,
			Set<RefrlStatusMstrLang> refrlStatusMstrLangs, Set<GoalLang> goalLangs,
			Set<InterviewStageMstrLang> interviewStageMstrLangs, Set<CurrentEmployerMstrLang> currentEmployerMstrLangs,
			Set<EmailTemplateConfigLang> emailTemplateConfigLangs, Set<CountryLang> countryLangs,
			Set<CountryMstrLang> countryMstrLangs, Set<SocialMessagesLang> socialMessagesLangs,
			Set<RewardMedalLang> rewardMedalLangs, Set<LevelRewardLang> levelRewardLangs,
			Set<ClientInterviewStatusLang> clientInterviewStatusLangs, Set<StateLang> stateLangs) {
		this.langCd = langCd;
		this.langDesc = langDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.companyMstrLangs = companyMstrLangs;
		this.rewardBadgeLangs = rewardBadgeLangs;
		this.relationshipMstrLangs = relationshipMstrLangs;
		this.userProfiles = userProfiles;
		this.qualificationMstrLangs = qualificationMstrLangs;
		this.cityLangs = cityLangs;
		this.jobRewardPolicyLangs = jobRewardPolicyLangs;
		this.skillsMstrLangs = skillsMstrLangs;
		this.refrlChannelMstrLangs = refrlChannelMstrLangs;
		this.locationMstrLangs = locationMstrLangs;
		this.currentLocationMstrLangs = currentLocationMstrLangs;
		this.jobRewardTypeLangs = jobRewardTypeLangs;
		this.rewardTypeMstrLangs = rewardTypeMstrLangs;
		this.genderMstrLangs = genderMstrLangs;
		this.refrlStatusMstrLangs = refrlStatusMstrLangs;
		this.goalLangs = goalLangs;
		this.interviewStageMstrLangs = interviewStageMstrLangs;
		this.currentEmployerMstrLangs = currentEmployerMstrLangs;
		this.emailTemplateConfigLangs = emailTemplateConfigLangs;
		this.countryLangs = countryLangs;
		this.countryMstrLangs = countryMstrLangs;
		this.socialMessagesLangs = socialMessagesLangs;
		this.rewardMedalLangs = rewardMedalLangs;
		this.levelRewardLangs = levelRewardLangs;
		this.clientInterviewStatusLangs = clientInterviewStatusLangs;
		this.stateLangs = stateLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LANG_MSTR_SEQ", unique = true, nullable = false)
	public Integer getLangMstrSeq() {
		return this.langMstrSeq;
	}

	public void setLangMstrSeq(Integer langMstrSeq) {
		this.langMstrSeq = langMstrSeq;
	}

	@Column(name = "LANG_CD", nullable = false, length = 50)
	public String getLangCd() {
		return this.langCd;
	}

	public void setLangCd(String langCd) {
		this.langCd = langCd;
	}

	@Column(name = "LANG_DESC", nullable = false, length = 100)
	public String getLangDesc() {
		return this.langDesc;
	}

	public void setLangDesc(String langDesc) {
		this.langDesc = langDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<CompanyMstrLang> getCompanyMstrLangs() {
		return this.companyMstrLangs;
	}

	public void setCompanyMstrLangs(Set<CompanyMstrLang> companyMstrLangs) {
		this.companyMstrLangs = companyMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<RewardBadgeLang> getRewardBadgeLangs() {
		return this.rewardBadgeLangs;
	}

	public void setRewardBadgeLangs(Set<RewardBadgeLang> rewardBadgeLangs) {
		this.rewardBadgeLangs = rewardBadgeLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<RelationshipMstrLang> getRelationshipMstrLangs() {
		return this.relationshipMstrLangs;
	}

	public void setRelationshipMstrLangs(Set<RelationshipMstrLang> relationshipMstrLangs) {
		this.relationshipMstrLangs = relationshipMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<UserProfile> getUserProfiles() {
		return this.userProfiles;
	}

	public void setUserProfiles(Set<UserProfile> userProfiles) {
		this.userProfiles = userProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<QualificationMstrLang> getQualificationMstrLangs() {
		return this.qualificationMstrLangs;
	}

	public void setQualificationMstrLangs(Set<QualificationMstrLang> qualificationMstrLangs) {
		this.qualificationMstrLangs = qualificationMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<CityLang> getCityLangs() {
		return this.cityLangs;
	}

	public void setCityLangs(Set<CityLang> cityLangs) {
		this.cityLangs = cityLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<JobRewardPolicyLang> getJobRewardPolicyLangs() {
		return this.jobRewardPolicyLangs;
	}

	public void setJobRewardPolicyLangs(Set<JobRewardPolicyLang> jobRewardPolicyLangs) {
		this.jobRewardPolicyLangs = jobRewardPolicyLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<SkillsMstrLang> getSkillsMstrLangs() {
		return this.skillsMstrLangs;
	}

	public void setSkillsMstrLangs(Set<SkillsMstrLang> skillsMstrLangs) {
		this.skillsMstrLangs = skillsMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<RefrlChannelMstrLang> getRefrlChannelMstrLangs() {
		return this.refrlChannelMstrLangs;
	}

	public void setRefrlChannelMstrLangs(Set<RefrlChannelMstrLang> refrlChannelMstrLangs) {
		this.refrlChannelMstrLangs = refrlChannelMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<LocationMstrLang> getLocationMstrLangs() {
		return this.locationMstrLangs;
	}

	public void setLocationMstrLangs(Set<LocationMstrLang> locationMstrLangs) {
		this.locationMstrLangs = locationMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<CurrentLocationMstrLang> getCurrentLocationMstrLangs() {
		return this.currentLocationMstrLangs;
	}

	public void setCurrentLocationMstrLangs(Set<CurrentLocationMstrLang> currentLocationMstrLangs) {
		this.currentLocationMstrLangs = currentLocationMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<JobRewardTypeLang> getJobRewardTypeLangs() {
		return this.jobRewardTypeLangs;
	}

	public void setJobRewardTypeLangs(Set<JobRewardTypeLang> jobRewardTypeLangs) {
		this.jobRewardTypeLangs = jobRewardTypeLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<RewardTypeMstrLang> getRewardTypeMstrLangs() {
		return this.rewardTypeMstrLangs;
	}

	public void setRewardTypeMstrLangs(Set<RewardTypeMstrLang> rewardTypeMstrLangs) {
		this.rewardTypeMstrLangs = rewardTypeMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<GenderMstrLang> getGenderMstrLangs() {
		return this.genderMstrLangs;
	}

	public void setGenderMstrLangs(Set<GenderMstrLang> genderMstrLangs) {
		this.genderMstrLangs = genderMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<RefrlStatusMstrLang> getRefrlStatusMstrLangs() {
		return this.refrlStatusMstrLangs;
	}

	public void setRefrlStatusMstrLangs(Set<RefrlStatusMstrLang> refrlStatusMstrLangs) {
		this.refrlStatusMstrLangs = refrlStatusMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<GoalLang> getGoalLangs() {
		return this.goalLangs;
	}

	public void setGoalLangs(Set<GoalLang> goalLangs) {
		this.goalLangs = goalLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<InterviewStageMstrLang> getInterviewStageMstrLangs() {
		return this.interviewStageMstrLangs;
	}

	public void setInterviewStageMstrLangs(Set<InterviewStageMstrLang> interviewStageMstrLangs) {
		this.interviewStageMstrLangs = interviewStageMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<CurrentEmployerMstrLang> getCurrentEmployerMstrLangs() {
		return this.currentEmployerMstrLangs;
	}

	public void setCurrentEmployerMstrLangs(Set<CurrentEmployerMstrLang> currentEmployerMstrLangs) {
		this.currentEmployerMstrLangs = currentEmployerMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<EmailTemplateConfigLang> getEmailTemplateConfigLangs() {
		return this.emailTemplateConfigLangs;
	}

	public void setEmailTemplateConfigLangs(Set<EmailTemplateConfigLang> emailTemplateConfigLangs) {
		this.emailTemplateConfigLangs = emailTemplateConfigLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<CountryLang> getCountryLangs() {
		return this.countryLangs;
	}

	public void setCountryLangs(Set<CountryLang> countryLangs) {
		this.countryLangs = countryLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<CountryMstrLang> getCountryMstrLangs() {
		return this.countryMstrLangs;
	}

	public void setCountryMstrLangs(Set<CountryMstrLang> countryMstrLangs) {
		this.countryMstrLangs = countryMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<SocialMessagesLang> getSocialMessagesLangs() {
		return this.socialMessagesLangs;
	}

	public void setSocialMessagesLangs(Set<SocialMessagesLang> socialMessagesLangs) {
		this.socialMessagesLangs = socialMessagesLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<RewardMedalLang> getRewardMedalLangs() {
		return this.rewardMedalLangs;
	}

	public void setRewardMedalLangs(Set<RewardMedalLang> rewardMedalLangs) {
		this.rewardMedalLangs = rewardMedalLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<LevelRewardLang> getLevelRewardLangs() {
		return this.levelRewardLangs;
	}

	public void setLevelRewardLangs(Set<LevelRewardLang> levelRewardLangs) {
		this.levelRewardLangs = levelRewardLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<ClientInterviewStatusLang> getClientInterviewStatusLangs() {
		return this.clientInterviewStatusLangs;
	}

	public void setClientInterviewStatusLangs(Set<ClientInterviewStatusLang> clientInterviewStatusLangs) {
		this.clientInterviewStatusLangs = clientInterviewStatusLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "langMstr")
	public Set<StateLang> getStateLangs() {
		return this.stateLangs;
	}

	public void setStateLangs(Set<StateLang> stateLangs) {
		this.stateLangs = stateLangs;
	}

}
