package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LevelReward generated by hbm2java
 */
@Entity
@Table(name = "level_reward")
public class LevelReward implements java.io.Serializable {

	private Integer levelRewardSeq;
	private Reward reward;
	private int companyMstrSeq;
	private String levelCd;
	private String levelDesc;
	private int levelPriority;
	private int levelLimit;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<LevelRewardLang> levelRewardLangs = new HashSet<LevelRewardLang>(
			0);

	public LevelReward() {
	}

	public LevelReward(int companyMstrSeq, String levelCd, int levelPriority,
			int levelLimit, char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.levelCd = levelCd;
		this.levelPriority = levelPriority;
		this.levelLimit = levelLimit;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public LevelReward(Reward reward, int companyMstrSeq, String levelCd,
			String levelDesc, int levelPriority, int levelLimit, char status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm,
			Set<LevelRewardLang> levelRewardLangs) {
		this.reward = reward;
		this.companyMstrSeq = companyMstrSeq;
		this.levelCd = levelCd;
		this.levelDesc = levelDesc;
		this.levelPriority = levelPriority;
		this.levelLimit = levelLimit;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.levelRewardLangs = levelRewardLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LEVEL_REWARD_SEQ", unique = true, nullable = false)
	public Integer getLevelRewardSeq() {
		return this.levelRewardSeq;
	}

	public void setLevelRewardSeq(Integer levelRewardSeq) {
		this.levelRewardSeq = levelRewardSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REWARD_SEQ")
	public Reward getReward() {
		return this.reward;
	}

	public void setReward(Reward reward) {
		this.reward = reward;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "LEVEL_CD", nullable = false, length = 20)
	public String getLevelCd() {
		return this.levelCd;
	}

	public void setLevelCd(String levelCd) {
		this.levelCd = levelCd;
	}

	@Column(name = "LEVEL_DESC")
	public String getLevelDesc() {
		return this.levelDesc;
	}

	public void setLevelDesc(String levelDesc) {
		this.levelDesc = levelDesc;
	}

	@Column(name = "LEVEL_PRIORITY", nullable = false)
	public int getLevelPriority() {
		return this.levelPriority;
	}

	public void setLevelPriority(int levelPriority) {
		this.levelPriority = levelPriority;
	}

	@Column(name = "LEVEL_LIMIT", nullable = false)
	public int getLevelLimit() {
		return this.levelLimit;
	}

	public void setLevelLimit(int levelLimit) {
		this.levelLimit = levelLimit;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "levelReward")
	public Set<LevelRewardLang> getLevelRewardLangs() {
		return this.levelRewardLangs;
	}

	public void setLevelRewardLangs(Set<LevelRewardLang> levelRewardLangs) {
		this.levelRewardLangs = levelRewardLangs;
	}

}
