package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LocationMstrLang generated by hbm2java
 */
@Entity
@Table(name = "location_mstr_lang")
public class LocationMstrLang implements java.io.Serializable {

	private Integer locationMstrLangSeq;
	private LangMstr langMstr;
	private LocationMstr locationMstr;
	private String city;
	private String state;
	private String country;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public LocationMstrLang() {
	}

	public LocationMstrLang(LangMstr langMstr, LocationMstr locationMstr,
			char status, int createdBy, Date createDttm) {
		this.langMstr = langMstr;
		this.locationMstr = locationMstr;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public LocationMstrLang(LangMstr langMstr, LocationMstr locationMstr,
			String city, String state, String country, char status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
		this.langMstr = langMstr;
		this.locationMstr = locationMstr;
		this.city = city;
		this.state = state;
		this.country = country;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LOCATION_MSTR_LANG_SEQ", unique = true, nullable = false)
	public Integer getLocationMstrLangSeq() {
		return this.locationMstrLangSeq;
	}

	public void setLocationMstrLangSeq(Integer locationMstrLangSeq) {
		this.locationMstrLangSeq = locationMstrLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOCATION_MSTR_SEQ", nullable = false)
	public LocationMstr getLocationMstr() {
		return this.locationMstr;
	}

	public void setLocationMstr(LocationMstr locationMstr) {
		this.locationMstr = locationMstr;
	}

	@Column(name = "CITY", length = 300)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 400)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTRY", length = 500)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
