package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LocationMstr generated by hbm2java
 */
@Entity
@Table(name = "location_mstr")
public class LocationMstr implements java.io.Serializable {

	private Integer locationMstrSeq;
	private int companyMstrSeq;
	private String city;
	private String postalCd;
	private String state;
	private String country;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<CampaignLocation> campaignLocations = new HashSet<CampaignLocation>(
			0);
	private Set<LocationMstrLang> locationMstrLangs = new HashSet<LocationMstrLang>(
			0);
	private Set<JobLocation> jobLocations = new HashSet<JobLocation>(0);
	private Set<UserProfile> userProfiles = new HashSet<UserProfile>(0);

	public LocationMstr() {
	}

	public LocationMstr(int companyMstrSeq, char status, int createdBy,
			Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public LocationMstr(int companyMstrSeq, String city, String postalCd,
			String state, String country, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm,
			Set<CampaignLocation> campaignLocations,
			Set<LocationMstrLang> locationMstrLangs,
			Set<JobLocation> jobLocations, Set<UserProfile> userProfiles) {
		this.companyMstrSeq = companyMstrSeq;
		this.city = city;
		this.postalCd = postalCd;
		this.state = state;
		this.country = country;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.campaignLocations = campaignLocations;
		this.locationMstrLangs = locationMstrLangs;
		this.jobLocations = jobLocations;
		this.userProfiles = userProfiles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LOCATION_MSTR_SEQ", unique = true, nullable = false)
	public Integer getLocationMstrSeq() {
		return this.locationMstrSeq;
	}

	public void setLocationMstrSeq(Integer locationMstrSeq) {
		this.locationMstrSeq = locationMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "CITY", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "POSTAL_CD", length = 20)
	public String getPostalCd() {
		return this.postalCd;
	}

	public void setPostalCd(String postalCd) {
		this.postalCd = postalCd;
	}

	@Column(name = "STATE", length = 30)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTRY", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationMstr")
	public Set<CampaignLocation> getCampaignLocations() {
		return this.campaignLocations;
	}

	public void setCampaignLocations(Set<CampaignLocation> campaignLocations) {
		this.campaignLocations = campaignLocations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationMstr")
	public Set<LocationMstrLang> getLocationMstrLangs() {
		return this.locationMstrLangs;
	}

	public void setLocationMstrLangs(Set<LocationMstrLang> locationMstrLangs) {
		this.locationMstrLangs = locationMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locationMstr")
	public Set<JobLocation> getJobLocations() {
		return this.jobLocations;
	}

	public void setJobLocations(Set<JobLocation> jobLocations) {
		this.jobLocations = jobLocations;
	}
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="locationMstr")
    public Set<UserProfile> getUserProfiles() {
        return this.userProfiles;
    }
    
    public void setUserProfiles(Set<UserProfile> userProfiles) {
        this.userProfiles = userProfiles;
    }

}
