package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginHistory generated by hbm2java
 */
@Entity
@Table(name = "login_history")
public class LoginHistory implements java.io.Serializable {

	private Integer loginHistorySeq;
	private UserProfile userProfile;
	private int companyMstrSeq;
	private Date loginDttm;
	private Date logoutDttm;
	private String ipAddress;
	private String userAgent;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public LoginHistory() {
	}

	public LoginHistory(UserProfile userProfile, int companyMstrSeq,
			Date loginDttm, char status, int createdBy, Date createDttm) {
		this.userProfile = userProfile;
		this.companyMstrSeq = companyMstrSeq;
		this.loginDttm = loginDttm;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public LoginHistory(UserProfile userProfile, int companyMstrSeq,
			Date loginDttm, Date logoutDttm, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm) {
		this.userProfile = userProfile;
		this.companyMstrSeq = companyMstrSeq;
		this.loginDttm = loginDttm;
		this.logoutDttm = logoutDttm;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LOGIN_HISTORY_SEQ", unique = true, nullable = false)
	public Integer getLoginHistorySeq() {
		return this.loginHistorySeq;
	}

	public void setLoginHistorySeq(Integer loginHistorySeq) {
		this.loginHistorySeq = loginHistorySeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PROFILE_SEQ", nullable = false)
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOGIN_DTTM", nullable = false, length = 19)
	public Date getLoginDttm() {
		return this.loginDttm;
	}

	public void setLoginDttm(Date loginDttm) {
		this.loginDttm = loginDttm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOGOUT_DTTM", length = 19)
	public Date getLogoutDttm() {
		return this.logoutDttm;
	}

	public void setLogoutDttm(Date logoutDttm) {
		this.logoutDttm = logoutDttm;
	}
	
	@Column(name = "IP_ADDRESS", length = 20)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}
	
	@Column(name = "USER_AGENT", length = 255)
	public String getUserAgent() {
		return this.userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
