package com.ripplehire.candidate.entities;
// Generated 13 Sep, 2016 1:33:22 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MphasisCandImport generated by hbm2java
 */
@Entity
@Table(name = "mphasis_cand_import")
public class MphasisCandImport implements java.io.Serializable {

	private Integer mphasisCandImportSeq;
	private int etlFileLogSeq;
	private String positionNo;
	private String jobId;
	private String applicantId;
	private String emplId;
	private String firstName;
	private String lastName;
	private String dob;
	private String emailId;
	private String recEmail;
	private String status;
	private Date joiningDate;
	private Date psUpdateDate;
	private String rhId;
	private String importStatus;
	private String importResult;
	private String importResultMessage;
	private String rejectionReason;
	private String salary;

	public MphasisCandImport() {
	}

	public MphasisCandImport(int etlFileLogSeq, Date psUpdateDate, String importStatus) {
		this.etlFileLogSeq = etlFileLogSeq;
		this.psUpdateDate = psUpdateDate;
		this.importStatus = importStatus;
	}

	public MphasisCandImport(int etlFileLogSeq, String positionNo, String jobId, String applicantId, String emplId,
			String firstName, String lastName, String dob, String emailId, String recEmail, String status,
			Date joiningDate, Date psUpdateDate, String rhId, String importStatus, String importResult,
			String importResultMessage, String rejectionReason, String salary) {
		this.etlFileLogSeq = etlFileLogSeq;
		this.positionNo = positionNo;
		this.jobId = jobId;
		this.applicantId = applicantId;
		this.emplId = emplId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.dob = dob;
		this.emailId = emailId;
		this.recEmail = recEmail;
		this.status = status;
		this.joiningDate = joiningDate;
		this.psUpdateDate = psUpdateDate;
		this.rhId = rhId;
		this.importStatus = importStatus;
		this.importResult = importResult;
		this.importResultMessage = importResultMessage;
		this.rejectionReason = rejectionReason;
		this.salary = salary;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MPHASIS_CAND_IMPORT_SEQ", unique = true, nullable = false)
	public Integer getMphasisCandImportSeq() {
		return this.mphasisCandImportSeq;
	}

	public void setMphasisCandImportSeq(Integer mphasisCandImportSeq) {
		this.mphasisCandImportSeq = mphasisCandImportSeq;
	}

	@Column(name = "ETL_FILE_LOG_SEQ", nullable = false)
	public int getEtlFileLogSeq() {
		return this.etlFileLogSeq;
	}

	public void setEtlFileLogSeq(int etlFileLogSeq) {
		this.etlFileLogSeq = etlFileLogSeq;
	}

	@Column(name = "POSITION_NO", length = 50)
	public String getPositionNo() {
		return this.positionNo;
	}

	public void setPositionNo(String positionNo) {
		this.positionNo = positionNo;
	}

	@Column(name = "JOB_ID", length = 50)
	public String getJobId() {
		return this.jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	@Column(name = "APPLICANT_ID", length = 50)
	public String getApplicantId() {
		return this.applicantId;
	}

	public void setApplicantId(String applicantId) {
		this.applicantId = applicantId;
	}

	@Column(name = "EMPL_ID", length = 50)
	public String getEmplId() {
		return this.emplId;
	}

	public void setEmplId(String emplId) {
		this.emplId = emplId;
	}

	@Column(name = "FIRST_NAME", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "DOB", length = 50)
	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	@Column(name = "EMAIL_ID", length = 50)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "REC_EMAIL", length = 50)
	public String getRecEmail() {
		return this.recEmail;
	}

	public void setRecEmail(String recEmail) {
		this.recEmail = recEmail;
	}

	@Column(name = "STATUS", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "JOINING_DATE", length = 10)
	public Date getJoiningDate() {
		return this.joiningDate;
	}

	public void setJoiningDate(Date joiningDate) {
		this.joiningDate = joiningDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PS_UPDATE_DATE", length = 19)
	public Date getPsUpdateDate() {
		return this.psUpdateDate;
	}

	public void setPsUpdateDate(Date psUpdateDate) {
		this.psUpdateDate = psUpdateDate;
	}

	@Column(name = "RH_ID", length = 50)
	public String getRhId() {
		return this.rhId;
	}

	public void setRhId(String rhId) {
		this.rhId = rhId;
	}

	@Column(name = "IMPORT_STATUS", nullable = false, length = 50)
	public String getImportStatus() {
		return this.importStatus;
	}

	public void setImportStatus(String importStatus) {
		this.importStatus = importStatus;
	}

	@Column(name = "IMPORT_RESULT")
	public String getImportResult() {
		return this.importResult;
	}

	public void setImportResult(String importResult) {
		this.importResult = importResult;
	}

	@Column(name = "IMPORT_RESULT_MESSAGE")
	public String getImportResultMessage() {
		return this.importResultMessage;
	}

	public void setImportResultMessage(String importResultMessage) {
		this.importResultMessage = importResultMessage;
	}

	@Column(name = "REJECTION_REASON", length = 50)
	public String getRejectionReason() {
		return this.rejectionReason;
	}

	public void setRejectionReason(String rejectionReason) {
		this.rejectionReason = rejectionReason;
	}

	@Column(name = "SALARY", length = 50)
	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

}
