package com.ripplehire.candidate.entities;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PageMstr generated by hbm2java
 */
@Entity
@Table(name = "page_mstr")
public class PageMstr implements java.io.Serializable {

	private Integer pageMstrSeq;
	private Integer companyMstrSeq;
	private String pageTitle;
	private String pageCd;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<WidgetMstr> widgetMstrs = new HashSet<WidgetMstr>(0);

	public PageMstr() {
	}

	public PageMstr(Integer companyMstrSeq, String pageTitle, String pageCd, char status, int createdBy,
			Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.pageTitle = pageTitle;
		this.pageCd = pageCd;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public PageMstr(Integer companyMstrSeq, String pageTitle, String pageCd, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm, Set<WidgetMstr> widgetMstrs) {
		this.companyMstrSeq = companyMstrSeq;
		this.pageTitle = pageTitle;
		this.pageCd = pageCd;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.widgetMstrs = widgetMstrs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PAGE_MSTR_SEQ", unique = true, nullable = false)
	public Integer getPageMstrSeq() {
		return this.pageMstrSeq;
	}

	public void setPageMstrSeq(Integer pageMstrSeq) {
		this.pageMstrSeq = pageMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public Integer getCompanyMstrSeq() {
		return companyMstrSeq;
	}

	public void setCompanyMstrSeq(Integer companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "PAGE_TITLE", nullable = false, length = 100)
	public String getPageTitle() {
		return this.pageTitle;
	}

	public void setPageTitle(String pageTitle) {
		this.pageTitle = pageTitle;
	}

	@Column(name = "PAGE_CD", nullable = false, length = 100)
	public String getPageCd() {
		return this.pageCd;
	}

	public void setPageCd(String pageCd) {
		this.pageCd = pageCd;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pageMstr")
	public Set<WidgetMstr> getWidgetMstrs() {
		return this.widgetMstrs;
	}

	public void setWidgetMstrs(Set<WidgetMstr> widgetMstrs) {
		this.widgetMstrs = widgetMstrs;
	}

}
