package com.ripplehire.candidate.entities;

// Generated May 16, 2014 11:36:58 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParentCompanyMstr generated by hbm2java
 */
@Entity
@Table(name = "parent_company_mstr")
public class ParentCompanyMstr implements java.io.Serializable {

	private Integer parentCompanyMstrSeq;
	private Integer parentCompanySeq;
	private String parentCompanyName;
	private String parentCompanyCd;
	private char showAllJobs;
	private String displayJobRewardCond;
	private char jobRewardConfig;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<CompanyMstr> companyMstrs = new HashSet<CompanyMstr>(0);
	private Set<JobRewardPolicy> jobRewardPolicies = new HashSet<JobRewardPolicy>(
			0);
	private Set<JobRewardType> jobRewardTypes = new HashSet<JobRewardType>(0);

	public ParentCompanyMstr() {
	}

	public ParentCompanyMstr(Integer parentCompanySeq, String parentCompanyName, char showAllJobs,
							 String displayJobRewardCond, char jobRewardConfig, char status,
							 int createdBy, Date createDttm) {
		this.parentCompanySeq = parentCompanySeq;
		this.parentCompanyName = parentCompanyName;
		this.showAllJobs = showAllJobs;
		this.displayJobRewardCond = displayJobRewardCond;
		this.jobRewardConfig = jobRewardConfig;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public ParentCompanyMstr(String parentCompanyName, String parentCompanyCd,
							 char showAllJobs, String displayJobRewardCond,
							 char jobRewardConfig, char status, int createdBy, Date createDttm,
							 Integer updatedBy, Date updateDttm, Set<CompanyMstr> companyMstrs,
							 Set<JobRewardPolicy> jobRewardPolicies,
							 Set<JobRewardType> jobRewardTypes) {
		this.parentCompanyName = parentCompanyName;
		this.parentCompanyCd = parentCompanyCd;
		this.showAllJobs = showAllJobs;
		this.displayJobRewardCond = displayJobRewardCond;
		this.jobRewardConfig = jobRewardConfig;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.companyMstrs = companyMstrs;
		this.jobRewardPolicies = jobRewardPolicies;
		this.jobRewardTypes = jobRewardTypes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PARENT_COMPANY_MSTR_SEQ", unique = true, nullable = false)
	public Integer getParentCompanyMstrSeq() {
		return this.parentCompanyMstrSeq;
	}

	public void setParentCompanyMstrSeq(Integer parentCompanyMstrSeq) {
		this.parentCompanyMstrSeq = parentCompanyMstrSeq;
	}

	@Column(name = "PARENT_COMPANY_SEQ", unique = true, nullable = false)
	public Integer getParentCompanySeq() {
		return this.parentCompanySeq;
	}

	public void setParentCompanySeq(Integer parentCompanySeq) {
		this.parentCompanySeq = parentCompanySeq;
	}

	@Column(name = "PARENT_COMPANY_NAME", nullable = false, length = 200)
	public String getParentCompanyName() {
		return this.parentCompanyName;
	}

	public void setParentCompanyName(String parentCompanyName) {
		this.parentCompanyName = parentCompanyName;
	}

	@Column(name = "PARENT_COMPANY_CD", length = 20)
	public String getParentCompanyCd() {
		return this.parentCompanyCd;
	}

	public void setParentCompanyCd(String parentCompanyCd) {
		this.parentCompanyCd = parentCompanyCd;
	}

	@Column(name = "SHOW_ALL_JOBS", nullable = false, length = 1)
	public char getShowAllJobs() {
		return this.showAllJobs;
	}

	public void setShowAllJobs(char showAllJobs) {
		this.showAllJobs = showAllJobs;
	}

	@Column(name = "DISPLAY_JOB_REWARD_COND", nullable = false, length = 50)
	public String getDisplayJobRewardCond() {
		return this.displayJobRewardCond;
	}

	public void setDisplayJobRewardCond(String displayJobRewardCond) {
		this.displayJobRewardCond = displayJobRewardCond;
	}

	@Column(name = "JOB_REWARD_CONFIG", nullable = false, length = 1)
	public char getJobRewardConfig() {
		return this.jobRewardConfig;
	}

	public void setJobRewardConfig(char jobRewardConfig) {
		this.jobRewardConfig = jobRewardConfig;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentCompanyMstr")
	public Set<CompanyMstr> getCompanyMstrs() {
		return this.companyMstrs;
	}

	public void setCompanyMstrs(Set<CompanyMstr> companyMstrs) {
		this.companyMstrs = companyMstrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentCompanyMstr")
	public Set<JobRewardPolicy> getJobRewardPolicies() {
		return this.jobRewardPolicies;
	}

	public void setJobRewardPolicies(Set<JobRewardPolicy> jobRewardPolicies) {
		this.jobRewardPolicies = jobRewardPolicies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentCompanyMstr")
	public Set<JobRewardType> getJobRewardTypes() {
		return this.jobRewardTypes;
	}

	public void setJobRewardTypes(Set<JobRewardType> jobRewardTypes) {
		this.jobRewardTypes = jobRewardTypes;
	}

}
