package com.ripplehire.candidate.entities;

// Generated Oct 26, 2015 4:16:51 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermissionsMstr generated by hbm2java
 */
@Entity
@Table(name = "permissions_mstr")
public class PermissionsMstr implements java.io.Serializable {

	private Integer permissionSeq;
	private String permissionCd;
	private String persmissionDesc;
	private char status;
	private int createdBy;
	private Date createdDttm;
	private Integer updatedBy;
	private Date updatedDttm;

	public PermissionsMstr() {
	}

	public PermissionsMstr(String permissionCd, String persmissionDesc,
			char status, int createdBy, Date createdDttm) {
		this.permissionCd = permissionCd;
		this.persmissionDesc = persmissionDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public PermissionsMstr(String permissionCd, String persmissionDesc, char status,
			int createdBy, Date createdDttm, Integer updatedBy, Date updatedDttm) {
		this.permissionCd = permissionCd;
		this.persmissionDesc = persmissionDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PERMISSION_SEQ", unique = true, nullable = false)
	public Integer getPermissionSeq() {
		return this.permissionSeq;
	}

	public void setPermissionSeq(Integer permissionSeq) {
		this.permissionSeq = permissionSeq;
	}

	@Column(name = "PERMISSION_CD", nullable = false, length = 50)
	public String getPermissionCd() {
		return this.permissionCd;
	}

	public void setPermissionCd(String permissionCd) {
		this.permissionCd = permissionCd;
	}

	@Column(name = "PERSMISSION_DESC", nullable = false, length = 50)
	public String getPersmissionDesc() {
		return this.persmissionDesc;
	}

	public void setPersmissionDesc(String persmissionDesc) {
		this.persmissionDesc = persmissionDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

}
