package com.ripplehire.candidate.entities;

// Generated Aug 12, 2014 2:57:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QualificationMstrLang generated by hbm2java
 */
@Entity
@Table(name = "qualification_mstr_lang")
public class QualificationMstrLang implements java.io.Serializable {

	private Integer qualificationMstrLangSeq;
	private QualificationMstr qualificationMstr;
	private LangMstr langMstr;
	private String qualificationDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public QualificationMstrLang() {
	}

	public QualificationMstrLang(QualificationMstr qualificationMstr,
			LangMstr langMstr, String qualificationDesc, char status,
			int createdBy, Date createDttm) {
		this.qualificationMstr = qualificationMstr;
		this.langMstr = langMstr;
		this.qualificationDesc = qualificationDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public QualificationMstrLang(QualificationMstr qualificationMstr,
			LangMstr langMstr, String qualificationDesc, char status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
		this.qualificationMstr = qualificationMstr;
		this.langMstr = langMstr;
		this.qualificationDesc = qualificationDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUALIFICATION_MSTR_LANG_SEQ", unique = true, nullable = false)
	public Integer getQualificationMstrLangSeq() {
		return this.qualificationMstrLangSeq;
	}

	public void setQualificationMstrLangSeq(Integer qualificationMstrLangSeq) {
		this.qualificationMstrLangSeq = qualificationMstrLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUALIFICATION_MSTR_SEQ", nullable = false)
	public QualificationMstr getQualificationMstr() {
		return this.qualificationMstr;
	}

	public void setQualificationMstr(QualificationMstr qualificationMstr) {
		this.qualificationMstr = qualificationMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@Column(name = "QUALIFICATION_DESC", nullable = false, length = 100)
	public String getQualificationDesc() {
		return this.qualificationDesc;
	}

	public void setQualificationDesc(String qualificationDesc) {
		this.qualificationDesc = qualificationDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
