package com.ripplehire.candidate.entities;

// Generated Aug 12, 2014 2:57:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QualificationMstr generated by hbm2java
 */
@Entity
@Table(name = "qualification_mstr")
public class QualificationMstr implements java.io.Serializable {

	private Integer qualificationMstrSeq;
	private int companyMstrSeq;
	private int qualificationClientKey;
	private String qualificationDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<QualificationMstrLang> qualificationMstrLangs = new HashSet<QualificationMstrLang>(
			0);
	private Set<CandidateResumedetails> candidateResumedetailses = new HashSet<CandidateResumedetails>(
			0);

	public QualificationMstr() {
	}

	public QualificationMstr(int companyMstrSeq, int qualificationClientKey,
			String qualificationDesc, char status, int createdBy,
			Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.qualificationClientKey = qualificationClientKey;
		this.qualificationDesc = qualificationDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public QualificationMstr(int companyMstrSeq, int qualificationClientKey,
			String qualificationDesc, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm,
			Set<QualificationMstrLang> qualificationMstrLangs,
			Set<CandidateResumedetails> candidateResumedetailses) {
		this.companyMstrSeq = companyMstrSeq;
		this.qualificationClientKey = qualificationClientKey;
		this.qualificationDesc = qualificationDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.qualificationMstrLangs = qualificationMstrLangs;
		this.candidateResumedetailses = candidateResumedetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUALIFICATION_MSTR_SEQ", unique = true, nullable = false)
	public Integer getQualificationMstrSeq() {
		return this.qualificationMstrSeq;
	}

	public void setQualificationMstrSeq(Integer qualificationMstrSeq) {
		this.qualificationMstrSeq = qualificationMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "QUALIFICATION_CLIENT_KEY", nullable = false)
	public int getQualificationClientKey() {
		return this.qualificationClientKey;
	}

	public void setQualificationClientKey(int qualificationClientKey) {
		this.qualificationClientKey = qualificationClientKey;
	}

	@Column(name = "QUALIFICATION_DESC", nullable = false, length = 100)
	public String getQualificationDesc() {
		return this.qualificationDesc;
	}

	public void setQualificationDesc(String qualificationDesc) {
		this.qualificationDesc = qualificationDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qualificationMstr")
	public Set<QualificationMstrLang> getQualificationMstrLangs() {
		return this.qualificationMstrLangs;
	}

	public void setQualificationMstrLangs(
			Set<QualificationMstrLang> qualificationMstrLangs) {
		this.qualificationMstrLangs = qualificationMstrLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qualificationMstr")
	public Set<CandidateResumedetails> getCandidateResumedetailses() {
		return this.candidateResumedetailses;
	}

	public void setCandidateResumedetailses(
			Set<CandidateResumedetails> candidateResumedetailses) {
		this.candidateResumedetailses = candidateResumedetailses;
	}

}
