package com.ripplehire.candidate.entities;

// Generated May 21, 2015 7:29:33 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReferralChannelConfig generated by hbm2java
 */
@Entity
@Table(name = "referral_channel_config")
public class ReferralChannelConfig implements java.io.Serializable {

	private Integer referralChannelConfigSequence;
	private int companyMstr;
	private String channelCd;
	private String channelDesc;
	private String channelType;
	private String channelImgClass;
	private int channelPriority;
	private char status;
	private char createdBy;
	private Date createdDttm;
	private Character updatedBy;
	private Date updatedDttm;

	public ReferralChannelConfig() {
	}

	public ReferralChannelConfig(int companyMstr, String channelCd,
			String channelDesc, String channelType, String channelImgClass, int channelPriority, char status,
			char createdBy, Date createdDttm) {
		this.companyMstr = companyMstr;
		this.channelCd = channelCd;
		this.channelDesc = channelDesc;
		this.channelType = channelType;
		this.channelImgClass = channelImgClass;
		this.channelPriority = channelPriority;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public ReferralChannelConfig(int companyMstr, String channelCd,
			String channelDesc, String channelType, String channelImgClass, int channelPriority, char status,
			char createdBy, Date createdDttm, Character updatedBy,
			Date updatedDttm) {
		this.companyMstr = companyMstr;
		this.channelCd = channelCd;
		this.channelDesc = channelDesc;
		this.channelType = channelType;
		this.channelImgClass = channelImgClass;
		this.channelPriority = channelPriority;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REFERRAL_CHANNEL_CONFIG_SEQUENCE", unique = true, nullable = false)
	public Integer getReferralChannelConfigSequence() {
		return this.referralChannelConfigSequence;
	}

	public void setReferralChannelConfigSequence(
			Integer referralChannelConfigSequence) {
		this.referralChannelConfigSequence = referralChannelConfigSequence;
	}

	@Column(name = "COMPANY_MSTR", nullable = false)
	public int getCompanyMstr() {
		return this.companyMstr;
	}

	public void setCompanyMstr(int companyMstr) {
		this.companyMstr = companyMstr;
	}

	@Column(name = "CHANNEL_CD", nullable = false, length = 20)
	public String getChannelCd() {
		return this.channelCd;
	}

	public void setChannelCd(String channelCd) {
		this.channelCd = channelCd;
	}

	@Column(name = "CHANNEL_DESC", nullable = false, length = 50)
	public String getChannelDesc() {
		return this.channelDesc;
	}

	public void setChannelDesc(String channelDesc) {
		this.channelDesc = channelDesc;
	}

	@Column(name = "CHANNEL_TYPE", nullable = false, length = 50)
	public String getChannelType() {
		return this.channelType;
	}

	public void setChannelType(String channelType) {
		this.channelType = channelType;
	}

	@Column(name = "CHANNEL_IMG_CLASS", nullable = false, length = 50)
	public String getChannelImgClass() {
		return this.channelImgClass;
	}

	public void setChannelImgClass(String channelImgClass) {
		this.channelImgClass = channelImgClass;
	}

	@Column(name = "CHANNEL_PRIORITY", nullable = false)
	public int getChannelPriority() {
		return this.channelPriority;
	}

	public void setChannelPriority(int channelPriority) {
		this.channelPriority = channelPriority;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 1)
	public char getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(char createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY", length = 1)
	public Character getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Character updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

}
