package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefrlStatusMstr generated by hbm2java
 */
@Entity
@Table(name = "refrl_status_mstr")
public class RefrlStatusMstr implements java.io.Serializable {

	private Integer refrlStatusMstrSeq;
	private int companyMstrSeq;
	private String refrlStatusCd;
	private String refrlStatusDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<EmplRefrl> emplRefrls = new HashSet<EmplRefrl>(0);
	private Set<RefrlStatusMstrLang> refrlStatusMstrLangs = new HashSet<RefrlStatusMstrLang>(
			0);

	public RefrlStatusMstr() {
	}

	public RefrlStatusMstr(int companyMstrSeq, String refrlStatusCd,
			char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.refrlStatusCd = refrlStatusCd;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public RefrlStatusMstr(int companyMstrSeq, String refrlStatusCd,
			String refrlStatusDesc, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm,
			Set<EmplRefrl> emplRefrls,
			Set<RefrlStatusMstrLang> refrlStatusMstrLangs) {
		this.companyMstrSeq = companyMstrSeq;
		this.refrlStatusCd = refrlStatusCd;
		this.refrlStatusDesc = refrlStatusDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.emplRefrls = emplRefrls;
		this.refrlStatusMstrLangs = refrlStatusMstrLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REFRL_STATUS_MSTR_SEQ", unique = true, nullable = false)
	public Integer getRefrlStatusMstrSeq() {
		return this.refrlStatusMstrSeq;
	}

	public void setRefrlStatusMstrSeq(Integer refrlStatusMstrSeq) {
		this.refrlStatusMstrSeq = refrlStatusMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "REFRL_STATUS_CD", nullable = false, length = 20)
	public String getRefrlStatusCd() {
		return this.refrlStatusCd;
	}

	public void setRefrlStatusCd(String refrlStatusCd) {
		this.refrlStatusCd = refrlStatusCd;
	}

	@Column(name = "REFRL_STATUS_DESC")
	public String getRefrlStatusDesc() {
		return this.refrlStatusDesc;
	}

	public void setRefrlStatusDesc(String refrlStatusDesc) {
		this.refrlStatusDesc = refrlStatusDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refrlStatusMstr")
	public Set<EmplRefrl> getEmplRefrls() {
		return this.emplRefrls;
	}

	public void setEmplRefrls(Set<EmplRefrl> emplRefrls) {
		this.emplRefrls = emplRefrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refrlStatusMstr")
	public Set<RefrlStatusMstrLang> getRefrlStatusMstrLangs() {
		return this.refrlStatusMstrLangs;
	}

	public void setRefrlStatusMstrLangs(
			Set<RefrlStatusMstrLang> refrlStatusMstrLangs) {
		this.refrlStatusMstrLangs = refrlStatusMstrLangs;
	}

}
