package com.ripplehire.candidate.entities;
// Generated 6 Oct, 2016 7:47:43 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefrlChannelHistory generated by hbm2java
 */
@Entity
@Table(name = "refrl_channel_history")
public class RefrlChannelHistory implements java.io.Serializable {

    private Integer refrlChannelHistorySeq;
    private int emplRefrlMstrSeq;
    private int refrlChannelMstrSeq;
    private Integer userProfileSeq;
    private String changeReason;
    private char status;
    private int createdBy;
    private Date createDttm;
    private Integer updatedBy;
    private Date updateDttm;

    public RefrlChannelHistory() {
    }

    public RefrlChannelHistory(int emplRefrlMstrSeq, int refrlChannelMstrSeq, String changeReason, char status,
                               int createdBy, Date createDttm) {
        this.emplRefrlMstrSeq = emplRefrlMstrSeq;
        this.refrlChannelMstrSeq = refrlChannelMstrSeq;
        this.changeReason = changeReason;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
    }

    public RefrlChannelHistory(int emplRefrlMstrSeq, int refrlChannelMstrSeq, Integer userProfileSeq,
                               String changeReason, char status, int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
        this.emplRefrlMstrSeq = emplRefrlMstrSeq;
        this.refrlChannelMstrSeq = refrlChannelMstrSeq;
        this.userProfileSeq = userProfileSeq;
        this.changeReason = changeReason;
        this.status = status;
        this.createdBy = createdBy;
        this.createDttm = createDttm;
        this.updatedBy = updatedBy;
        this.updateDttm = updateDttm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "REFRL_CHANNEL_HISTORY_SEQ", unique = true, nullable = false)
    public Integer getRefrlChannelHistorySeq() {
        return this.refrlChannelHistorySeq;
    }

    public void setRefrlChannelHistorySeq(Integer refrlChannelHistorySeq) {
        this.refrlChannelHistorySeq = refrlChannelHistorySeq;
    }

    @Column(name = "EMPL_REFRL_MSTR_SEQ", nullable = false)
    public int getEmplRefrlMstrSeq() {
        return this.emplRefrlMstrSeq;
    }

    public void setEmplRefrlMstrSeq(int emplRefrlMstrSeq) {
        this.emplRefrlMstrSeq = emplRefrlMstrSeq;
    }

    @Column(name = "REFRL_CHANNEL_MSTR_SEQ", nullable = false)
    public int getRefrlChannelMstrSeq() {
        return this.refrlChannelMstrSeq;
    }

    public void setRefrlChannelMstrSeq(int refrlChannelMstrSeq) {
        this.refrlChannelMstrSeq = refrlChannelMstrSeq;
    }

    @Column(name = "USER_PROFILE_SEQ")
    public Integer getUserProfileSeq() {
        return this.userProfileSeq;
    }

    public void setUserProfileSeq(Integer userProfileSeq) {
        this.userProfileSeq = userProfileSeq;
    }

    @Column(name = "CHANGE_REASON", nullable = false, length = 1000)
    public String getChangeReason() {
        return this.changeReason;
    }

    public void setChangeReason(String changeReason) {
        this.changeReason = changeReason;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_DTTM", nullable = false, length = 19)
    public Date getCreateDttm() {
        return this.createDttm;
    }

    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_DTTM", length = 19)
    public Date getUpdateDttm() {
        return this.updateDttm;
    }

    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }

}