package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefrlStatusMstrLang generated by hbm2java
 */
@Entity
@Table(name = "refrl_status_mstr_lang")
public class RefrlStatusMstrLang implements java.io.Serializable {

	private Integer refrlStatusMstrLangSeq;
	private LangMstr langMstr;
	private RefrlStatusMstr refrlStatusMstr;
	private String refrlStatusDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public RefrlStatusMstrLang() {
	}

	public RefrlStatusMstrLang(LangMstr langMstr,
			RefrlStatusMstr refrlStatusMstr, char status, int createdBy,
			Date createDttm) {
		this.langMstr = langMstr;
		this.refrlStatusMstr = refrlStatusMstr;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public RefrlStatusMstrLang(LangMstr langMstr,
			RefrlStatusMstr refrlStatusMstr, String refrlStatusDesc,
			char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm) {
		this.langMstr = langMstr;
		this.refrlStatusMstr = refrlStatusMstr;
		this.refrlStatusDesc = refrlStatusDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REFRL_STATUS_MSTR_LANG_SEQ", unique = true, nullable = false)
	public Integer getRefrlStatusMstrLangSeq() {
		return this.refrlStatusMstrLangSeq;
	}

	public void setRefrlStatusMstrLangSeq(Integer refrlStatusMstrLangSeq) {
		this.refrlStatusMstrLangSeq = refrlStatusMstrLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REFRL_STATUS_MSTR_SEQ", nullable = false)
	public RefrlStatusMstr getRefrlStatusMstr() {
		return this.refrlStatusMstr;
	}

	public void setRefrlStatusMstr(RefrlStatusMstr refrlStatusMstr) {
		this.refrlStatusMstr = refrlStatusMstr;
	}

	@Column(name = "REFRL_STATUS_DESC", length = 500)
	public String getRefrlStatusDesc() {
		return this.refrlStatusDesc;
	}

	public void setRefrlStatusDesc(String refrlStatusDesc) {
		this.refrlStatusDesc = refrlStatusDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
