package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefrlChannelMstrLang generated by hbm2java
 */
@Entity
@Table(name = "refrl_channel_mstr_lang")
public class RefrlChannelMstrLang implements java.io.Serializable {

	private Integer refrlChannelMstrLangSeq;
	private RefrlChannelMstr refrlChannelMstr;
	private LangMstr langMstr;
	private String refrlChannelDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public RefrlChannelMstrLang() {
	}

	public RefrlChannelMstrLang(RefrlChannelMstr refrlChannelMstr,
			LangMstr langMstr, char status, int createdBy, Date createDttm) {
		this.refrlChannelMstr = refrlChannelMstr;
		this.langMstr = langMstr;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public RefrlChannelMstrLang(RefrlChannelMstr refrlChannelMstr,
			LangMstr langMstr, String refrlChannelDesc, char status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm) {
		this.refrlChannelMstr = refrlChannelMstr;
		this.langMstr = langMstr;
		this.refrlChannelDesc = refrlChannelDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REFRL_CHANNEL_MSTR_LANG_SEQ", unique = true, nullable = false)
	public Integer getRefrlChannelMstrLangSeq() {
		return this.refrlChannelMstrLangSeq;
	}

	public void setRefrlChannelMstrLangSeq(Integer refrlChannelMstrLangSeq) {
		this.refrlChannelMstrLangSeq = refrlChannelMstrLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REFRL_CHANNEL_MSTR_SEQ", nullable = false)
	public RefrlChannelMstr getRefrlChannelMstr() {
		return this.refrlChannelMstr;
	}

	public void setRefrlChannelMstr(RefrlChannelMstr refrlChannelMstr) {
		this.refrlChannelMstr = refrlChannelMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@Column(name = "REFRL_CHANNEL_DESC", length = 500)
	public String getRefrlChannelDesc() {
		return this.refrlChannelDesc;
	}

	public void setRefrlChannelDesc(String refrlChannelDesc) {
		this.refrlChannelDesc = refrlChannelDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
