package com.ripplehire.candidate.entities;

// Generated Sep 5, 2014 12:37:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RelationshipMstr generated by hbm2java
 */
@Entity
@Table(name = "relationship_mstr")
public class RelationshipMstr implements java.io.Serializable {

	private Integer relationshipMstrSeq;
	private int companyMstrSeq;
	private String relationshipCd;
	private String relationshipDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
    private Integer displayOrder;
	private Set<EmplRefrl> emplRefrls = new HashSet<EmplRefrl>(0);
	private Set<CandidateResumedetails> candidateResumedetailses = new HashSet<CandidateResumedetails>(
			0);
	private Set<RelationshipMstrLang> relationshipMstrLangs = new HashSet<RelationshipMstrLang>(
			0);

	public RelationshipMstr() {
	}

	public RelationshipMstr(int companyMstrSeq, String relationshipCd,
			char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.relationshipCd = relationshipCd;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public RelationshipMstr(int companyMstrSeq, String relationshipCd,
			String relationshipDesc, char status, int createdBy,
			Date createDttm, Integer updatedBy, Date updateDttm,
			Set<EmplRefrl> emplRefrls,
			Set<CandidateResumedetails> candidateResumedetailses,
			Set<RelationshipMstrLang> relationshipMstrLangs) {
		this.companyMstrSeq = companyMstrSeq;
		this.relationshipCd = relationshipCd;
		this.relationshipDesc = relationshipDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.emplRefrls = emplRefrls;
		this.candidateResumedetailses = candidateResumedetailses;
		this.relationshipMstrLangs = relationshipMstrLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RELATIONSHIP_MSTR_SEQ", unique = true, nullable = false)
	public Integer getRelationshipMstrSeq() {
		return this.relationshipMstrSeq;
	}

	public void setRelationshipMstrSeq(Integer relationshipMstrSeq) {
		this.relationshipMstrSeq = relationshipMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "RELATIONSHIP_CD", nullable = false, length = 20)
	public String getRelationshipCd() {
		return this.relationshipCd;
	}

	public void setRelationshipCd(String relationshipCd) {
		this.relationshipCd = relationshipCd;
	}

	@Column(name = "RELATIONSHIP_DESC")
	public String getRelationshipDesc() {
		return this.relationshipDesc;
	}

	public void setRelationshipDesc(String relationshipDesc) {
		this.relationshipDesc = relationshipDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relationshipMstr")
	public Set<EmplRefrl> getEmplRefrls() {
		return this.emplRefrls;
	}

	public void setEmplRefrls(Set<EmplRefrl> emplRefrls) {
		this.emplRefrls = emplRefrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relationshipMstr")
	public Set<CandidateResumedetails> getCandidateResumedetailses() {
		return this.candidateResumedetailses;
	}

	public void setCandidateResumedetailses(
			Set<CandidateResumedetails> candidateResumedetailses) {
		this.candidateResumedetailses = candidateResumedetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relationshipMstr")
	public Set<RelationshipMstrLang> getRelationshipMstrLangs() {
		return this.relationshipMstrLangs;
	}

	public void setRelationshipMstrLangs(
			Set<RelationshipMstrLang> relationshipMstrLangs) {
		this.relationshipMstrLangs = relationshipMstrLangs;
	}

    @Column(name = "DISPLAY_ORDER")
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
}
