package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RewardTypeMstrLang generated by hbm2java
 */
@Entity
@Table(name = "reward_type_mstr_lang")
public class RewardTypeMstrLang implements java.io.Serializable {

	private Integer rewardTypeMstrLangSeq;
	private LangMstr langMstr;
	private RewardTypeMstr rewardTypeMstr;
	private String rewardTypeDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public RewardTypeMstrLang() {
	}

	public RewardTypeMstrLang(LangMstr langMstr, RewardTypeMstr rewardTypeMstr,
			char status, int createdBy, Date createDttm) {
		this.langMstr = langMstr;
		this.rewardTypeMstr = rewardTypeMstr;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public RewardTypeMstrLang(LangMstr langMstr, RewardTypeMstr rewardTypeMstr,
			String rewardTypeDesc, char status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm) {
		this.langMstr = langMstr;
		this.rewardTypeMstr = rewardTypeMstr;
		this.rewardTypeDesc = rewardTypeDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REWARD_TYPE_MSTR_LANG_SEQ", unique = true, nullable = false)
	public Integer getRewardTypeMstrLangSeq() {
		return this.rewardTypeMstrLangSeq;
	}

	public void setRewardTypeMstrLangSeq(Integer rewardTypeMstrLangSeq) {
		this.rewardTypeMstrLangSeq = rewardTypeMstrLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REWARD_TYPE_MSTR_SEQ", nullable = false)
	public RewardTypeMstr getRewardTypeMstr() {
		return this.rewardTypeMstr;
	}

	public void setRewardTypeMstr(RewardTypeMstr rewardTypeMstr) {
		this.rewardTypeMstr = rewardTypeMstr;
	}

	@Column(name = "REWARD_TYPE_DESC", length = 30)
	public String getRewardTypeDesc() {
		return this.rewardTypeDesc;
	}

	public void setRewardTypeDesc(String rewardTypeDesc) {
		this.rewardTypeDesc = rewardTypeDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
