package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reward generated by hbm2java
 */
@Entity
@Table(name = "reward")
public class Reward implements java.io.Serializable {

	private Integer rewardSeq;
	private ActivityMstr activityMstr;
	private RewardTypeMstr rewardTypeMstr;
	private int companyMstrSeq;
	private String rewardDesc;
	private Integer rewardQty;
	private Integer rewardCounts;
	private String rewardFrequency;
	private String rewardRelease;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<ContestReward> contestRewards = new HashSet<ContestReward>(0);
	private Set<EmplActivity> emplActivities = new HashSet<EmplActivity>(0);
	private Set<GoalReward> goalRewards = new HashSet<GoalReward>(0);
	private Set<LevelReward> levelRewards = new HashSet<LevelReward>(0);
	private Set<RewardMedal> rewardMedals = new HashSet<RewardMedal>(0);
	private Set<JobRewardRule> jobRewardRules = new HashSet<JobRewardRule>(0);
	private Set<EmplReward> emplRewards = new HashSet<EmplReward>(0);
	private Set<RewardBadge> rewardBadges = new HashSet<RewardBadge>(0);
	private Set<JobReward> jobRewards = new HashSet<JobReward>(0);
	private Set<ActivitystageReward> activitystageRewards = new HashSet<ActivitystageReward>(
			0);

	public Reward() {
	}

	public Reward(ActivityMstr activityMstr, RewardTypeMstr rewardTypeMstr,
			int companyMstrSeq, String rewardFrequency, char status,
			int createdBy, Date createDttm) {
		this.activityMstr = activityMstr;
		this.rewardTypeMstr = rewardTypeMstr;
		this.companyMstrSeq = companyMstrSeq;
		this.rewardFrequency = rewardFrequency;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public Reward(ActivityMstr activityMstr, RewardTypeMstr rewardTypeMstr,
			int companyMstrSeq, String rewardDesc, Integer rewardQty,
			Integer rewardCounts, String rewardFrequency, String rewardRelease, char status,
			int createdBy, Date createDttm, Integer updatedBy, Date updateDttm,
			Set<ContestReward> contestRewards,
			Set<EmplActivity> emplActivities, Set<GoalReward> goalRewards,
			Set<LevelReward> levelRewards, Set<RewardMedal> rewardMedals,
			Set<JobRewardRule> jobRewardRules, Set<EmplReward> emplRewards,
			Set<RewardBadge> rewardBadges, Set<JobReward> jobRewards,
			Set<ActivitystageReward> activitystageRewards) {
		this.activityMstr = activityMstr;
		this.rewardTypeMstr = rewardTypeMstr;
		this.companyMstrSeq = companyMstrSeq;
		this.rewardDesc = rewardDesc;
		this.rewardQty = rewardQty;
		this.rewardCounts = rewardCounts;
		this.rewardFrequency = rewardFrequency;
		this.rewardRelease = rewardRelease;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.contestRewards = contestRewards;
		this.emplActivities = emplActivities;
		this.goalRewards = goalRewards;
		this.levelRewards = levelRewards;
		this.rewardMedals = rewardMedals;
		this.jobRewardRules = jobRewardRules;
		this.emplRewards = emplRewards;
		this.rewardBadges = rewardBadges;
		this.jobRewards = jobRewards;
		this.activitystageRewards = activitystageRewards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REWARD_SEQ", unique = true, nullable = false)
	public Integer getRewardSeq() {
		return this.rewardSeq;
	}

	public void setRewardSeq(Integer rewardSeq) {
		this.rewardSeq = rewardSeq;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ACTIVITY_MSTR_SEQ", nullable = false)
	public ActivityMstr getActivityMstr() {
		return this.activityMstr;
	}

	public void setActivityMstr(ActivityMstr activityMstr) {
		this.activityMstr = activityMstr;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "REWARD_TYPE_MSTR_SEQ", nullable = false)
	public RewardTypeMstr getRewardTypeMstr() {
		return this.rewardTypeMstr;
	}

	public void setRewardTypeMstr(RewardTypeMstr rewardTypeMstr) {
		this.rewardTypeMstr = rewardTypeMstr;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "REWARD_DESC", length = 100)
	public String getRewardDesc() {
		return this.rewardDesc;
	}

	public void setRewardDesc(String rewardDesc) {
		this.rewardDesc = rewardDesc;
	}

	@Column(name = "REWARD_QTY")
	public Integer getRewardQty() {
		return this.rewardQty;
	}

	public void setRewardQty(Integer rewardQty) {
		this.rewardQty = rewardQty;
	}

	@Column(name = "REWARD_COUNTS")
	public Integer getRewardCounts() {
		return this.rewardCounts;
	}

	public void setRewardCounts(Integer rewardCounts) {
		this.rewardCounts = rewardCounts;
	}

	@Column(name = "REWARD_FREQUENCY", nullable = false, length = 10)
	public String getRewardFrequency() {
		return this.rewardFrequency;
	}

	public void setRewardFrequency(String rewardFrequency) {
		this.rewardFrequency = rewardFrequency;
	}

	@Column(name = "REWARD_RELEASE", length = 10)
	public String getRewardRelease() {
		return this.rewardRelease;
	}

	public void setRewardRelease(String rewardRelease) {
		this.rewardRelease = rewardRelease;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reward")
	public Set<ContestReward> getContestRewards() {
		return this.contestRewards;
	}

	public void setContestRewards(Set<ContestReward> contestRewards) {
		this.contestRewards = contestRewards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reward")
	public Set<EmplActivity> getEmplActivities() {
		return this.emplActivities;
	}

	public void setEmplActivities(Set<EmplActivity> emplActivities) {
		this.emplActivities = emplActivities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reward")
	public Set<GoalReward> getGoalRewards() {
		return this.goalRewards;
	}

	public void setGoalRewards(Set<GoalReward> goalRewards) {
		this.goalRewards = goalRewards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reward")
	public Set<LevelReward> getLevelRewards() {
		return this.levelRewards;
	}

	public void setLevelRewards(Set<LevelReward> levelRewards) {
		this.levelRewards = levelRewards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reward")
	public Set<RewardMedal> getRewardMedals() {
		return this.rewardMedals;
	}

	public void setRewardMedals(Set<RewardMedal> rewardMedals) {
		this.rewardMedals = rewardMedals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reward")
	public Set<JobRewardRule> getJobRewardRules() {
		return this.jobRewardRules;
	}

	public void setJobRewardRules(Set<JobRewardRule> jobRewardRules) {
		this.jobRewardRules = jobRewardRules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reward")
	public Set<EmplReward> getEmplRewards() {
		return this.emplRewards;
	}

	public void setEmplRewards(Set<EmplReward> emplRewards) {
		this.emplRewards = emplRewards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reward")
	public Set<RewardBadge> getRewardBadges() {
		return this.rewardBadges;
	}

	public void setRewardBadges(Set<RewardBadge> rewardBadges) {
		this.rewardBadges = rewardBadges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reward")
	public Set<JobReward> getJobRewards() {
		return this.jobRewards;
	}

	public void setJobRewards(Set<JobReward> jobRewards) {
		this.jobRewards = jobRewards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reward")
	public Set<ActivitystageReward> getActivitystageRewards() {
		return this.activitystageRewards;
	}

	public void setActivitystageRewards(
			Set<ActivitystageReward> activitystageRewards) {
		this.activitystageRewards = activitystageRewards;
	}

}
