package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RewardTypeMstr generated by hbm2java
 */
@Entity
@Table(name = "reward_type_mstr")
public class RewardTypeMstr implements java.io.Serializable {

	private Integer rewardTypeMstrSeq;
	private int companyMstrSeq;
	private String rewardTypeCd;
	private String rewardTypeDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<Reward> rewards = new HashSet<Reward>(0);
	private Set<RewardTypeMstrLang> rewardTypeMstrLangs = new HashSet<RewardTypeMstrLang>(
			0);

	public RewardTypeMstr() {
	}

	public RewardTypeMstr(int companyMstrSeq, String rewardTypeCd, char status,
			int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.rewardTypeCd = rewardTypeCd;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public RewardTypeMstr(int companyMstrSeq, String rewardTypeCd,
			String rewardTypeDesc, char status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm, Set<Reward> rewards,
			Set<RewardTypeMstrLang> rewardTypeMstrLangs) {
		this.companyMstrSeq = companyMstrSeq;
		this.rewardTypeCd = rewardTypeCd;
		this.rewardTypeDesc = rewardTypeDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.rewards = rewards;
		this.rewardTypeMstrLangs = rewardTypeMstrLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REWARD_TYPE_MSTR_SEQ", unique = true, nullable = false)
	public Integer getRewardTypeMstrSeq() {
		return this.rewardTypeMstrSeq;
	}

	public void setRewardTypeMstrSeq(Integer rewardTypeMstrSeq) {
		this.rewardTypeMstrSeq = rewardTypeMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "REWARD_TYPE_CD", nullable = false, length = 20)
	public String getRewardTypeCd() {
		return this.rewardTypeCd;
	}

	public void setRewardTypeCd(String rewardTypeCd) {
		this.rewardTypeCd = rewardTypeCd;
	}

	@Column(name = "REWARD_TYPE_DESC", length = 30)
	public String getRewardTypeDesc() {
		return this.rewardTypeDesc;
	}

	public void setRewardTypeDesc(String rewardTypeDesc) {
		this.rewardTypeDesc = rewardTypeDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rewardTypeMstr")
	public Set<Reward> getRewards() {
		return this.rewards;
	}

	public void setRewards(Set<Reward> rewards) {
		this.rewards = rewards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rewardTypeMstr")
	public Set<RewardTypeMstrLang> getRewardTypeMstrLangs() {
		return this.rewardTypeMstrLangs;
	}

	public void setRewardTypeMstrLangs(
			Set<RewardTypeMstrLang> rewardTypeMstrLangs) {
		this.rewardTypeMstrLangs = rewardTypeMstrLangs;
	}

}
