package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RewardBadgeLang generated by hbm2java
 */
@Entity
@Table(name = "reward_badge_lang")
public class RewardBadgeLang implements java.io.Serializable {

	private Integer rewardBadgeLangSeq;
	private LangMstr langMstr;
	private RewardBadge rewardBadge;
	private String badgeLbl;
	private String badgeDesc;
	private char status;
	private int createdBy;
	private Date createdDttm;
	private Integer updatedBy;
	private Date updatedDttm;

	public RewardBadgeLang() {
	}

	public RewardBadgeLang(LangMstr langMstr, RewardBadge rewardBadge,
			char status, int createdBy, Date createdDttm) {
		this.langMstr = langMstr;
		this.rewardBadge = rewardBadge;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public RewardBadgeLang(LangMstr langMstr, RewardBadge rewardBadge,
			String badgeLbl, String badgeDesc, char status, int createdBy,
			Date createdDttm, Integer updatedBy, Date updatedDttm) {
		this.langMstr = langMstr;
		this.rewardBadge = rewardBadge;
		this.badgeLbl = badgeLbl;
		this.badgeDesc = badgeDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "REWARD_BADGE_LANG_SEQ", unique = true, nullable = false)
	public Integer getRewardBadgeLangSeq() {
		return this.rewardBadgeLangSeq;
	}

	public void setRewardBadgeLangSeq(Integer rewardBadgeLangSeq) {
		this.rewardBadgeLangSeq = rewardBadgeLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REWARD_BADGE_SEQ", nullable = false)
	public RewardBadge getRewardBadge() {
		return this.rewardBadge;
	}

	public void setRewardBadge(RewardBadge rewardBadge) {
		this.rewardBadge = rewardBadge;
	}

	@Column(name = "BADGE_LBL", length = 500)
	public String getBadgeLbl() {
		return this.badgeLbl;
	}

	public void setBadgeLbl(String badgeLbl) {
		this.badgeLbl = badgeLbl;
	}

	@Column(name = "BADGE_DESC", length = 500)
	public String getBadgeDesc() {
		return this.badgeDesc;
	}

	public void setBadgeDesc(String badgeDesc) {
		this.badgeDesc = badgeDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

}
