package com.ripplehire.candidate.entities;

// Generated Aug 12, 2014 2:57:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SkillsMstr generated by hbm2java
 */
@Entity
@Table(name = "skills_mstr")
public class SkillsMstr implements java.io.Serializable {

	private Integer skillsMstrSeq;
	private int companyMstrSeq;
	private int skillsClientKey;
	private String skillsDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<CandidateSkills> candidateSkillses = new HashSet<CandidateSkills>(
			0);
	private Set<SkillsMstrLang> skillsMstrLangs = new HashSet<SkillsMstrLang>(0);

	public SkillsMstr() {
	}

	public SkillsMstr(int companyMstrSeq, int skillsClientKey,
			String skillsDesc, char status, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.skillsClientKey = skillsClientKey;
		this.skillsDesc = skillsDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public SkillsMstr(int companyMstrSeq, int skillsClientKey,
			String skillsDesc, char status, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm,
			Set<CandidateSkills> candidateSkillses,
			Set<SkillsMstrLang> skillsMstrLangs) {
		this.companyMstrSeq = companyMstrSeq;
		this.skillsClientKey = skillsClientKey;
		this.skillsDesc = skillsDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.candidateSkillses = candidateSkillses;
		this.skillsMstrLangs = skillsMstrLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SKILLS_MSTR_SEQ", unique = true, nullable = false)
	public Integer getSkillsMstrSeq() {
		return this.skillsMstrSeq;
	}

	public void setSkillsMstrSeq(Integer skillsMstrSeq) {
		this.skillsMstrSeq = skillsMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "SKILLS_CLIENT_KEY", nullable = false)
	public int getSkillsClientKey() {
		return this.skillsClientKey;
	}

	public void setSkillsClientKey(int skillsClientKey) {
		this.skillsClientKey = skillsClientKey;
	}

	@Column(name = "SKILLS_DESC", nullable = false, length = 100)
	public String getSkillsDesc() {
		return this.skillsDesc;
	}

	public void setSkillsDesc(String skillsDesc) {
		this.skillsDesc = skillsDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skillsMstr")
	public Set<CandidateSkills> getCandidateSkillses() {
		return this.candidateSkillses;
	}

	public void setCandidateSkillses(Set<CandidateSkills> candidateSkillses) {
		this.candidateSkillses = candidateSkillses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skillsMstr")
	public Set<SkillsMstrLang> getSkillsMstrLangs() {
		return this.skillsMstrLangs;
	}

	public void setSkillsMstrLangs(Set<SkillsMstrLang> skillsMstrLangs) {
		this.skillsMstrLangs = skillsMstrLangs;
	}

}
