package com.ripplehire.candidate.entities;
// Generated Jun 22, 2016 8:07:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SocialMessagesLang generated by hbm2java
 */
@Entity
@Table(name = "social_messages_lang")
public class SocialMessagesLang implements java.io.Serializable {

	private Integer socialMessagesLangSeq;
	private LangMstr langMstr;
	private SocialMessages socialMessages;
	private String socialMessage;
	private char status;
	private int createdBy;
	private Date createdDttm;
	private Integer updatedBy;
	private Date updatedDttm;

	public SocialMessagesLang() {
	}

	public SocialMessagesLang(LangMstr langMstr, SocialMessages socialMessages, String socialMessage, char status,
			int createdBy, Date createdDttm) {
		this.langMstr = langMstr;
		this.socialMessages = socialMessages;
		this.socialMessage = socialMessage;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public SocialMessagesLang(LangMstr langMstr, SocialMessages socialMessages, String socialMessage, char status,
			int createdBy, Date createdDttm, Integer updatedBy, Date updatedDttm) {
		this.langMstr = langMstr;
		this.socialMessages = socialMessages;
		this.socialMessage = socialMessage;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SOCIAL_MESSAGES_LANG_SEQ", unique = true, nullable = false)
	public Integer getSocialMessagesLangSeq() {
		return this.socialMessagesLangSeq;
	}

	public void setSocialMessagesLangSeq(Integer socialMessagesLangSeq) {
		this.socialMessagesLangSeq = socialMessagesLangSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LANG_MSTR_SEQ", nullable = false)
	public LangMstr getLangMstr() {
		return this.langMstr;
	}

	public void setLangMstr(LangMstr langMstr) {
		this.langMstr = langMstr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOCIAL_MESSAGES_SEQ", nullable = false)
	public SocialMessages getSocialMessages() {
		return this.socialMessages;
	}

	public void setSocialMessages(SocialMessages socialMessages) {
		this.socialMessages = socialMessages;
	}

	@Column(name = "SOCIAL_MESSAGE", nullable = false, length = 500)
	public String getSocialMessage() {
		return this.socialMessage;
	}

	public void setSocialMessage(String socialMessage) {
		this.socialMessage = socialMessage;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

}
