package com.ripplehire.candidate.entities;
// Generated Jun 22, 2016 8:07:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SocialMessages generated by hbm2java
 */
@Entity
@Table(name = "social_messages")
public class SocialMessages implements java.io.Serializable {

	private Integer socialMessagesSeq;
	private int companyMstrSeq;
	private String socialChannelCd;
	private UserRole userRole;
	private char status;
	private int createdBy;
	private Date createdDttm;
	private Integer updatedBy;
	private Date updatedDttm;
	private Set<SocialMessagesLang> socialMessagesLangs = new HashSet<SocialMessagesLang>(0);

	public SocialMessages() {
	}

	public SocialMessages(int companyMstrSeq, String socialChannelCd, UserRole userRole, char status, int createdBy, Date createdDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.socialChannelCd = socialChannelCd;
		this.userRole = userRole;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public SocialMessages(int companyMstrSeq, String socialChannelCd, UserRole userRole, char status, int createdBy, Date createdDttm,
			Integer updatedBy, Date updatedDttm, Set<SocialMessagesLang> socialMessagesLangs) {
		this.companyMstrSeq = companyMstrSeq;
		this.socialChannelCd = socialChannelCd;
		this.userRole = userRole;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
		this.socialMessagesLangs = socialMessagesLangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SOCIAL_MESSAGES_SEQ", unique = true, nullable = false)
	public Integer getSocialMessagesSeq() {
		return this.socialMessagesSeq;
	}

	public void setSocialMessagesSeq(Integer socialMessagesSeq) {
		this.socialMessagesSeq = socialMessagesSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "SOCIAL_CHANNEL_CD", nullable = false, length = 50)
	public String getSocialChannelCd() {
		return this.socialChannelCd;
	}

	public void setSocialChannelCd(String socialChannelCd) {
		this.socialChannelCd = socialChannelCd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ROLE_SEQ", nullable = false)
	public UserRole getUserRole() {
		return userRole;
	}

	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "socialMessages")
	public Set<SocialMessagesLang> getSocialMessagesLangs() {
		return this.socialMessagesLangs;
	}

	public void setSocialMessagesLangs(Set<SocialMessagesLang> socialMessagesLangs) {
		this.socialMessagesLangs = socialMessagesLangs;
	}

}
