package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "state")
public class State implements java.io.Serializable {

	private Integer stateSeq;
	private Country country;
	private String stateName;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Set<StateLang> stateLangs = new HashSet<StateLang>(0);
	private Set<City> cities = new HashSet<City>(0);

	public State() {
	}

	public State(Country country, String stateName, char status, int createdBy,
			Date createDttm) {
		this.country = country;
		this.stateName = stateName;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public State(Country country, String stateName, char status, int createdBy,
			Date createDttm, Set<StateLang> stateLangs, Set<City> cities) {
		this.country = country;
		this.stateName = stateName;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.stateLangs = stateLangs;
		this.cities = cities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STATE_SEQ", unique = true, nullable = false)
	public Integer getStateSeq() {
		return this.stateSeq;
	}

	public void setStateSeq(Integer stateSeq) {
		this.stateSeq = stateSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COUNTRY_SEQ", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "STATE_NAME", nullable = false, length = 100)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "state")
	public Set<StateLang> getStateLangs() {
		return this.stateLangs;
	}

	public void setStateLangs(Set<StateLang> stateLangs) {
		this.stateLangs = stateLangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "state")
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
