package com.ripplehire.candidate.entities;
// Generated 25 Aug, 2016 4:49:45 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SystemErrorLog generated by hbm2java
 */
@Entity
@Table(name = "system_error_log")
public class SystemErrorLog implements java.io.Serializable {

	private Integer systemErrorLogSeq;
	private UserProfile userProfile;
	private int companyMstrSeq;
	private String requestName;
	private String className;
	private String exceptionMsg;
	private char status;
	private int createdBy;
	private Date createDttm;

	public SystemErrorLog() {
	}

	public SystemErrorLog(UserProfile userProfile, char status, int createdBy, Date createDttm) {
		this.userProfile = userProfile;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public SystemErrorLog(UserProfile userProfile, String requestName, String className, char status, int createdBy,
			Date createDttm) {
		this.userProfile = userProfile;
		this.requestName = requestName;
		this.className = className;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYSTEM_ERROR_LOG_SEQ", unique = true, nullable = false)
	public Integer getSystemErrorLogSeq() {
		return this.systemErrorLogSeq;
	}

	public void setSystemErrorLogSeq(Integer systemErrorLogSeq) {
		this.systemErrorLogSeq = systemErrorLogSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PROFILE_SEQ")
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "REQUEST_NAME", length = 500)
	public String getRequestName() {
		return this.requestName;
	}

	public void setRequestName(String requestName) {
		this.requestName = requestName;
	}

	@Column(name = "CLASS_NAME", length = 500)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "EXCEPTION_MSG", length = 1000)
	public String getExceptionMsg() {
		return exceptionMsg;
	}

	public void setExceptionMsg(String exceptionMsg) {
		this.exceptionMsg = exceptionMsg;
	}
}
