package com.ripplehire.candidate.entities;

// Generated Mar 6, 2014 7:42:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role")
public class UserRole implements java.io.Serializable {

	private Integer userRoleSeq;
	private int companyMstrSeq;
	private String userRoleCd;
	private String userRoleDesc;
	private char status;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;
	private Set<UserProfile> userProfiles = new HashSet<UserProfile>(0);
	private Set<ActivityMstr> activityMstrs = new HashSet<ActivityMstr>(0);
	private Set<SocialMessages> socialMessageses = new HashSet<SocialMessages>(0);

	public UserRole() {
	}

	public UserRole(int companyMstrSeq, String userRoleCd, char status,
			int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.userRoleCd = userRoleCd;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public UserRole(int companyMstrSeq, String userRoleCd, String userRoleDesc,
			char status, int createdBy, Date createDttm, Integer updatedBy,
			Date updateDttm, Set<UserProfile> userProfiles,
			Set<ActivityMstr> activityMstrs, Set<SocialMessages> socialMessageses) {
		this.companyMstrSeq = companyMstrSeq;
		this.userRoleCd = userRoleCd;
		this.userRoleDesc = userRoleDesc;
		this.status = status;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
		this.userProfiles = userProfiles;
		this.activityMstrs = activityMstrs;
		this.socialMessageses = socialMessageses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_ROLE_SEQ", unique = true, nullable = false)
	public Integer getUserRoleSeq() {
		return this.userRoleSeq;
	}

	public void setUserRoleSeq(Integer userRoleSeq) {
		this.userRoleSeq = userRoleSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public int getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(int companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "USER_ROLE_CD", nullable = false, length = 20)
	public String getUserRoleCd() {
		return this.userRoleCd;
	}

	public void setUserRoleCd(String userRoleCd) {
		this.userRoleCd = userRoleCd;
	}

	@Column(name = "USER_ROLE_DESC", length = 100)
	public String getUserRoleDesc() {
		return this.userRoleDesc;
	}

	public void setUserRoleDesc(String userRoleDesc) {
		this.userRoleDesc = userRoleDesc;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRole")
	public Set<UserProfile> getUserProfiles() {
		return this.userProfiles;
	}

	public void setUserProfiles(Set<UserProfile> userProfiles) {
		this.userProfiles = userProfiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRole")
	public Set<ActivityMstr> getActivityMstrs() {
		return this.activityMstrs;
	}

	public void setActivityMstrs(Set<ActivityMstr> activityMstrs) {
		this.activityMstrs = activityMstrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRole")
	public Set<SocialMessages> getSocialMessageses() {
		return socialMessageses;
	}

	public void setSocialMessageses(Set<SocialMessages> socialMessageses) {
		this.socialMessageses = socialMessageses;
	}
}
