package com.ripplehire.candidate.entities;
// Generated 19 Dec, 2016 4:03:53 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserProfilePermissions generated by hbm2java
 */
@Entity
@Table(name = "user_profile_permissions")
public class UserProfilePermissions implements java.io.Serializable {

	private Integer userProfilePermissionSeq;
	private UserProfile userProfile;
	private PermissionsMstr permissionsMstr;
	private Integer companyMstrSeq;
	private char status;
	private int createdBy;
	private Date createdDttm;
	private Integer updatedBy;
	private Date updatedDttm;

	public UserProfilePermissions() {
	}

	public UserProfilePermissions(char status, int createdBy, Date createdDttm) {
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public UserProfilePermissions(UserProfile userProfile, PermissionsMstr permissionsMstr, Integer companyMstrSeq,
			char status, int createdBy, Date createdDttm, Integer updatedBy, Date updatedDttm) {
		this.userProfile = userProfile;
		this.permissionsMstr = permissionsMstr;
		this.companyMstrSeq = companyMstrSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USER_PROFILE_PERMISSION_SEQ", unique = true, nullable = false)
	public Integer getUserProfilePermissionSeq() {
		return this.userProfilePermissionSeq;
	}

	public void setUserProfilePermissionSeq(Integer userProfilePermissionSeq) {
		this.userProfilePermissionSeq = userProfilePermissionSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_PROFILE_SEQ")
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMISSION_SEQ")
	public PermissionsMstr getPermissionsMstr() {
		return this.permissionsMstr;
	}

	public void setPermissionsMstr(PermissionsMstr permissionsMstr) {
		this.permissionsMstr = permissionsMstr;
	}

	@Column(name = "COMPANY_MSTR_SEQ")
	public Integer getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(Integer companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

}
