package com.ripplehire.candidate.entities;

// Generated Oct 26, 2015 4:16:51 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRolePermissions generated by hbm2java
 */
@Entity
@Table(name = "user_role_permissions")
public class UserRolePermissions implements java.io.Serializable {

	private Integer userRolePermissionSeq;
	private Integer companyMstrSeq;
	private String userRoleCd;
	private Integer permissionSeq;
	private char status;
	private int createdBy;
	private Date createdDttm;
	private Integer updatedBy;
	private Date updatedDttm;

	public UserRolePermissions() {
	}

	public UserRolePermissions(char status, int createdBy, Date createdDttm) {
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
	}

	public UserRolePermissions(Integer companyMstrSeq, String userRoleCd,
			Integer permissionSeq, char status, int createdBy, Date createdDttm,
			Integer updatedBy, Date updatedDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.userRoleCd = userRoleCd;
		this.permissionSeq = permissionSeq;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDttm = createdDttm;
		this.updatedBy = updatedBy;
		this.updatedDttm = updatedDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USER_ROLE_PERMISSION_SEQ", unique = true, nullable = false)
	public Integer getUserRolePermissionSeq() {
		return this.userRolePermissionSeq;
	}

	public void setUserRolePermissionSeq(Integer userRolePermissionSeq) {
		this.userRolePermissionSeq = userRolePermissionSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ")
	public Integer getCompanyMstrSeq() {
		return this.companyMstrSeq;
	}

	public void setCompanyMstrSeq(Integer companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@Column(name = "USER_ROLE_CD")
	public String getUserRoleCd() {
		return this.userRoleCd;
	}

	public void setUserRoleCd(String userRoleCd) {
		this.userRoleCd = userRoleCd;
	}

	@Column(name = "PERMISSION_SEQ")
	public Integer getPermissionSeq() {
		return this.permissionSeq;
	}

	public void setPermissionSeq(Integer permissionSeq) {
		this.permissionSeq = permissionSeq;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DTTM", nullable = false, length = 19)
	public Date getCreatedDttm() {
		return this.createdDttm;
	}

	public void setCreatedDttm(Date createdDttm) {
		this.createdDttm = createdDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DTTM", length = 19)
	public Date getUpdatedDttm() {
		return this.updatedDttm;
	}

	public void setUpdatedDttm(Date updatedDttm) {
		this.updatedDttm = updatedDttm;
	}

}
