package com.ripplehire.candidate.entities;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserProfileDetails generated by hbm2java
 */
@Entity
@Table(name = "user_coins_history")
public class UserCoinsHistory implements java.io.Serializable {
    private Integer userCoinsHistorySeq;
    private Integer companySeq;
    private UserProfile userProfile;
    private EmplReward emplReward;
    private CurrencyMstr currencyMstr;
    private String transactionId;
    private Integer rewardAmount;
    private Integer coinsAmount;
    private String conversionRate;
    private Character status;
    private Integer createdBy;
    private Date createdDttm;
    private Integer updatedBy;
    private Date updatedDttm;

    public UserCoinsHistory(){}

    public UserCoinsHistory(UserProfile userProfile, Integer updatedBy, Date updatedDttm) {
        this.userProfile = userProfile;
        this.updatedBy = updatedBy;
        this.updatedDttm = updatedDttm;
    }

    public UserCoinsHistory(UserProfile userProfile, EmplReward emplReward, CurrencyMstr currencyMstr,
                            String transactionId, Integer rewardAmount, Integer coinsAmount, String conversionRate,
                            Character status, Integer createdBy, Date createdDttm, Integer updatedBy, Date updatedDttm) {
        this.userProfile = userProfile;
        this.emplReward = emplReward;
        this.currencyMstr = currencyMstr;
        this.transactionId = transactionId;
        this.rewardAmount = rewardAmount;
        this.coinsAmount = coinsAmount;
        this.conversionRate = conversionRate;
        this.status = status;
        this.createdBy = createdBy;
        this.createdDttm = createdDttm;
        this.updatedBy = updatedBy;
        this.updatedDttm = updatedDttm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "USER_COINS_HISTORY_SEQ", unique = true, nullable = false)
    public Integer getUserCoinsHistorySeq() {
        return this.userCoinsHistorySeq;
    }

    public void setUserCoinsHistorySeq(Integer userCoinsHistorySeq) {
        this.userCoinsHistorySeq = userCoinsHistorySeq;
    }

    @Column(name = "COMPANY_SEQ", nullable = false, length = 50)
    public Integer getCompanySeq() {
        return companySeq;
    }

    public void setCompanySeq(Integer companySeq) {
        this.companySeq = companySeq;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_PROFILE_SEQ", nullable = false)
    public UserProfile getUserProfile() {
        return this.userProfile;
    }

    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EMPL_REWARD_SEQ", nullable = false)
    public EmplReward getEmplReward() {
        return emplReward;
    }

    public void setEmplReward(EmplReward emplReward) {
        this.emplReward = emplReward;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CURRENCY_MSTR_SEQ", nullable = false)
    public CurrencyMstr getCurrencyMstr() {
        return currencyMstr;
    }

    public void setCurrencyMstr(CurrencyMstr currencyMstr) {
        this.currencyMstr = currencyMstr;
    }

    @Column(name = "TRANSACTION_ID", nullable = false, length = 50)
    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    @Column(name = "REWARD_AMOUNT", nullable = false, length = 50)
    public Integer getRewardAmount() {
        return rewardAmount;
    }

    public void setRewardAmount(Integer rewardAmount) {
        this.rewardAmount = rewardAmount;
    }

    @Column(name = "COINS_AMOUNT", nullable = false, length = 11)
    public Integer getCoinsAmount() {
        return coinsAmount;
    }

    public void setCoinsAmount(Integer coinsAmount) {
        this.coinsAmount = coinsAmount;
    }

    @Column(name = "CONVERSION_RATE", nullable = false, length = 11)
    public String getConversionRate() {
        return conversionRate;
    }

    public void setConversionRate(String conversionRate) {
        this.conversionRate = conversionRate;
    }

    @Column(name = "STATUS", length = 1)
    public Character getStatus() {
        return this.status;
    }

    public void setStatus(Character status) {
        this.status = status;
    }

    @Column(name = "CREATED_BY")
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_DTTM", length = 19)
    public Date getCreatedDttm() {
        return this.createdDttm;
    }

    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_DTTM", length = 19)
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }

    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }
}
