package com.ripplehire.candidate.entities;

// Generated Jul 14, 2015 6:30:24 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UserCompanyConfig generated by hbm2java
 */
@Entity
@Table(name = "user_company_config")
public class UserCompanyConfig implements java.io.Serializable {

    private Integer userCompanyConfigSeq;
    private CompanyMstr companyMstr;
    private Integer userProfileSeq;
    private Integer userRoleSeq;
    private char isDefault;
    private char status;
    private int createdBy;
    private Date createdDttm;
    private Integer updatedBy;
    private Date updatedDttm;

    public UserCompanyConfig() {
    }

    public UserCompanyConfig(Integer userProfileSeq, int createdBy,
                                 Date createdDttm) {
        this.userProfileSeq = userProfileSeq;
        this.createdBy = createdBy;
        this.createdDttm = createdDttm;
    }

    public UserCompanyConfig(CompanyMstr companyMstr, Integer userProfileSeq, Integer userRoleSeq, char status, char isDefault,
                                 int createdBy, Date createdDttm, Integer updatedBy, Date updatedDttm) {
        this.companyMstr = companyMstr;
        this.userProfileSeq = userProfileSeq;
        this.userRoleSeq = userRoleSeq;
        this.status = status;
        this.isDefault = isDefault;
        this.createdBy = createdBy;
        this.createdDttm = createdDttm;
        this.updatedBy = updatedBy;
        this.updatedDttm = updatedDttm;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "USER_COMPANY_CONFIG_SEQ", unique = true, nullable = false)
    public Integer getUserCompanyConfigSeq() {
        return this.userCompanyConfigSeq;
    }

    public void setUserCompanyConfigSeq(Integer userCompanyConfigSeq) {
        this.userCompanyConfigSeq = userCompanyConfigSeq;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "COMPANY_MSTR_SEQ")
    public CompanyMstr getCompanyMstr() {
        return this.companyMstr;
    }

    public void setCompanyMstr(CompanyMstr companyMstr) {
        this.companyMstr = companyMstr;
    }

    @Column(name = "USER_PROFILE_SEQ")
    public Integer getUserProfileSeq() {
        return this.userProfileSeq;
    }

    public void setUserProfileSeq(Integer userProfileSeq) {
        this.userProfileSeq = userProfileSeq;
    }

    @Column(name = "USER_ROLE_SEQ")
    public Integer getUserRoleSeq() {
        return this.userRoleSeq;
    }

    public void setUserRoleSeq(Integer userRoleSeq) {
        this.userRoleSeq = userRoleSeq;
    }

    @Column(name = "IS_DEFAULT", nullable = false, length = 1)
    public char getIsDefault() {
        return this.isDefault;
    }

    public void setIsDefault(char isDefault) {
        this.isDefault = isDefault;
    }

    @Column(name = "STATUS", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Column(name = "CREATED_BY", nullable = false)
    public int getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_DTTM", nullable = false, length = 19)
    public Date getCreatedDttm() {
        return this.createdDttm;
    }

    public void setCreatedDttm(Date createdDttm) {
        this.createdDttm = createdDttm;
    }

    @Column(name = "UPDATED_BY")
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_DTTM", length = 19)
    public Date getUpdatedDttm() {
        return this.updatedDttm;
    }

    public void setUpdatedDttm(Date updatedDttm) {
        this.updatedDttm = updatedDttm;
    }

}
