package com.ripplehire.candidate.entities;
// Generated Jul 26, 2016 2:13:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WidgetMstr generated by hbm2java
 */
@Entity
@Table(name = "widget_mstr")
public class WidgetMstr implements java.io.Serializable {

	private Integer widgetMstrSeq;
	private Integer companyMstrSeq;
	private PageMstr pageMstr;
	private String widgetTitle;
	private int widgetType;
	private String widgetCd;
	private String implClass;
	private int widgetWidth;
	private int widgetHeight;
	private char status;
	private int priority;
 	private int widgetContainer;
	private int createdBy;
	private Date createDttm;
	private Integer updatedBy;
	private Date updateDttm;

	public WidgetMstr() {
	}

	public WidgetMstr(Integer companyMstrSeq, PageMstr pageMstr, String widgetTitle, int widgetType, String widgetCd,
			String implClass, int widgetWidth, int widgetHeight, char status, int priority, int widgetContainer, int createdBy, Date createDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.pageMstr = pageMstr;
		this.widgetTitle = widgetTitle;
		this.widgetType = widgetType;
		this.widgetCd = widgetCd;
		this.implClass = implClass;
		this.widgetWidth = widgetWidth;
		this.widgetHeight = widgetHeight;
		this.status = status;
		this.priority = priority;
		this.widgetContainer = widgetContainer;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
	}

	public WidgetMstr(Integer companyMstrSeq, PageMstr pageMstr, String widgetTitle, int widgetType, String widgetCd,
			String implClass, int widgetWidth, int widgetHeight, char status, int priority, int widgetContainer, int createdBy, Date createDttm,
			Integer updatedBy, Date updateDttm) {
		this.companyMstrSeq = companyMstrSeq;
		this.pageMstr = pageMstr;
		this.widgetTitle = widgetTitle;
		this.widgetType = widgetType;
		this.widgetCd = widgetCd;
		this.implClass = implClass;
		this.widgetWidth = widgetWidth;
		this.widgetHeight = widgetHeight;
		this.status = status;
		this.priority = priority;
		this.widgetContainer = widgetContainer;
		this.createdBy = createdBy;
		this.createDttm = createDttm;
		this.updatedBy = updatedBy;
		this.updateDttm = updateDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "WIDGET_MSTR_SEQ", unique = true, nullable = false)
	public Integer getWidgetMstrSeq() {
		return this.widgetMstrSeq;
	}

	public void setWidgetMstrSeq(Integer widgetMstrSeq) {
		this.widgetMstrSeq = widgetMstrSeq;
	}

	@Column(name = "COMPANY_MSTR_SEQ", nullable = false)
	public Integer getCompanyMstrSeq() {
		return companyMstrSeq;
	}

	public void setCompanyMstrSeq(Integer companyMstrSeq) {
		this.companyMstrSeq = companyMstrSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAGE_MSTR_SEQ", nullable = false)
	public PageMstr getPageMstr() {
		return this.pageMstr;
	}

	public void setPageMstr(PageMstr pageMstr) {
		this.pageMstr = pageMstr;
	}

	@Column(name = "WIDGET_TITLE", nullable = false, length = 100)
	public String getWidgetTitle() {
		return this.widgetTitle;
	}

	public void setWidgetTitle(String widgetTitle) {
		this.widgetTitle = widgetTitle;
	}

	@Column(name = "WIDGET_TYPE", nullable = false)
	public int getWidgetType() {
		return this.widgetType;
	}

	public void setWidgetType(int widgetType) {
		this.widgetType = widgetType;
	}

	@Column(name = "WIDGET_CD", nullable = false, length = 100)
	public String getWidgetCd() {
		return this.widgetCd;
	}

	public void setWidgetCd(String widgetCd) {
		this.widgetCd = widgetCd;
	}

	@Column(name = "IMPL_CLASS", nullable = false, length = 100)
	public String getImplClass() {
		return this.implClass;
	}

	public void setImplClass(String implClass) {
		this.implClass = implClass;
	}

	@Column(name = "WIDGET_WIDTH", nullable = false)
	public int getWidgetWidth() {
		return this.widgetWidth;
	}

	public void setWidgetWidth(int widgetWidth) {
		this.widgetWidth = widgetWidth;
	}

	@Column(name = "WIDGET_HEIGHT", nullable = false)
	public int getWidgetHeight() {
		return this.widgetHeight;
	}

	public void setWidgetHeight(int widgetHeight) {
		this.widgetHeight = widgetHeight;
	}

	@Column(name = "STATUS", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "PRIORITY", nullable = false)
 	public int getPriority() {
		return priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "WIDGET_CONTAINER", nullable = false)
 	public int getWidgetContainer() {
		return widgetContainer;
	}

	public void setWidgetContainer(int widgetContainer) {
		this.widgetContainer = widgetContainer;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DTTM", nullable = false, length = 19)
	public Date getCreateDttm() {
		return this.createDttm;
	}

	public void setCreateDttm(Date createDttm) {
		this.createDttm = createDttm;
	}

	@Column(name = "UPDATED_BY")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DTTM", length = 19)
	public Date getUpdateDttm() {
		return this.updateDttm;
	}

	public void setUpdateDttm(Date updateDttm) {
		this.updateDttm = updateDttm;
	}

}
