
package com.ripplehire.candidate.constants;

public interface EmailConstants
{

	String IMAGE_URL = "imageUrl";
	
	String CONTEST_PUBLISH_TEMPLATE = "CONTEST_PUBLISH";
    String EMAIL_TEMPLATE_CD_CANDIDATE_STATUS_MAIL_RESPONDED = "CANDIDATE_STATUS_MAIL_RESPONDED";
    String EMAIL_TEMPLATE_CD_CANDIDATE_STATUS_MAIL_ROUNDS = "CANDIDATE_STATUS_MAIL_ROUNDS";
    String EMAIL_TEMPLATE_CD_CANDIDATE_STATUS_MAIL_OFFERED = "CANDIDATE_STATUS_MAIL_OFFERED";
    String EMAIL_TEMPLATE_CD_CANDIDATE_STATUS_MAIL_HIRED = "CANDIDATE_STATUS_MAIL_HIRED";
    String EMAIL_TEMPLATE_CD_CANDIDATE_STATUS_MAIL_ONHOLD = "CANDIDATE_STATUS_MAIL_ONHOLD";
    String EMAIL_TEMPLATE_CD_CANDIDATE_STATUS_MAIL_UNHOLD = "CANDIDATE_STATUS_MAIL_UNHOLD";
    String EMAIL_TEMPLATE_CD_CANDIDATE_STATUS_MAIL_REJECT = "CANDIDATE_STATUS_MAIL_REJECT";
    String EMAIL_TEMPLATE_CD_CANDIDATE_STATUS_MAIL_RESPONDED_TO_RECRUITER = "CANDIDATE_STATUS_MAIL_RESPONDED_TO_RECRUITER";
    String EMAIL_TEMPLATE_CD_CANDIDATE_STATUS_MAIL_DUPICATE = "CANDIDATE_STATUS_MAIL_DUPLICATE";
    String EMAIL_TEMPLATE_CD_SOURCER_REMINDER = "SOURCER_REMINDER";
    String EMAIL_TEMPLATE_CD_COMMON_SOURCER_REMINDER="COMMON_SOURCER_REMINDER";
    String EMAIL_TEMPLATE_CD_MONTHLY_STATS="MONTHLY_STATS";
    String EMAIL_TEMPLATE_CD_FIRST_TIME_WELCOME_EMAIL_TO_USERS = "FIRST_TIME_WELCOME_EMAIL_TO_USERS";
    String EMAIL_TEMPLATE_CD_FIRST_TIME_WELCOME_EMAIL_TO_AGENCY = "FIRST_TIME_WELCOME_EMAIL_TO_AGENCY";
    String EMAIL_TEMPLATE_CD_WELCOME_EMAIL_TO_RECRUITERS = "WELCOME_EMAIL_TO_RECRUITERS";
    String EMAIL_TEMPLATE_CD_REJECT_EMAIL_TO_CANDIDATE = "REJECT_EMAIL_TO_CANDIDATE";
    String EMAIL_TEMPLATE_CD_OFFER_EMAIL_TO_CANDIDATE = "OFFER_EMAIL_TO_CANDIDATE";
    String EMAIL_TEMPLATE_CD_HIRED_EMAIL_TO_CANDIDATE = "HIRED_EMAIL_TO_CANDIDATE";
    String EMAIL_TEMPLATE_CD_SHORTLISTED_EMAIL_TO_CANDIDATE = "SHORTLISTED_EMAIL_TO_CANDIDATE";

    String EMAIL_TEMPLATE_CD_IJP_SHORTLISTED_EMAIL = "IJP_SHORTLISTED_EMAIL";
    String EMAIL_TEMPLATE_CD_IJP_REJECT_EMAIL = "IJP_REJECT_EMAIL";
    String EMAIL_TEMPLATE_CD_IJP_OFFER_EMAIL = "IJP_OFFER_EMAIL";
    String EMAIL_TEMPLATE_CD_IJP_HIRED_EMAIL = "IJP_HIRED_EMAIL";
    String EMAIL_TEMPLATE_CD_IJP_DAILY_EMAIL = "IJP_DAILY_EMAIL";
    String EMAIL_TEMPLATE_CD_IJP_WEEKLY_JOB_EMAIL = "IJP_WEEKLY_JOB_EMAIL";

    String EMAIL_TEMPLATE_CD_CUSTOM_ROUND_EMAIL_TO_REFERRER = "CUSTOM_ROUND_EMAIL_TO_REFERRER";
    String EMAIL_TEMPLATE_CD_INVITE_RECRUITER = "INVITE_RECRUITER";
    String EMAIL_TEMPLATE_CD_WEEKLY_VENDOR_STATS = "WEEKLY_VENDOR_STATS";
//    String EMAIL_TEMPLATE_CD_EMP_REFERRALS_REWARDING = "EMP_REFERRALS_REWARDING";
    String EMAIL_TEMPLATE_CD_NO_NEED_FOLLOWUP = "NO_NEED_FOLLOWUP";
    String EMAIL_TEMPLATE_CD_NOBLE_DEED_TODAY = "NOBLE_DEED_TODAY";
    String EMAIL_TEMPLATE_CD_REFERRING_SUPER_EASY = "REFERRING_SUPER_EASY";
//    String EMAIL_TEMPLATE_CD_QUALITY_MAILER = "QUALITY_MAILER";
    String EMAIL_TEMPLATE_CD_REVIEW_JOB = "REVIEW_JOB";
    String EMAIL_TEMPLATE_CD_INTERVIEWER_FEEDBACK_MAILER = "INTERVIEWER_FEEDBACK_MAILER";

    String EMAIL_TEMPLATE_CD_CANDIDATE_STATUS_MAIL_ROUND_TWO= "CANDIDATE_STATUS_MAIL_ROUND_TWO";
    String EMAIL_FROM_ADMIN = "admin";
    String EMAIL_FROM_NOREPLY = "noreply";
    String EMAIL_FROM_SUPPORT = "support";

    String EMAIL_TEMPLATE_CD_JOB_ASSIGNED_TO_RECRUITER="JOB_ASSIGNED_TO_RECRUITER";
    String EMAIL_TEMPLATE_CD_JOB_ASSIGNED_TO_AGENCY="JOB_ASSIGNED_TO_AGENCY";

    String EMAIL_TEMPLATE_CD_WEEKLY_JOB_MAILER = "WEEKLY_JOB_MAILER";
    String EMAIL_TEMPLATE_CD_REWARD_PROCESS_SUCCESS_MAIL_TO_EMP = "REWARD_SUCCESS_MAIL";
    String EMAIL_TEMPLATE_CD_COINS_TRANSFER_FAILED="COINS_TRANSFER_FAILED";
    String EMAIL_TEMPLATE_CD_RAW_JOB_EXPORT = "RAW_JOB_EXPORT";
    String EMAIL_TEMPLATE_CD_INTRV_REPORT_RAW_EXPORT = "INTRV_REPORT_RAW_EXPORT";
    String EMAIL_TEMPLATE_CD_FORGOT_PWD_EMAIL="FORGOT_PWD_EMAIL";
    String EMAIL_TEMPLATE_CD_LOCKED_ACC_EMAIL="LOCKED_ACC_EMAIL";
    String EMAIL_TEMPLATE_CD_WHATSAPP_REFERRAL = "WHATSAPP_REFERRAL";
    String EMAIL_TEMPLATE_CD_COFFEE_MAILER = "COFFEE_MAILER";
    String EMAIL_TEMPLATE_CD_REVIEW_INVITE = "REVIEW_INVITE";
    String EMAIL_TEMPLATE_CD_CANCEL_JOB = "CANCEL_JOB";
    String EMAIL_TEMPLATE_CD_CHANGE_SOURCE_EMAIL = "CHANGE_SOURCE_EMAIL";
    String JOB_REQUEST_MAILER = "JOB_REQUEST_MAILER";
    String JOB_APPROVE_REQUEST_MAILER = "JOB_APPROVE_REQUEST_MAILER";
    String JOB_REQUEST_NOTIFICATION_MAILER_TO_RECR = "JOB_REQUEST_NOTIFICATION_MAILER_TO_RECR";
    String REQUESTED_JOB_CONVERTED_TO_OPEN_JOB_MAILER = "REQUESTED_JOB_CONVERTED_TO_OPEN_JOB_MAILER";

    String WELCOME_USER_SMS = "WELCOME_USER_SMS";
    String JOB_USER_SMS = "JOB_USER_SMS";

    String SMS_TEMPLATE_CD_CANDIDATE_STATUS_RESPONDED = "CANDIDATE_STATUS_SMS_RESPONDED";
    String SMS_TEMPLATE_CD_CANDIDATE_STATUS_ROUNDS = "CANDIDATE_STATUS_SMS_ROUNDS";
    String SMS_TEMPLATE_CD_CANDIDATE_STATUS_OFFERED = "CANDIDATE_STATUS_SMS_OFFERED";
    String SMS_TEMPLATE_CD_CANDIDATE_STATUS_HIRED = "CANDIDATE_STATUS_SMS_HIRED";
    String SMS_TEMPLATE_CD_CANDIDATE_STATUS_ONHOLD = "CANDIDATE_STATUS_SMS_ONHOLD";
    String SMS_TEMPLATE_CD_CANDIDATE_STATUS_UNHOLD = "CANDIDATE_STATUS_SMS_UNHOLD";
    String SMS_TEMPLATE_CD_CANDIDATE_STATUS_REJECT = "CANDIDATE_STATUS_SMS_REJECT";
    String SMS_TEMPLATE_CD_CANDIDATE_STATUS_REJECT_DUPLICATE = "CANDIDATE_STATUS_SMS_REJECT_DUPLICATE";

    String SMS_TEMPLATE_CD_CANDIDATE_INTERVIEW="CANDIDATE_INTERVIEW_SMS";
    String SMS_TEMPLATE_CD_CANDIDATE_INTERVIEW_TO_EMPLOYEE="CANDIDATE_INTERVIEW_SMS_TOEMPLOYEE";

    String SMS_TEMPLATE_CD_CANDIDATE_MESSAGES_EMPLOYEE="CANDIDATE_MESSAGES_EMPLOYEE_SMS";
    String SMS_TEMPLATE_CD_EMPLOYEE_MESSAGES_CANDIDATE="EMPLOYEE_MESSAGES_CANDIDATE_SMS";
    String EMAIL_TEMPLATE_CD_TALEO_CANDIDATE_STATUS_MAIL_PREAPPLY = "TALEO_CANDIDATE_STATUS_MAIL_PREAPPLY";
    String EMAIL_TEMPLATE_CD_CANDIDATE_ACK_EMAIL="CANDIDATE_ACK_EMAIL";
    String IMAGE_SOURCE_TYPE_CID = "CID";
    String EMAIL_TEMPLATE_CD_IJP_APPLY_EMAIL = "IJP_APPLY_EMAIL";
}
