package com.ripplehire.candidate.constants;

public interface PermissionConstants {

    String SHOW_REPORTS = "SHOW_REPORTS";
    String SHOW_JOB_REQUESTS = "SHOW_JOB_REQUESTS";
    String SHOW_ALL_JOBS = "SHOW_ALL_JOBS";
    String SHOW_ALL_CAMPAIGNS = "SHOW_ALL_CAMPAIGNS";
    String SHOW_ALL_EVENTS = "SHOW_ALL_EVENTS";
    String CREATE_JOB_REQUESTS = "CREATE_JOB_REQUESTS";
    String ADD_JOB="ADD_JOB";
    String EDIT_JOB="EDIT_JOB";
    String ADD_CAMPAIGN="ADD_CAMPAIGN";
    String PERMISSION_SYSTEM_ADMINISTRATION= "SYSTEM_ADMINISTRATION";
    String PERMISSION_EDIT_ALL_JOB_REWARD = "EDIT_ALL_JOB_REWARD";
    String PERMISSION_SMS_DASHBOARD="SMS_DASHBOARD";
    String DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD";
    String DOCUMENT_UPLOAD_READ = "DOCUMENT_UPLOAD_READ";
    String SHOW_INTERVIEW_REPORT = "SHOW_INTERVIEW_REPORT";
    String VENDOR_ASSIGNMENT = "VENDOR_ASSIGNMENT";
    String DELETE_CANDIDATE = "DELETE_CANDIDATE";
}